import type { CategoryReference, PlatformInfo } from "./types"

export { PLATFORM_NAMES } from "./types"

export const NEW_CATEGORIES = [
  { name: "algo_feed_control", desc: "Control algorithmic feed recommendations; enforce chronological mode for minors", laws: "KOSA, KOSMA, CA SB 976, EU DSA" },
  { name: "addictive_design_control", desc: "Disable infinite scroll, autoplay, streaks, like counts, and daily rewards", laws: "KOSA, CT SB 3, EU DSA, UK OSA" },
  { name: "notification_curfew", desc: "Suppress notifications during defined quiet hours (e.g., 20:00-07:00)", laws: "VA SB 854, NY SAFE for Kids" },
  { name: "usage_timer_notification", desc: "Periodic usage reminders at configurable intervals (15/30/45/60 min)", laws: "MN HF 2, TN HB 1891" },
  { name: "targeted_ad_block", desc: "Block all targeted/behavioral advertising for minors", laws: "COPPA 2.0, EU DSA, India DPDPA" },
  { name: "dm_restriction", desc: "Restrict direct messaging: none, contacts_only, or everyone", laws: "CT SB 3, UK OSA" },
  { name: "age_gate", desc: "Require age verification before platform access", laws: "KOSMA, FL HB 3, Australia Online Safety Act" },
  { name: "data_deletion_request", desc: "Enable one-click data deletion request for child accounts", laws: "COPPA 2.0, NY NYCDPA" },
  { name: "geolocation_opt_in", desc: "Default geolocation sharing to off; require explicit opt-in", laws: "CT SB 3, MD Kids Code, COPPA update" },
]

export const PLATFORM_NONE: PlatformInfo[] = [
  { name: "NextDNS", support: "none" },
  { name: "CleanBrowsing", support: "none" },
  { name: "Android", support: "none" },
  { name: "Apple MDM", support: "none" },
  { name: "Microsoft", support: "none" },
]

export const CATEGORY_REFERENCE: CategoryReference[] = [
  // ─── Content (1-5) ───
  {
    id: "content_rating",
    name: "Content Rating",
    group: "content",
    description: "Controls the maximum content rating a child can access across five international rating systems (MPAA, TV, ESRB, PEGI, CSM). Enforces age-appropriate media consumption.",
    rationale: "Exposure to age-inappropriate content is one of the most well-documented harms to child development. This rule ensures platforms respect age-based content gates across all media types \u2014 movies, TV, games, and apps.",
    laws: [],
    fields: [
      { name: "max_ratings", type: "Record<string, string>", required: true, default: "age-computed", constraints: "Keys: mpaa, tv, esrb, pegi, csm. Values must be valid ratings within each system.", description: "Maximum allowed content rating per rating system" },
    ],
    exampleConfig: '{\n  "max_ratings": {\n    "mpaa": "PG",\n    "tv": "TV-Y7",\n    "esrb": "E",\n    "pegi": "7",\n    "csm": "7+"\n  }\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "G / TV-Y / E / PEGI 3 / CSM 5+" },
      { range: "7-9", enabled: true, summary: "PG / TV-Y7 / E / PEGI 7 / CSM 7+" },
      { range: "10-12", enabled: true, summary: "PG / TV-PG / E10+ / PEGI 7 / CSM 10+" },
      { range: "13-16", enabled: true, summary: "PG-13 / TV-14 / T / PEGI 12 / CSM 13+" },
      { range: "17+", enabled: true, summary: "R / TV-MA / M / PEGI 16 / CSM 17+" },
    ],
    platforms: [
      { name: "NextDNS", support: "none" },
      { name: "CleanBrowsing", support: "none" },
      { name: "Android", support: "full" },
      { name: "Apple MDM", support: "full" },
      { name: "Microsoft", support: "full" },
    ],
  },
  {
    id: "content_block_title",
    name: "Content Block by Title",
    group: "content",
    description: "Blocks specific content titles (movies, shows, games, apps) by name. Provides granular per-title blocking beyond rating-based controls.",
    rationale: "Rating systems cannot catch every objectionable title. Parents need the ability to block specific content they deem inappropriate regardless of its official rating \u2014 for example, a PG movie with themes a particular family finds unsuitable.",
    laws: [],
    fields: [
      { name: "titles", type: "string[]", required: true, default: "[]", constraints: "Array of title strings. Case-insensitive matching. Max 500 entries.", description: "List of content titles to block" },
    ],
    exampleConfig: '{\n  "titles": ["Grand Theft Auto V", "Squid Game", "South Park"]\n}',
    ageDefaults: [
      { range: "0-6", enabled: false, summary: "No titles blocked by default" },
      { range: "7-9", enabled: false, summary: "No titles blocked by default" },
      { range: "10-12", enabled: false, summary: "No titles blocked by default" },
      { range: "13-16", enabled: false, summary: "No titles blocked by default" },
      { range: "17+", enabled: false, summary: "No titles blocked by default" },
    ],
    platforms: [
      { name: "NextDNS", support: "none" },
      { name: "CleanBrowsing", support: "none" },
      { name: "Android", support: "full" },
      { name: "Apple MDM", support: "partial" },
      { name: "Microsoft", support: "full" },
    ],
  },
  {
    id: "content_allow_title",
    name: "Content Allow by Title",
    group: "content",
    description: "Explicitly allows specific content titles that would otherwise be blocked by rating or category rules. Acts as an override allowlist.",
    rationale: "Parents may want to grant exceptions for specific educational or family-approved content that falls above the child's general rating threshold \u2014 for example, allowing a PG-13 documentary for a 10-year-old.",
    laws: [],
    fields: [
      { name: "titles", type: "string[]", required: true, default: "[]", constraints: "Array of title strings. Case-insensitive matching. Max 500 entries.", description: "List of content titles to explicitly allow" },
    ],
    exampleConfig: '{\n  "titles": ["Planet Earth", "National Geographic Wild"]\n}',
    ageDefaults: [
      { range: "0-6", enabled: false, summary: "No titles allowed by default" },
      { range: "7-9", enabled: false, summary: "No titles allowed by default" },
      { range: "10-12", enabled: false, summary: "No titles allowed by default" },
      { range: "13-16", enabled: false, summary: "No titles allowed by default" },
      { range: "17+", enabled: false, summary: "No titles allowed by default" },
    ],
    platforms: [
      { name: "NextDNS", support: "none" },
      { name: "CleanBrowsing", support: "none" },
      { name: "Android", support: "full" },
      { name: "Apple MDM", support: "partial" },
      { name: "Microsoft", support: "full" },
    ],
  },
  {
    id: "content_allowlist_mode",
    name: "Content Allowlist Mode",
    group: "content",
    description: "When enabled, switches content access to allowlist-only mode \u2014 only explicitly approved content is accessible. All other content is blocked by default.",
    rationale: "For very young children or highly restricted environments, a deny-all-except-approved approach is safer than trying to block every possible harmful title. This inverts the default posture from permissive to restrictive.",
    laws: [],
    fields: [
      { name: "enabled", type: "boolean", required: true, default: "false", constraints: "true or false", description: "Whether to enable allowlist-only mode" },
    ],
    exampleConfig: '{\n  "enabled": true\n}',
    ageDefaults: [
      { range: "0-6", enabled: false, summary: "Disabled (rating-based filtering sufficient)" },
      { range: "7-9", enabled: false, summary: "Disabled" },
      { range: "10-12", enabled: false, summary: "Disabled" },
      { range: "13-16", enabled: false, summary: "Disabled" },
      { range: "17+", enabled: false, summary: "Disabled" },
    ],
    platforms: [
      { name: "NextDNS", support: "none" },
      { name: "CleanBrowsing", support: "none" },
      { name: "Android", support: "full" },
      { name: "Apple MDM", support: "partial" },
      { name: "Microsoft", support: "full" },
    ],
  },
  {
    id: "content_descriptor_block",
    name: "Content Descriptor Block",
    group: "content",
    description: "Blocks content based on specific content descriptors (violence, language, sexual content, drugs, gambling) regardless of the overall rating.",
    rationale: "A title may have an acceptable overall rating but contain specific elements a family wants to avoid. Content descriptors provide fine-grained control \u2014 for example, blocking all content flagged for gambling regardless of its rating.",
    laws: [],
    fields: [
      { name: "descriptors", type: "string[]", required: true, default: "age-computed", constraints: "Valid values: violence, language, sexual_content, drugs, gambling", description: "Content descriptors to block" },
    ],
    exampleConfig: '{\n  "descriptors": ["violence", "gambling", "drugs"]\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "All descriptors blocked" },
      { range: "7-9", enabled: true, summary: "All descriptors blocked" },
      { range: "10-12", enabled: true, summary: "violence, sexual_content, drugs, gambling" },
      { range: "13-16", enabled: true, summary: "sexual_content, drugs, gambling" },
      { range: "17+", enabled: true, summary: "gambling only" },
    ],
    platforms: [
      { name: "NextDNS", support: "none" },
      { name: "CleanBrowsing", support: "none" },
      { name: "Android", support: "full" },
      { name: "Apple MDM", support: "partial" },
      { name: "Microsoft", support: "full" },
    ],
  },
  // ─── Time (6-9) ───
  {
    id: "time_daily_limit",
    name: "Daily Screen Time Limit",
    group: "time",
    description: "Sets the maximum total screen time allowed per day in minutes. Enforced across all apps and content on supported platforms.",
    rationale: "Excessive screen time is linked to sleep disruption, reduced physical activity, and attention difficulties in children. Daily limits help families establish healthy digital habits and ensure time for offline activities.",
    laws: [],
    fields: [
      { name: "daily_minutes", type: "number", required: true, default: "age-computed", constraints: "Range: 15-480, step: 15", description: "Maximum screen time per day in minutes" },
    ],
    exampleConfig: '{\n  "daily_minutes": 120\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "60 minutes" },
      { range: "7-9", enabled: true, summary: "90 minutes" },
      { range: "10-12", enabled: true, summary: "120 minutes" },
      { range: "13-16", enabled: true, summary: "180 minutes" },
      { range: "17+", enabled: true, summary: "240 minutes" },
    ],
    platforms: [
      { name: "NextDNS", support: "none" },
      { name: "CleanBrowsing", support: "none" },
      { name: "Android", support: "full" },
      { name: "Apple MDM", support: "full" },
      { name: "Microsoft", support: "full" },
    ],
  },
  {
    id: "time_scheduled_hours",
    name: "Scheduled Usage Hours",
    group: "time",
    description: "Defines allowed usage windows for weekdays and weekends. Device access is blocked outside these hours, enforcing bedtime and school-time restrictions.",
    rationale: "Children need structured schedules that protect sleep, school time, and family time. Scheduled hours ensure devices are only accessible during parent-approved windows, preventing late-night usage and classroom distractions.",
    laws: [],
    fields: [
      { name: "schedule", type: "object", required: true, default: "age-computed", constraints: "Must include weekday and weekend sub-objects, each with start and end in HH:MM format", description: "Allowed usage schedule" },
      { name: "schedule.weekday.start", type: "string", required: true, default: "07:00", constraints: "HH:MM format, 24-hour", description: "Weekday start time" },
      { name: "schedule.weekday.end", type: "string", required: true, default: "age-computed", constraints: "HH:MM format, 24-hour", description: "Weekday end time (bedtime)" },
      { name: "schedule.weekend.start", type: "string", required: true, default: "08:00", constraints: "HH:MM format, 24-hour", description: "Weekend start time" },
      { name: "schedule.weekend.end", type: "string", required: true, default: "age-computed", constraints: "HH:MM format, 24-hour", description: "Weekend end time" },
    ],
    exampleConfig: '{\n  "schedule": {\n    "weekday": { "start": "07:00", "end": "20:00" },\n    "weekend": { "start": "08:00", "end": "21:00" }\n  }\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "Weekday 07:00-19:00, Weekend 08:00-19:00" },
      { range: "7-9", enabled: true, summary: "Weekday 07:00-20:00, Weekend 08:00-20:00" },
      { range: "10-12", enabled: true, summary: "Weekday 07:00-21:00, Weekend 08:00-21:00" },
      { range: "13-16", enabled: true, summary: "Weekday 07:00-22:00, Weekend 08:00-22:00" },
      { range: "17+", enabled: true, summary: "Weekday 07:00-23:00, Weekend 08:00-23:00" },
    ],
    platforms: [
      { name: "NextDNS", support: "none" },
      { name: "CleanBrowsing", support: "none" },
      { name: "Android", support: "full" },
      { name: "Apple MDM", support: "partial" },
      { name: "Microsoft", support: "full" },
    ],
  },
  {
    id: "time_per_app_limit",
    name: "Per-App Time Limit",
    group: "time",
    description: "Sets individual time limits for specific apps. Allows parents to restrict time on specific apps (e.g., social media) while allowing more time for educational apps.",
    rationale: "Not all screen time is equal. Parents need granular control to limit addictive apps like social media or games while allowing longer use of educational tools like Khan Academy or reading apps.",
    laws: [],
    fields: [
      { name: "limits", type: "Record<string, number>", required: true, default: "{}", constraints: "Keys: app identifiers. Values: minutes per day (15-480, step 15)", description: "Per-app daily time limits in minutes" },
    ],
    exampleConfig: '{\n  "limits": {\n    "com.instagram.android": 30,\n    "com.tiktok.android": 30,\n    "com.youtube.android": 60\n  }\n}',
    ageDefaults: [
      { range: "0-6", enabled: false, summary: "No per-app limits (daily limit sufficient)" },
      { range: "7-9", enabled: false, summary: "No per-app limits by default" },
      { range: "10-12", enabled: false, summary: "No per-app limits by default" },
      { range: "13-16", enabled: false, summary: "No per-app limits by default" },
      { range: "17+", enabled: false, summary: "No per-app limits by default" },
    ],
    platforms: [
      { name: "NextDNS", support: "none" },
      { name: "CleanBrowsing", support: "none" },
      { name: "Android", support: "full" },
      { name: "Apple MDM", support: "full" },
      { name: "Microsoft", support: "partial" },
    ],
  },
  {
    id: "time_downtime",
    name: "Scheduled Downtime",
    group: "time",
    description: "Defines specific downtime periods where device usage is fully blocked. Supports different schedules per day of the week.",
    rationale: "Downtime periods enforce mandatory screen-free time for meals, homework, sleep, and family activities. Unlike scheduled hours which define allowed windows, downtime creates explicit blocked windows that override all other settings.",
    laws: [],
    fields: [
      { name: "start", type: "string", required: true, default: "age-computed", constraints: "HH:MM format, 24-hour", description: "Downtime start time" },
      { name: "end", type: "string", required: true, default: "07:00", constraints: "HH:MM format, 24-hour", description: "Downtime end time" },
      { name: "days", type: "string[]", required: false, default: '["mon","tue","wed","thu","fri","sat","sun"]', constraints: "Valid: mon, tue, wed, thu, fri, sat, sun", description: "Days of the week when downtime applies" },
    ],
    exampleConfig: '{\n  "start": "20:00",\n  "end": "07:00",\n  "days": ["mon", "tue", "wed", "thu", "fri"]\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "19:00-07:00 daily" },
      { range: "7-9", enabled: true, summary: "20:00-07:00 daily" },
      { range: "10-12", enabled: true, summary: "21:00-07:00 daily" },
      { range: "13-16", enabled: true, summary: "22:00-07:00 daily" },
      { range: "17+", enabled: true, summary: "23:00-07:00 daily" },
    ],
    platforms: [
      { name: "NextDNS", support: "none" },
      { name: "CleanBrowsing", support: "none" },
      { name: "Android", support: "full" },
      { name: "Apple MDM", support: "partial" },
      { name: "Microsoft", support: "full" },
    ],
  },
  // ─── Purchase (10-12) ───
  {
    id: "purchase_approval",
    name: "Purchase Approval",
    group: "purchase",
    description: "Requires parent/guardian approval before any purchase can be completed. Applies to app purchases, subscriptions, and digital content.",
    rationale: "Children may not understand the financial implications of digital purchases. Approval gates prevent unauthorized spending and teach responsible consumer habits by involving parents in purchase decisions.",
    laws: [],
    fields: [
      { name: "require_approval", type: "boolean", required: true, default: "age-computed", constraints: "true or false", description: "Whether purchases require parent approval" },
    ],
    exampleConfig: '{\n  "require_approval": true\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "Approval required" },
      { range: "7-9", enabled: true, summary: "Approval required" },
      { range: "10-12", enabled: true, summary: "Approval required" },
      { range: "13-16", enabled: true, summary: "Approval required" },
      { range: "17+", enabled: false, summary: "No approval required" },
    ],
    platforms: PLATFORM_NONE,
  },
  {
    id: "purchase_spending_cap",
    name: "Monthly Spending Cap",
    group: "purchase",
    description: "Sets a maximum monthly spending limit for the child's account across all digital purchases. Resets at the start of each calendar month.",
    rationale: "Even with purchase approval enabled, a spending cap provides a hard financial boundary. This protects against rapid-fire small purchases that individually seem harmless but accumulate quickly.",
    laws: [],
    fields: [
      { name: "monthly_cap", type: "number", required: true, default: "0", constraints: "Range: 0-500 (USD). 0 means no purchases allowed.", description: "Maximum monthly spending in USD" },
    ],
    exampleConfig: '{\n  "monthly_cap": 25\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "$0 (no purchases)" },
      { range: "7-9", enabled: true, summary: "$0 (no purchases)" },
      { range: "10-12", enabled: true, summary: "$10/month" },
      { range: "13-16", enabled: true, summary: "$25/month" },
      { range: "17+", enabled: false, summary: "No cap" },
    ],
    platforms: PLATFORM_NONE,
  },
  {
    id: "purchase_block_iap",
    name: "Block In-App Purchases",
    group: "purchase",
    description: "Blocks all in-app purchases (IAP) including consumables, subscriptions, and loot boxes within apps and games.",
    rationale: "In-app purchases \u2014 especially loot boxes and microtransactions in games \u2014 are designed to exploit impulsive behavior. Blocking IAP entirely removes the most predatory monetization vectors targeting children.",
    laws: [],
    fields: [
      { name: "block_iap", type: "boolean", required: true, default: "age-computed", constraints: "true or false", description: "Whether to block all in-app purchases" },
    ],
    exampleConfig: '{\n  "block_iap": true\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "All IAP blocked" },
      { range: "7-9", enabled: true, summary: "All IAP blocked" },
      { range: "10-12", enabled: true, summary: "All IAP blocked" },
      { range: "13-16", enabled: false, summary: "IAP allowed (with approval)" },
      { range: "17+", enabled: false, summary: "IAP allowed" },
    ],
    platforms: PLATFORM_NONE,
  },
  // ─── Social (13-15) ───
  {
    id: "social_contacts",
    name: "Contact Management",
    group: "social",
    description: "Controls who the child can communicate with. In approved-only mode, only parent-approved contacts can reach the child.",
    rationale: "Stranger contact is one of the primary vectors for grooming and exploitation. Contact management ensures children only interact with vetted, parent-approved individuals across all communication channels.",
    laws: [],
    fields: [
      { name: "mode", type: "string", required: true, default: "age-computed", constraints: '"approved_only" or "anyone"', description: "Contact restriction mode" },
      { name: "approved_contacts", type: "string[]", required: false, default: "[]", constraints: "Array of contact identifiers. Max 200 entries.", description: "List of approved contact IDs when in approved_only mode" },
    ],
    exampleConfig: '{\n  "mode": "approved_only",\n  "approved_contacts": ["contact_abc123", "contact_def456"]\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "Approved contacts only" },
      { range: "7-9", enabled: true, summary: "Approved contacts only" },
      { range: "10-12", enabled: true, summary: "Approved contacts only" },
      { range: "13-16", enabled: false, summary: "Anyone (monitoring enabled)" },
      { range: "17+", enabled: false, summary: "Anyone" },
    ],
    platforms: PLATFORM_NONE,
  },
  {
    id: "social_chat_control",
    name: "Chat Control",
    group: "social",
    description: "Controls in-app chat functionality. Can be fully disabled, limited to friends only, or open to everyone.",
    rationale: "Chat features in games and apps expose children to unsupervised communication with strangers. Restricting chat to friends-only or disabling it entirely reduces exposure to harassment, bullying, and predatory contact.",
    laws: [],
    fields: [
      { name: "mode", type: "string", required: true, default: "age-computed", constraints: '"disabled", "friends_only", or "everyone"', description: "Chat restriction level" },
    ],
    exampleConfig: '{\n  "mode": "friends_only"\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "Chat disabled" },
      { range: "7-9", enabled: true, summary: "Friends only" },
      { range: "10-12", enabled: true, summary: "Friends only" },
      { range: "13-16", enabled: true, summary: "Friends only" },
      { range: "17+", enabled: false, summary: "Everyone" },
    ],
    platforms: PLATFORM_NONE,
  },
  {
    id: "social_multiplayer",
    name: "Multiplayer Gaming",
    group: "social",
    description: "Controls access to multiplayer gaming features. Can restrict to approved games only or disable multiplayer entirely.",
    rationale: "Multiplayer gaming exposes children to unmoderated voice and text chat with strangers. Restricting multiplayer to approved games ensures parents can vet the social environment of each game individually.",
    laws: [],
    fields: [
      { name: "enabled", type: "boolean", required: true, default: "age-computed", constraints: "true or false", description: "Whether multiplayer gaming is allowed" },
      { name: "approved_games", type: "string[]", required: false, default: "[]", constraints: "Array of game identifiers. Only used when enabled=true.", description: "List of approved multiplayer game IDs" },
    ],
    exampleConfig: '{\n  "enabled": true,\n  "approved_games": ["minecraft", "roblox"]\n}',
    ageDefaults: [
      { range: "0-6", enabled: false, summary: "Multiplayer disabled" },
      { range: "7-9", enabled: true, summary: "Approved games only" },
      { range: "10-12", enabled: true, summary: "Approved games only" },
      { range: "13-16", enabled: true, summary: "All multiplayer allowed" },
      { range: "17+", enabled: true, summary: "All multiplayer allowed" },
    ],
    platforms: PLATFORM_NONE,
  },
  // ─── Web (16-20) ───
  {
    id: "web_safesearch",
    name: "Safe Search",
    group: "web",
    description: "Forces safe search mode on supported search engines (Google, Bing, DuckDuckGo, YouTube). Filters explicit results from search queries.",
    rationale: "Search engines are the primary discovery mechanism for content online. Without safe search enforcement, a single search query can expose children to pornography, violence, and other harmful content.",
    laws: [],
    fields: [
      { name: "enabled", type: "boolean", required: true, default: "true", constraints: "true or false", description: "Whether to enforce safe search" },
    ],
    exampleConfig: '{\n  "enabled": true\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "Safe search on" },
      { range: "7-9", enabled: true, summary: "Safe search on" },
      { range: "10-12", enabled: true, summary: "Safe search on" },
      { range: "13-16", enabled: true, summary: "Safe search on" },
      { range: "17+", enabled: true, summary: "Safe search on" },
    ],
    platforms: [
      { name: "NextDNS", support: "full" },
      { name: "CleanBrowsing", support: "full" },
      { name: "Android", support: "none" },
      { name: "Apple MDM", support: "none" },
      { name: "Microsoft", support: "none" },
    ],
  },
  {
    id: "web_category_block",
    name: "Web Category Block",
    group: "web",
    description: "Blocks access to entire categories of websites. Categories include adult content, gambling, drugs, violence, social media, dating, and malware.",
    rationale: "Category-based blocking provides broad protection against entire classes of harmful content without requiring per-URL management. It catches new harmful sites automatically as DNS providers update their category databases.",
    laws: [],
    fields: [
      { name: "categories", type: "string[]", required: true, default: "age-computed", constraints: "Valid: adult, gambling, drugs, violence, social_media, dating, malware", description: "Website categories to block" },
    ],
    exampleConfig: '{\n  "categories": ["adult", "gambling", "drugs", "violence", "malware"]\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "All categories blocked" },
      { range: "7-9", enabled: true, summary: "All categories blocked" },
      { range: "10-12", enabled: true, summary: "adult, gambling, drugs, violence, dating, malware" },
      { range: "13-16", enabled: true, summary: "adult, gambling, drugs, malware" },
      { range: "17+", enabled: true, summary: "adult, gambling, malware" },
    ],
    platforms: [
      { name: "NextDNS", support: "full" },
      { name: "CleanBrowsing", support: "full" },
      { name: "Android", support: "none" },
      { name: "Apple MDM", support: "full" },
      { name: "Microsoft", support: "full" },
    ],
  },
  {
    id: "web_custom_allowlist",
    name: "Web Custom Allowlist",
    group: "web",
    description: "Explicitly allows specific URLs/domains that would otherwise be blocked by category or filter rules. Acts as an override for false positives.",
    rationale: "Category-based blocking can sometimes catch educational or family-approved sites. The allowlist provides a mechanism to grant exceptions without weakening the overall filtering policy.",
    laws: [],
    fields: [
      { name: "urls", type: "string[]", required: true, default: "[]", constraints: "Array of URLs or domains. Max 1000 entries.", description: "URLs/domains to explicitly allow" },
    ],
    exampleConfig: '{\n  "urls": ["khanacademy.org", "wikipedia.org", "scratch.mit.edu"]\n}',
    ageDefaults: [
      { range: "0-6", enabled: false, summary: "No custom allowlist" },
      { range: "7-9", enabled: false, summary: "No custom allowlist" },
      { range: "10-12", enabled: false, summary: "No custom allowlist" },
      { range: "13-16", enabled: false, summary: "No custom allowlist" },
      { range: "17+", enabled: false, summary: "No custom allowlist" },
    ],
    platforms: [
      { name: "NextDNS", support: "full" },
      { name: "CleanBrowsing", support: "full" },
      { name: "Android", support: "none" },
      { name: "Apple MDM", support: "none" },
      { name: "Microsoft", support: "none" },
    ],
  },
  {
    id: "web_custom_blocklist",
    name: "Web Custom Blocklist",
    group: "web",
    description: "Blocks specific URLs/domains in addition to category-based blocking. Provides per-site granularity for sites not covered by category filters.",
    rationale: "Some harmful or distracting sites may not fall into blocked categories. A custom blocklist lets parents address specific sites they've identified as problematic for their child.",
    laws: [],
    fields: [
      { name: "urls", type: "string[]", required: true, default: "[]", constraints: "Array of URLs or domains. Max 1000 entries.", description: "URLs/domains to block" },
    ],
    exampleConfig: '{\n  "urls": ["reddit.com", "4chan.org", "omegle.com"]\n}',
    ageDefaults: [
      { range: "0-6", enabled: false, summary: "No custom blocklist" },
      { range: "7-9", enabled: false, summary: "No custom blocklist" },
      { range: "10-12", enabled: false, summary: "No custom blocklist" },
      { range: "13-16", enabled: false, summary: "No custom blocklist" },
      { range: "17+", enabled: false, summary: "No custom blocklist" },
    ],
    platforms: [
      { name: "NextDNS", support: "full" },
      { name: "CleanBrowsing", support: "full" },
      { name: "Android", support: "none" },
      { name: "Apple MDM", support: "none" },
      { name: "Microsoft", support: "none" },
    ],
  },
  {
    id: "web_filter_level",
    name: "Web Filter Level",
    group: "web",
    description: "Sets the overall web filtering strictness level. Controls how aggressively content is filtered across all web access.",
    rationale: "A single filter level setting provides a simple, parent-friendly way to control overall web safety without requiring detailed category-by-category configuration. It acts as the baseline filtering posture.",
    laws: [],
    fields: [
      { name: "level", type: "string", required: true, default: "age-computed", constraints: '"strict", "moderate", or "light"', description: "Web filtering strictness level" },
    ],
    exampleConfig: '{\n  "level": "strict"\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "Strict" },
      { range: "7-9", enabled: true, summary: "Strict" },
      { range: "10-12", enabled: true, summary: "Moderate" },
      { range: "13-16", enabled: true, summary: "Light" },
      { range: "17+", enabled: true, summary: "Light" },
    ],
    platforms: [
      { name: "NextDNS", support: "full" },
      { name: "CleanBrowsing", support: "full" },
      { name: "Android", support: "none" },
      { name: "Apple MDM", support: "full" },
      { name: "Microsoft", support: "full" },
    ],
  },
  // ─── Privacy (21-24) ───
  {
    id: "privacy_location",
    name: "Location Sharing",
    group: "privacy",
    description: "Controls location sharing settings. Can be off, shared with family only, or fully on. Family-only mode allows parents to locate the child without exposing location to third parties.",
    rationale: "Location data is highly sensitive for minors. While parents need location access for safety, sharing location with apps and third parties creates tracking and profiling risks. This control separates family safety from commercial surveillance.",
    laws: [],
    fields: [
      { name: "sharing", type: "string", required: true, default: "age-computed", constraints: '"off", "family_only", or "on"', description: "Location sharing mode" },
    ],
    exampleConfig: '{\n  "sharing": "family_only"\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "Family only" },
      { range: "7-9", enabled: true, summary: "Family only" },
      { range: "10-12", enabled: true, summary: "Family only" },
      { range: "13-16", enabled: true, summary: "Family only" },
      { range: "17+", enabled: false, summary: "Off" },
    ],
    platforms: [
      { name: "NextDNS", support: "none" },
      { name: "CleanBrowsing", support: "none" },
      { name: "Android", support: "full" },
      { name: "Apple MDM", support: "none" },
      { name: "Microsoft", support: "none" },
    ],
  },
  {
    id: "privacy_profile_visibility",
    name: "Profile Visibility",
    group: "privacy",
    description: "Controls the visibility of the child's profile on platforms. Can be set to private, friends-only, or public.",
    rationale: "Public profiles expose children's personal information, photos, and activity to anyone on the internet. Restricting profile visibility reduces the risk of unwanted contact, identity theft, and profiling.",
    laws: [],
    fields: [
      { name: "visibility", type: "string", required: true, default: "age-computed", constraints: '"private", "friends", or "public"', description: "Profile visibility level" },
    ],
    exampleConfig: '{\n  "visibility": "private"\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "Private" },
      { range: "7-9", enabled: true, summary: "Private" },
      { range: "10-12", enabled: true, summary: "Friends only" },
      { range: "13-16", enabled: true, summary: "Friends only" },
      { range: "17+", enabled: true, summary: "Friends only" },
    ],
    platforms: PLATFORM_NONE,
  },
  {
    id: "privacy_data_sharing",
    name: "Data Sharing Controls",
    group: "privacy",
    description: "Controls whether the child's data can be shared with third parties for advertising or analytics purposes.",
    rationale: "Children's data is aggressively collected and monetized by ad networks and data brokers. These controls ensure parents can prevent commercial exploitation of their child's behavioral data, activity patterns, and personal information.",
    laws: [],
    fields: [
      { name: "allow_third_party", type: "boolean", required: true, default: "false", constraints: "true or false", description: "Whether third-party data sharing is allowed" },
      { name: "allow_analytics", type: "boolean", required: true, default: "false", constraints: "true or false", description: "Whether analytics data collection is allowed" },
    ],
    exampleConfig: '{\n  "allow_third_party": false,\n  "allow_analytics": false\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "All sharing blocked" },
      { range: "7-9", enabled: true, summary: "All sharing blocked" },
      { range: "10-12", enabled: true, summary: "All sharing blocked" },
      { range: "13-16", enabled: true, summary: "All sharing blocked" },
      { range: "17+", enabled: true, summary: "Analytics only" },
    ],
    platforms: PLATFORM_NONE,
  },
  {
    id: "privacy_account_creation",
    name: "Account Creation Approval",
    group: "privacy",
    description: "Requires parent approval before the child can create new accounts on platforms and services.",
    rationale: "Uncontrolled account creation allows children to bypass parental controls by creating accounts on unmonitored platforms. Approval gates ensure parents know every platform their child uses.",
    laws: [],
    fields: [
      { name: "require_approval", type: "boolean", required: true, default: "true", constraints: "true or false", description: "Whether new account creation requires parent approval" },
    ],
    exampleConfig: '{\n  "require_approval": true\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "Approval required" },
      { range: "7-9", enabled: true, summary: "Approval required" },
      { range: "10-12", enabled: true, summary: "Approval required" },
      { range: "13-16", enabled: true, summary: "Approval required" },
      { range: "17+", enabled: false, summary: "No approval required" },
    ],
    platforms: PLATFORM_NONE,
  },
  // ─── Monitoring (25-26) ───
  {
    id: "monitoring_activity",
    name: "Activity Monitoring",
    group: "monitoring",
    description: "Enables activity monitoring to track app usage, screen time, and browsing activity. Reports are made available to parents through the dashboard.",
    rationale: "Parents need visibility into their child's digital activity to identify concerning patterns \u2014 excessive gaming, late-night usage, or visits to risky sites. Activity monitoring provides this visibility without blocking access.",
    laws: [],
    fields: [
      { name: "enabled", type: "boolean", required: true, default: "true", constraints: "true or false", description: "Whether activity monitoring is enabled" },
    ],
    exampleConfig: '{\n  "enabled": true\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "Monitoring on" },
      { range: "7-9", enabled: true, summary: "Monitoring on" },
      { range: "10-12", enabled: true, summary: "Monitoring on" },
      { range: "13-16", enabled: true, summary: "Monitoring on" },
      { range: "17+", enabled: true, summary: "Monitoring on" },
    ],
    platforms: [
      { name: "NextDNS", support: "none" },
      { name: "CleanBrowsing", support: "none" },
      { name: "Android", support: "full" },
      { name: "Apple MDM", support: "none" },
      { name: "Microsoft", support: "full" },
    ],
  },
  {
    id: "monitoring_alerts",
    name: "Monitoring Alerts",
    group: "monitoring",
    description: "Configures real-time alerts sent to parents when specific events occur, such as screen time being exceeded, new apps installed, blocked content attempts, or location changes.",
    rationale: "Passive monitoring is only useful if parents review reports. Real-time alerts ensure parents are immediately notified of concerning events, enabling timely intervention rather than after-the-fact discovery.",
    laws: [],
    fields: [
      { name: "enabled", type: "boolean", required: true, default: "true", constraints: "true or false", description: "Whether monitoring alerts are enabled" },
      { name: "alert_types", type: "string[]", required: false, default: "all", constraints: "Valid: screen_time_exceeded, new_app_installed, blocked_content_attempt, location_change", description: "Types of alerts to send" },
    ],
    exampleConfig: '{\n  "enabled": true,\n  "alert_types": [\n    "screen_time_exceeded",\n    "new_app_installed",\n    "blocked_content_attempt"\n  ]\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "All alert types" },
      { range: "7-9", enabled: true, summary: "All alert types" },
      { range: "10-12", enabled: true, summary: "All alert types" },
      { range: "13-16", enabled: true, summary: "screen_time_exceeded, blocked_content_attempt" },
      { range: "17+", enabled: true, summary: "blocked_content_attempt only" },
    ],
    platforms: [
      { name: "NextDNS", support: "none" },
      { name: "CleanBrowsing", support: "none" },
      { name: "Android", support: "full" },
      { name: "Apple MDM", support: "none" },
      { name: "Microsoft", support: "full" },
    ],
  },
  // ─── Algorithmic Safety (27-28) ───
  {
    id: "algo_feed_control",
    name: "Algorithm Feed Control",
    group: "algorithmic_safety",
    description: "Controls whether platforms serve algorithmic or chronological feeds. In chronological mode, content is shown in time order rather than ranked by engagement algorithms.",
    rationale: "Algorithmic feeds are optimized for engagement, not child wellbeing. They amplify sensational, addictive, and emotionally provocative content. Chronological feeds remove the algorithmic amplification that leads children into harmful content rabbit holes.",
    laws: ["KOSA", "KOSMA", "CA SB 976", "EU DSA"],
    fields: [
      { name: "mode", type: "string", required: true, default: "chronological", constraints: '"chronological" or "algorithmic"', description: "Feed algorithm mode" },
    ],
    exampleConfig: '{\n  "mode": "chronological"\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "Chronological" },
      { range: "7-9", enabled: true, summary: "Chronological" },
      { range: "10-12", enabled: true, summary: "Chronological" },
      { range: "13-16", enabled: true, summary: "Chronological" },
      { range: "17+", enabled: true, summary: "Chronological" },
    ],
    platforms: PLATFORM_NONE,
  },
  {
    id: "addictive_design_control",
    name: "Addictive Design Control",
    group: "algorithmic_safety",
    description: "Disables addictive design patterns including infinite scroll, autoplay, streaks, like counts, and daily rewards. Each pattern can be individually controlled.",
    rationale: "Addictive design patterns exploit psychological vulnerabilities \u2014 variable reward schedules, loss aversion (streaks), social validation (likes), and endless content (infinite scroll). Disabling these patterns reduces compulsive usage and protects developing brains.",
    laws: ["KOSA", "CT SB 3", "EU DSA", "UK OSA"],
    fields: [
      { name: "disable_infinite_scroll", type: "boolean", required: true, default: "true", constraints: "true or false", description: "Disable infinite scroll / endless feed" },
      { name: "disable_autoplay", type: "boolean", required: true, default: "true", constraints: "true or false", description: "Disable auto-playing next video/content" },
      { name: "disable_streaks", type: "boolean", required: true, default: "true", constraints: "true or false", description: "Disable streak counters and rewards" },
      { name: "disable_like_counts", type: "boolean", required: true, default: "true", constraints: "true or false", description: "Hide like/reaction counts" },
      { name: "disable_daily_rewards", type: "boolean", required: true, default: "true", constraints: "true or false", description: "Disable daily login rewards" },
    ],
    exampleConfig: '{\n  "disable_infinite_scroll": true,\n  "disable_autoplay": true,\n  "disable_streaks": true,\n  "disable_like_counts": true,\n  "disable_daily_rewards": true\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "All patterns disabled" },
      { range: "7-9", enabled: true, summary: "All patterns disabled" },
      { range: "10-12", enabled: true, summary: "All patterns disabled" },
      { range: "13-16", enabled: true, summary: "Autoplay + infinite scroll disabled" },
      { range: "17+", enabled: false, summary: "No restrictions" },
    ],
    platforms: PLATFORM_NONE,
  },
  // ─── Notifications (29-30) ───
  {
    id: "notification_curfew",
    name: "Notification Curfew",
    group: "notifications",
    description: "Suppresses all non-essential notifications during defined quiet hours. Emergency and family notifications are always allowed through.",
    rationale: "Notifications are a primary driver of compulsive device checking and sleep disruption. A notification curfew during evening and nighttime hours protects sleep quality and reduces anxiety from constant digital stimulation.",
    laws: ["VA SB 854", "NY SAFE for Kids"],
    fields: [
      { name: "start", type: "string", required: true, default: "age-computed", constraints: "HH:MM format, 24-hour", description: "Curfew start time" },
      { name: "end", type: "string", required: true, default: "age-computed", constraints: "HH:MM format, 24-hour", description: "Curfew end time" },
    ],
    exampleConfig: '{\n  "start": "20:00",\n  "end": "07:00"\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "20:00-07:00" },
      { range: "7-9", enabled: true, summary: "20:00-07:00" },
      { range: "10-12", enabled: true, summary: "20:00-07:00" },
      { range: "13-16", enabled: true, summary: "22:00-06:00" },
      { range: "17+", enabled: true, summary: "00:00-06:00" },
    ],
    platforms: PLATFORM_NONE,
  },
  {
    id: "usage_timer_notification",
    name: "Usage Timer Notification",
    group: "notifications",
    description: "Sends periodic reminders to the child at configurable intervals while they are using their device. Helps build awareness of time spent on screens.",
    rationale: "Children often lose track of time while using devices. Periodic usage reminders build self-regulation skills by making children conscious of how long they've been using screens, encouraging voluntary breaks.",
    laws: ["MN HF 2", "TN HB 1891"],
    fields: [
      { name: "interval_minutes", type: "number", required: true, default: "age-computed", constraints: "Valid values: 15, 30, 45, or 60", description: "Reminder interval in minutes" },
    ],
    exampleConfig: '{\n  "interval_minutes": 30\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "Every 15 minutes" },
      { range: "7-9", enabled: true, summary: "Every 15 minutes" },
      { range: "10-12", enabled: true, summary: "Every 15 minutes" },
      { range: "13-16", enabled: true, summary: "Every 30 minutes" },
      { range: "17+", enabled: true, summary: "Every 60 minutes" },
    ],
    platforms: PLATFORM_NONE,
  },
  // ─── Advertising & Data (31, 34-35) ───
  {
    id: "targeted_ad_block",
    name: "Targeted Ad Block",
    group: "advertising_data",
    description: "Blocks all targeted and behavioral advertising for the child's account. Only contextual (non-personalized) ads are permitted.",
    rationale: "Targeted advertising uses surveillance-based profiling to exploit children's vulnerabilities, interests, and insecurities. Multiple laws now explicitly prohibit behavioral advertising targeting minors.",
    laws: ["COPPA 2.0", "EU DSA", "India DPDPA"],
    fields: [
      { name: "block_targeted_ads", type: "boolean", required: true, default: "true", constraints: "true or false", description: "Whether to block targeted/behavioral ads" },
    ],
    exampleConfig: '{\n  "block_targeted_ads": true\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "Targeted ads blocked" },
      { range: "7-9", enabled: true, summary: "Targeted ads blocked" },
      { range: "10-12", enabled: true, summary: "Targeted ads blocked" },
      { range: "13-16", enabled: true, summary: "Targeted ads blocked" },
      { range: "17+", enabled: true, summary: "Targeted ads blocked" },
    ],
    platforms: PLATFORM_NONE,
  },
  {
    id: "data_deletion_request",
    name: "Data Deletion Request",
    group: "advertising_data",
    description: "Enables one-click data deletion request for child accounts. Platforms must honor deletion requests within 30 days per applicable law.",
    rationale: "Children cannot meaningfully consent to permanent data collection. The right to deletion ensures that data collected during childhood \u2014 browsing history, location data, social interactions \u2014 can be erased when no longer needed or desired.",
    laws: ["COPPA 2.0", "NY NYCDPA"],
    fields: [
      { name: "enabled", type: "boolean", required: true, default: "true", constraints: "true or false", description: "Whether data deletion request capability is enabled" },
    ],
    exampleConfig: '{\n  "enabled": true\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "Enabled" },
      { range: "7-9", enabled: true, summary: "Enabled" },
      { range: "10-12", enabled: true, summary: "Enabled" },
      { range: "13-16", enabled: true, summary: "Enabled" },
      { range: "17+", enabled: true, summary: "Enabled" },
    ],
    platforms: PLATFORM_NONE,
  },
  {
    id: "geolocation_opt_in",
    name: "Geolocation Opt-In",
    group: "advertising_data",
    description: "Defaults geolocation sharing to off and requires explicit opt-in. Prevents apps from silently accessing location data.",
    rationale: "Many apps request and use geolocation data by default, creating detailed movement profiles of children. Defaulting to off and requiring explicit opt-in ensures location access is a conscious, informed decision.",
    laws: ["CT SB 3", "MD Kids Code", "COPPA update"],
    fields: [
      { name: "geolocation_allowed", type: "boolean", required: true, default: "false", constraints: "true or false", description: "Whether geolocation is allowed for third-party apps" },
    ],
    exampleConfig: '{\n  "geolocation_allowed": false\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "Geolocation off" },
      { range: "7-9", enabled: true, summary: "Geolocation off" },
      { range: "10-12", enabled: true, summary: "Geolocation off" },
      { range: "13-16", enabled: true, summary: "Geolocation off" },
      { range: "17+", enabled: true, summary: "Geolocation off" },
    ],
    platforms: PLATFORM_NONE,
  },
  // ─── Access Control (32-33) ───
  {
    id: "dm_restriction",
    name: "DM Restriction",
    group: "access_control",
    description: "Restricts direct messaging capabilities. Can block all DMs, limit to contacts only, or allow everyone.",
    rationale: "Direct messages are the primary vector for predatory contact, cyberbullying, and sextortion. Restricting DMs to known contacts dramatically reduces the attack surface for these harms.",
    laws: ["CT SB 3", "UK OSA"],
    fields: [
      { name: "mode", type: "string", required: true, default: "age-computed", constraints: '"none", "contacts_only", or "everyone"', description: "DM restriction level" },
    ],
    exampleConfig: '{\n  "mode": "contacts_only"\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "No DMs" },
      { range: "7-9", enabled: true, summary: "No DMs" },
      { range: "10-12", enabled: true, summary: "No DMs" },
      { range: "13-16", enabled: true, summary: "Contacts only" },
      { range: "17+", enabled: false, summary: "Everyone" },
    ],
    platforms: PLATFORM_NONE,
  },
  {
    id: "age_gate",
    name: "Age Gate",
    group: "access_control",
    description: "Requires age verification before platform access. Configurable minimum age threshold. Platforms must implement age verification compliant with applicable law.",
    rationale: "Age gates are the first line of defense against underage access to platforms designed for older users. Multiple jurisdictions now mandate robust age verification for platforms serving minors.",
    laws: ["KOSMA", "FL HB 3", "Australia Online Safety Act"],
    fields: [
      { name: "enabled", type: "boolean", required: true, default: "age-computed", constraints: "true or false", description: "Whether age gate is enabled" },
      { name: "min_age", type: "number", required: false, default: "13", constraints: "Range: 0-18", description: "Minimum age required for platform access" },
    ],
    exampleConfig: '{\n  "enabled": true,\n  "min_age": 13\n}',
    ageDefaults: [
      { range: "0-6", enabled: true, summary: "Enabled (min age 13)" },
      { range: "7-9", enabled: true, summary: "Enabled (min age 13)" },
      { range: "10-12", enabled: true, summary: "Enabled (min age 13)" },
      { range: "13-16", enabled: false, summary: "Disabled (meets minimum)" },
      { range: "17+", enabled: false, summary: "Disabled" },
    ],
    platforms: PLATFORM_NONE,
  },
]

export const CATEGORY_GROUPS = [
  { key: "content", label: "Content", description: "Control what media and content children can access across platforms", categories: ["content_rating", "content_block_title", "content_allow_title", "content_allowlist_mode", "content_descriptor_block"] },
  { key: "time", label: "Time", description: "Manage screen time limits, schedules, and downtime periods", categories: ["time_daily_limit", "time_scheduled_hours", "time_per_app_limit", "time_downtime"] },
  { key: "purchase", label: "Purchase", description: "Control digital purchases, spending limits, and in-app transactions", categories: ["purchase_approval", "purchase_spending_cap", "purchase_block_iap"] },
  { key: "social", label: "Social", description: "Manage contacts, chat, and multiplayer interactions", categories: ["social_contacts", "social_chat_control", "social_multiplayer"] },
  { key: "web", label: "Web", description: "Filter web content, enforce safe search, and manage blocklists", categories: ["web_safesearch", "web_category_block", "web_custom_allowlist", "web_custom_blocklist", "web_filter_level"] },
  { key: "privacy", label: "Privacy", description: "Control location sharing, profile visibility, and data sharing", categories: ["privacy_location", "privacy_profile_visibility", "privacy_data_sharing", "privacy_account_creation"] },
  { key: "monitoring", label: "Monitoring", description: "Track activity and configure real-time alerts for parents", categories: ["monitoring_activity", "monitoring_alerts"] },
  { key: "algorithmic_safety", label: "Algorithmic Safety", description: "Control algorithmic feeds and disable addictive design patterns", categories: ["algo_feed_control", "addictive_design_control"] },
  { key: "notifications", label: "Notifications", description: "Manage notification curfews and usage timer reminders", categories: ["notification_curfew", "usage_timer_notification"] },
  { key: "advertising_data", label: "Advertising & Data", description: "Block targeted ads, enable data deletion, and control geolocation", categories: ["targeted_ad_block", "data_deletion_request", "geolocation_opt_in"] },
  { key: "access_control", label: "Access Control", description: "Manage DM restrictions and age verification gates", categories: ["dm_restriction", "age_gate"] },
]
