import { LegislationEntry } from "./types"

export const LEGISLATION_REFERENCE: LegislationEntry[] = [
  {
    id: "kosa",
    law: "KOSA (Kids Online Safety Act)",
    summary: "Federal bill requiring platforms to provide minors with options to protect their information and disable addictive product features. Establishes a duty of care for covered platforms.",
    jurisdiction: "United States (Federal)",
    introduced: "2023 (S. 1409, 118th Congress)",
    stage: "Passed Senate (Jul 2024); pending House action",
    categories: ["algo_feed_control", "addictive_design_control", "targeted_ad_block"],
    keyProvisions: [
      "Duty of care requiring platforms to prevent and mitigate harms to minors",
      "Strongest default privacy settings for minors must be enabled by default",
      "Minors must be able to opt out of algorithmic recommendations",
      "Platforms must disable addictive design features (autoplay, notifications, rewards) by default for minors",
      "FTC enforcement authority with civil penalties up to $50,000 per violation",
      "Annual independent audits of platform compliance required",
    ],
  },
  {
    id: "kosma",
    law: "KOSMA (Kids Online Safety & Media Act)",
    summary: "Combined package merging KOSA with COPPA 2.0 updates. Expands COPPA protections to teens (13-16) and strengthens age verification requirements for platforms serving minors.",
    jurisdiction: "United States (Federal)",
    introduced: "2024 (S. 1409 + S. 1418, 118th Congress)",
    stage: "Passed Senate (Jul 2024); pending House action",
    categories: ["algo_feed_control", "age_gate"],
    keyProvisions: [
      "Extends COPPA protections from under-13 to all minors under 17",
      "Requires platforms to obtain verifiable parental consent for data collection on minors",
      "Mandates age verification mechanisms on platforms likely to be used by children",
      "Prohibits targeted advertising to minors under 17",
      "Creates an Eraser Button — right for minors to delete personal data",
      "Establishes Kids Online Safety Council within the FTC",
    ],
  },
  {
    id: "ca-sb-976",
    law: "CA SB 976",
    summary: "California law restricting addictive social media features for minors. Bans algorithmic feeds and addictive design patterns for users known to be under 18 without parental consent.",
    jurisdiction: "California, United States",
    introduced: "2024 (SB 976, California Legislature)",
    stage: "Signed into law (Sep 2024); effective Jan 2027",
    categories: ["algo_feed_control", "addictive_design_control"],
    keyProvisions: [
      "Prohibits platforms from providing addictive feeds to minors without parental consent",
      "Bans sending notifications to minors during school hours (7am-3pm) and overnight (9pm-6am)",
      "Requires platforms to default minors to chronological feeds instead of algorithmic recommendations",
      "Restricts autoplay, infinite scroll, and engagement-maximizing features for minor accounts",
      "California AG enforcement with penalties up to $2,500 per affected minor per violation",
    ],
  },
  {
    id: "eu-dsa",
    law: "EU Digital Services Act",
    summary: "Comprehensive EU regulation governing digital platforms with specific protections for minors. Bans targeted advertising to minors and requires platforms to assess systemic risks to children.",
    jurisdiction: "European Union (27 member states)",
    introduced: "2022 (Regulation (EU) 2022/2065)",
    stage: "In force (Feb 2024); full enforcement active",
    categories: ["algo_feed_control", "addictive_design_control", "targeted_ad_block"],
    keyProvisions: [
      "Complete ban on targeted advertising based on profiling of minors",
      "Very large online platforms (VLOPs) must assess and mitigate systemic risks to minors",
      "Platforms must provide clear, age-appropriate terms of service for minors",
      "Recommender systems must offer at least one option not based on profiling",
      "Mandatory transparency reporting on content moderation and algorithmic systems",
      "Fines up to 6% of global annual turnover for non-compliance",
    ],
  },
  {
    id: "uk-osa",
    law: "UK Online Safety Act",
    summary: "UK law imposing a duty of care on platforms to protect children from harmful content online. Requires age verification and proactive measures to prevent children encountering harmful material.",
    jurisdiction: "United Kingdom",
    introduced: "2023 (UK Parliament)",
    stage: "Enacted (Oct 2023); Ofcom codes of practice in phased rollout",
    categories: ["addictive_design_control", "dm_restriction"],
    keyProvisions: [
      "Duty of care requiring platforms to protect children from harmful content",
      "Mandatory age verification or age estimation for platforms likely accessed by children",
      "Platforms must prevent children from encountering priority harmful content (self-harm, eating disorders, pornography)",
      "Restrictions on direct messaging between adults and children they don't know",
      "Ofcom as regulator with power to fine up to 10% of global revenue or £18 million",
      "Criminal liability for senior managers who fail to comply with information requests",
    ],
  },
  {
    id: "coppa-2",
    law: "COPPA 2.0",
    summary: "Update to the Children's Online Privacy Protection Act extending protections to teenagers (13-16), banning targeted advertising to all minors, and creating a data deletion right.",
    jurisdiction: "United States (Federal)",
    introduced: "2024 (S. 1418, 118th Congress)",
    stage: "Passed Senate as part of KOSMA (Jul 2024); pending House action",
    categories: ["targeted_ad_block", "data_deletion_request", "geolocation_opt_in"],
    keyProvisions: [
      "Extends COPPA from children under 13 to all minors under 17",
      "Complete ban on targeted advertising directed at minors",
      "Creates Eraser Button — minors and parents can request deletion of all personal data",
      "Prohibits conditioning service access on a minor providing more data than necessary",
      "Establishes Youth Privacy and Marketing Division within the FTC",
      "Increased penalties: up to $50,000 per violation (up from $46,517)",
    ],
  },
  {
    id: "ct-sb-3",
    law: "CT SB 3",
    summary: "Connecticut law protecting minors from addictive platform features and restricting unsolicited contact. Requires platforms to default to safest settings for accounts identified as minors.",
    jurisdiction: "Connecticut, United States",
    introduced: "2023 (SB 3, Connecticut General Assembly)",
    stage: "Signed into law (Jun 2023); effective Oct 2024",
    categories: ["addictive_design_control", "dm_restriction", "geolocation_opt_in"],
    keyProvisions: [
      "Platforms must default to highest privacy and safety settings for minor accounts",
      "Prohibits sending unsolicited communications (DMs) from adults to unconnected minors",
      "Restricts addictive features: autoplay, infinite scroll, notifications designed to increase engagement",
      "Geolocation data collection from minors prohibited without explicit informed consent",
      "Platforms must provide parents with tools to supervise minor accounts",
      "Connecticut AG enforcement authority; penalties under CUTPA (unfair trade practices)",
    ],
  },
  {
    id: "va-sb-854",
    law: "VA SB 854",
    summary: "Virginia law requiring social media platforms to implement notification restrictions and usage limits for minor accounts, including quiet hours during nighttime.",
    jurisdiction: "Virginia, United States",
    introduced: "2024 (SB 854, Virginia General Assembly)",
    stage: "Signed into law (Apr 2024); effective Jul 2025",
    categories: ["notification_curfew"],
    keyProvisions: [
      "Platforms must suppress non-essential notifications to minors during nighttime hours",
      "Requires platforms to implement configurable screen time limits for minor accounts",
      "Parents must be provided tools to set notification schedules",
      "Platforms must provide activity reports to parents on request",
      "Virginia AG enforcement with civil penalties",
    ],
  },
  {
    id: "ny-safe",
    law: "NY SAFE for Kids Act",
    summary: "New York law restricting addictive algorithmic feeds for minors and requiring notification-free periods. Bans algorithmic recommendations without parental consent.",
    jurisdiction: "New York, United States",
    introduced: "2024 (S. 7694 / A. 8148, New York Legislature)",
    stage: "Signed into law (Jun 2024); effective 2025",
    categories: ["notification_curfew"],
    keyProvisions: [
      "Prohibits addictive algorithmic feeds for minors without verifiable parental consent",
      "Mandates notification-free quiet hours for minor accounts (default overnight)",
      "Platforms must verify age of users before serving algorithmic content",
      "Restricts platforms from sending push notifications to minors during nighttime hours",
      "New York AG enforcement authority",
    ],
  },
  {
    id: "mn-hf-2",
    law: "MN HF 2",
    summary: "Minnesota bill requiring platforms to implement usage awareness tools for minor users, including periodic screen time reminders and usage dashboards.",
    jurisdiction: "Minnesota, United States",
    introduced: "2024 (HF 2, Minnesota Legislature)",
    stage: "Introduced; committee review",
    categories: ["usage_timer_notification"],
    keyProvisions: [
      "Platforms must provide periodic usage time reminders at intervals no greater than 60 minutes",
      "Requires platforms to offer a usage dashboard visible to both the minor and their parent",
      "Platforms must allow parents to configure reminder intervals",
      "Usage data must be presented in age-appropriate format for the minor",
    ],
  },
  {
    id: "tn-hb-1891",
    law: "TN HB 1891",
    summary: "Tennessee law requiring social media platforms to implement screen time awareness features for minor users, including configurable usage timer notifications.",
    jurisdiction: "Tennessee, United States",
    introduced: "2024 (HB 1891, Tennessee General Assembly)",
    stage: "Signed into law (May 2024); effective Jan 2025",
    categories: ["usage_timer_notification"],
    keyProvisions: [
      "Platforms must notify minor users of cumulative usage time at regular intervals",
      "Default usage reminder interval of 30 minutes; configurable by parent or minor",
      "Platforms must provide parents with weekly screen time reports",
      "Parental consent required for minors under 13 to create accounts",
      "Tennessee AG enforcement with civil penalties up to $10,000 per violation",
    ],
  },
  {
    id: "fl-hb-3",
    law: "FL HB 3",
    summary: "Florida law requiring age verification for social media platforms and prohibiting minors under 14 from holding accounts. Minors 14-15 need parental consent.",
    jurisdiction: "Florida, United States",
    introduced: "2024 (HB 3, Florida Legislature)",
    stage: "Signed into law (Mar 2024); enforcement paused (federal court injunction)",
    categories: ["age_gate"],
    keyProvisions: [
      "Prohibits social media accounts for children under 14",
      "Minors aged 14-15 require verifiable parental consent to create accounts",
      "Platforms must implement age verification using government-issued ID or equivalent",
      "Existing accounts for minors under 14 must be terminated within prescribed period",
      "Platforms must delete all personal information of terminated minor accounts",
      "Private right of action for parents; statutory damages of $10,000 per violation",
    ],
  },
  {
    id: "au-osa",
    law: "Australia Online Safety Act",
    summary: "Australian law establishing the eSafety Commissioner with broad powers to enforce online safety, including age verification requirements and content removal powers for material harmful to children.",
    jurisdiction: "Australia",
    introduced: "2021 (Online Safety Act 2021, Australian Parliament)",
    stage: "In force; age verification trial underway (2024-2025)",
    categories: ["age_gate"],
    keyProvisions: [
      "Establishes eSafety Commissioner as independent regulator",
      "Mandatory age verification for platforms hosting age-restricted content",
      "Powers to issue removal notices for cyber-abuse material targeting children",
      "Basic Online Safety Expectations (BOSE) that platforms must report against",
      "Industry codes of practice for platform categories (social media, messaging, gaming, etc.)",
      "Civil penalties up to AUD $555,000 per day for non-compliance",
    ],
  },
  {
    id: "india-dpdpa",
    law: "India DPDPA",
    summary: "India's Digital Personal Data Protection Act establishing comprehensive data protection rules with specific provisions prohibiting behavioral advertising targeting children and requiring verifiable parental consent.",
    jurisdiction: "India",
    introduced: "2023 (Digital Personal Data Protection Act, Indian Parliament)",
    stage: "Enacted (Aug 2023); rules being finalized",
    categories: ["targeted_ad_block"],
    keyProvisions: [
      "Complete ban on behavioral monitoring and targeted advertising directed at children",
      "Verifiable parental consent required before processing any child's data",
      "Prohibits processing of children's data that could cause detrimental effect",
      "Data fiduciaries must not undertake tracking or profiling of children",
      "Penalties up to INR 250 crore (approx. $30 million) for violations",
    ],
  },
  {
    id: "ny-nycdpa",
    law: "NY NYCDPA",
    summary: "New York Child Data Protection Act focusing on commercial data collection from minors, with strong data minimization and deletion rights for child accounts.",
    jurisdiction: "New York, United States",
    introduced: "2024 (New York Legislature)",
    stage: "Introduced; committee review",
    categories: ["data_deletion_request"],
    keyProvisions: [
      "Platforms must provide a clear, accessible mechanism for parents to request deletion of a minor's data",
      "Data deletion requests must be honored within 30 days",
      "Prohibits selling or sharing personal data of minors for commercial purposes",
      "Data minimization requirement — platforms may only collect data necessary for the service",
      "New York AG enforcement authority with enhanced penalties for violations involving minors",
    ],
  },
  {
    id: "md-kids-code",
    law: "MD Kids Code",
    summary: "Maryland Age-Appropriate Design Code requiring platforms to default to maximum privacy settings for minors, including geolocation disabled by default and data protection impact assessments.",
    jurisdiction: "Maryland, United States",
    introduced: "2024 (Maryland Kids Code, Maryland General Assembly)",
    stage: "Signed into law (May 2024); effective Oct 2025",
    categories: ["geolocation_opt_in"],
    keyProvisions: [
      "Geolocation and precise location services must be disabled by default for minors",
      "Platforms must complete a Data Protection Impact Assessment (DPIA) for features used by minors",
      "Highest privacy settings must be the default for accounts identified as belonging to minors",
      "Prohibits using geolocation data to serve targeted content or advertising to minors",
      "Platforms must provide clear, child-friendly explanations of how location data is used",
      "Maryland AG enforcement; penalties under Maryland Consumer Protection Act",
    ],
  },
]
