package com.phosra.sdk.enforcement

import android.app.NotificationManager
import android.content.Context
import android.os.Build
import android.provider.Settings
import com.phosra.sdk.models.PhosraNotifications
import java.util.Calendar

/**
 * Enforces notification restrictions including curfew hours and usage timer notifications.
 *
 * Strategy:
 * - Uses NotificationListenerService to intercept and suppress notifications during curfew
 * - Schedules usage timer notifications via AlarmManager
 * - Activates Do Not Disturb mode during curfew hours (if DND access is granted)
 *
 * Required permissions:
 * - BIND_NOTIFICATION_LISTENER_SERVICE (Settings > Notification Access)
 * - ACCESS_NOTIFICATION_POLICY (for DND mode, optional)
 *
 * TODO: Requires NotificationListenerService implementation to actively filter
 *       notifications. Currently implements curfew detection and DND scheduling.
 */
class NotificationEnforcer(private val context: Context) {

    private var currentConfig: PhosraNotifications? = null

    /**
     * Apply notification rules from the compiled policy.
     *
     * @param notifications The notification configuration.
     * @return A [CategoryReport] describing the enforcement result.
     */
    fun apply(notifications: PhosraNotifications): CategoryReport {
        currentConfig = notifications

        val hasCurfew = notifications.curfewStart.isNotBlank() && notifications.curfewEnd.isNotBlank()
        val hasUsageTimer = notifications.usageTimerMinutes > 0

        if (!hasCurfew && !hasUsageTimer) {
            return CategoryReport(
                status = EnforcementStatus.ENFORCED,
                framework = "NotificationListenerService",
                details = "No notification rules configured"
            )
        }

        val hasNotificationAccess = hasNotificationListenerPermission()
        val enforced = mutableListOf<String>()
        val partial = mutableListOf<String>()

        // Notification curfew
        if (hasCurfew) {
            if (hasNotificationAccess) {
                // TODO: Schedule NotificationListenerService to suppress notifications
                //       during curfew hours. The service's onNotificationPosted() callback
                //       checks the current time against curfew window and calls
                //       cancelNotification() for blocked notifications.
                //
                //       Additionally, consider using DND mode via NotificationManager:
                //       val nm = context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
                //       if (nm.isNotificationPolicyAccessGranted) {
                //           nm.setInterruptionFilter(NotificationManager.INTERRUPTION_FILTER_PRIORITY)
                //       }
                enforced.add("Curfew ${notifications.curfewStart}-${notifications.curfewEnd}")
            } else {
                partial.add("Curfew (notification listener access not granted)")
            }
        }

        // Usage timer notifications
        if (hasUsageTimer) {
            // Usage timer notifications are self-generated by the SDK,
            // not filtered from other apps. This always works.
            // TODO: Schedule periodic notifications via AlarmManager that remind
            //       the child they've been using the device for X minutes.
            enforced.add("Usage timer every ${notifications.usageTimerMinutes}min")
        }

        val status = when {
            partial.isEmpty() && enforced.isNotEmpty() -> EnforcementStatus.ENFORCED
            enforced.isNotEmpty() -> EnforcementStatus.PARTIAL
            else -> EnforcementStatus.FAILED
        }

        val details = buildString {
            if (enforced.isNotEmpty()) append("Active: ${enforced.joinToString(", ")}. ")
            if (partial.isNotEmpty()) append("Needs permission: ${partial.joinToString(", ")}.")
        }

        return CategoryReport(
            status = status,
            framework = "NotificationListenerService",
            details = details.trim()
        )
    }

    /**
     * Remove all notification restrictions.
     */
    fun remove() {
        // TODO: Cancel scheduled alarms and restore normal notification behavior
        //       If DND was activated by us, deactivate it.
        currentConfig = null
    }

    /**
     * Get the current enforcement status.
     */
    fun currentStatus(): CategoryReport {
        return if (currentConfig != null) {
            val inCurfew = isInCurfew()
            CategoryReport(
                status = EnforcementStatus.ENFORCED,
                framework = "NotificationListenerService",
                details = if (inCurfew) "Currently in notification curfew" else "Notification rules active"
            )
        } else {
            CategoryReport(
                status = EnforcementStatus.PENDING,
                framework = "NotificationListenerService",
                details = "No notification rules configured"
            )
        }
    }

    /**
     * Check if the device is currently in a notification curfew period.
     */
    fun isInCurfew(): Boolean {
        val config = currentConfig ?: return false
        if (config.curfewStart.isBlank() || config.curfewEnd.isBlank()) return false

        val now = Calendar.getInstance()
        val currentTime = String.format(
            "%02d:%02d",
            now.get(Calendar.HOUR_OF_DAY),
            now.get(Calendar.MINUTE)
        )

        // Handle overnight curfew (e.g., 21:00 - 07:00)
        return if (config.curfewStart > config.curfewEnd) {
            currentTime >= config.curfewStart || currentTime < config.curfewEnd
        } else {
            currentTime >= config.curfewStart && currentTime < config.curfewEnd
        }
    }

    private fun hasNotificationListenerPermission(): Boolean {
        val enabledListeners = Settings.Secure.getString(
            context.contentResolver,
            "enabled_notification_listeners"
        ) ?: return false
        return enabledListeners.contains(context.packageName)
    }
}
