export interface LegalSection {
  id: string
  title: string
  content: string
}

// ---------------------------------------------------------------------------
// Privacy Policy
// ---------------------------------------------------------------------------

export const PRIVACY_SECTIONS: LegalSection[] = [
  {
    id: "introduction",
    title: "Introduction",
    content:
      "Phosra, Inc. (\"Phosra,\" \"we,\" \"us,\" or \"our\") is a universal parental controls platform that enables parent-facing applications to define child safety policies once and enforce them across 188+ digital platforms. This Privacy Policy describes how we collect, use, disclose, and protect information when you access or use phosra.com, the Phosra API, the Phosra dashboard, and any related services (collectively, the \"Service\").\n\nIn this Privacy Policy, \"you\" or \"your\" refers to any individual or entity that accesses or uses the Service, including parents, guardians, developers, and enterprise customers. \"Child data\" refers to information about children that is submitted to the Service by authorized parents, guardians, or applications acting on their behalf.\n\nBy accessing or using the Service, you acknowledge that you have read, understood, and agree to the practices described in this Privacy Policy. If you do not agree, please discontinue use of the Service immediately. We encourage you to review this policy periodically, as it may be updated to reflect changes in our practices or applicable law.",
  },
  {
    id: "information-collected",
    title: "Information We Collect",
    content:
      "We collect several categories of information in order to provide and improve the Service. The types and extent of data we collect depend on your use of the platform and the features you enable.\n\nAccount Information: When you register for a Phosra account, we collect your name, email address, and authentication credentials. Passwords are managed and hashed through our authentication provider, Clerk, using industry-standard bcrypt hashing. We do not store plaintext passwords at any point in our infrastructure.\n\nChild Profile Data: Parents and guardians may create child profiles within the Service. Child profile data includes the child's first name, date of birth, and computed age group. This information is provided exclusively by the parent or guardian and is never collected directly from children. We apply strict data minimization principles and collect only the information necessary to match policies to age-appropriate rules.\n\nPolicy and Rule Data: The Service stores policy configurations, rule category selections (such as content rating filters, screen time limits, web filtering preferences, and notification curfews), enforcement preferences, and platform connection settings. This data defines how child safety rules are pushed to connected platforms.\n\nUsage Data: We automatically collect certain technical information when you interact with the Service, including API call logs, request timestamps, IP addresses, browser type and version, device information, and referring URLs. This data is used for analytics, rate limiting, security monitoring, and service optimization.\n\nPlatform Credentials: When you connect third-party platforms (such as Netflix, YouTube, or device management services), the Service stores the necessary API keys or OAuth tokens required to enforce policies on those platforms. All platform credentials are encrypted at rest using AES-256-GCM encryption and are never exposed in logs, API responses, or error messages.",
  },
  {
    id: "how-we-use",
    title: "How We Use Your Information",
    content:
      "We use the information we collect for the following purposes, all of which are directed toward providing you with a reliable, secure, and effective parental controls platform.\n\nService Provision and Policy Enforcement: Your account information, child profiles, and policy configurations are used to operate the core Service, including pushing policy rules to connected platforms, verifying enforcement status, and synchronizing rule changes across your connected ecosystem. When you trigger an enforcement action, we transmit only the minimum rule data necessary to the relevant platform adapters.\n\nCompliance Verification and Audit: We use enforcement logs, job records, and policy snapshots to verify that rules have been successfully applied to each connected platform. These records also support audit trails required by child safety regulations such as COPPA, KOSA, and the EU Digital Services Act.\n\nAPI Analytics and Performance: Usage data, including API call volumes, response times, and error rates, is analyzed to monitor Service health, optimize infrastructure, enforce rate limits, and plan capacity. Aggregated and anonymized analytics may be used to improve the Service and inform product decisions.\n\nSecurity and Fraud Prevention: We use IP addresses, authentication logs, device fingerprints, and behavioral signals to detect unauthorized access attempts, prevent credential abuse, identify suspicious API usage patterns, and protect the integrity of child data. Automated systems may temporarily restrict access when anomalous activity is detected.\n\nCommunication: We may use your email address to send transactional messages related to your account (such as verification emails, enforcement status alerts, and security notifications) and, with your consent, to send product updates, feature announcements, and educational content about child safety regulations. You may opt out of non-transactional communications at any time.",
  },
  {
    id: "childrens-data",
    title: "Children's Data",
    content:
      "The protection of children's data is central to Phosra's mission and architecture. This section describes how we handle information about children and the safeguards we have implemented to ensure that child data is treated with the highest level of care.\n\nPhosra acts as a data processor on behalf of parents and guardians, who serve as the data controllers for their children's information. We do not collect data directly from children at any point. All child profile data, including names, dates of birth, and age groups, is submitted exclusively by authorized parents, guardians, or applications that have obtained appropriate parental consent.\n\nWe apply strict data minimization principles to child data. The only personal information we store for a child profile is the child's first name, date of birth, and computed age group. We do not collect, store, or process children's email addresses, phone numbers, physical addresses, photographs, biometric data, or social media identifiers. Age group data is used solely to match children with age-appropriate policy rules across content rating systems (MPAA, TV Parental Guidelines, ESRB, PEGI, and Common Sense Media).\n\nAll child data is encrypted at rest using AES-256-GCM encryption. When policy rules are transmitted to third-party platforms for enforcement, we send only the abstract rule categories (such as content rating thresholds or screen time limits) and never transmit children's names, dates of birth, or any other personal information to platform providers.\n\nParents and guardians retain full control over their children's data at all times. Child profiles can be deleted at any time through the Phosra dashboard or via the API. Upon deletion, all associated data, including the profile record, linked policy rules, and enforcement history, is permanently removed from our systems within seven days. We comply with the Children's Online Privacy Protection Act (COPPA), the Kids Online Safety Act (KOSA), and equivalent international regulations governing children's data, including the EU General Data Protection Regulation (GDPR) as it applies to minors and the UK Age Appropriate Design Code.",
  },
  {
    id: "legal-basis",
    title: "Legal Basis for Processing",
    content:
      "For users in the European Economic Area (EEA), United Kingdom, and other jurisdictions that require a legal basis for processing personal data, we rely on the following grounds under the General Data Protection Regulation (GDPR) and equivalent frameworks.\n\nContractual Necessity (Article 6(1)(b) GDPR): Processing of your account information, child profile data, and policy configurations is necessary to perform the contract between you and Phosra, specifically to provide the Service, enforce policies across connected platforms, and maintain your account. Without this processing, we cannot deliver the core functionality of the platform.\n\nLegitimate Interest (Article 6(1)(f) GDPR): We process certain data, such as IP addresses, API usage logs, and device information, based on our legitimate interest in maintaining the security and integrity of the Service, preventing fraud and abuse, and improving platform performance. We have conducted balancing tests to ensure these interests do not override your fundamental rights, particularly with respect to children's data.\n\nConsent (Article 6(1)(a) GDPR): Where we send marketing communications, product newsletters, or non-essential communications, we do so based on your explicit opt-in consent. You may withdraw consent at any time by clicking the unsubscribe link in any marketing email or by updating your preferences in the dashboard Settings page. Withdrawal of consent does not affect the lawfulness of processing performed before withdrawal.\n\nLegal Obligation (Article 6(1)(c) GDPR): Certain processing activities are required to comply with applicable laws and regulations, including child safety laws (COPPA, KOSA), data protection regulations, tax and accounting requirements, and lawful requests from regulatory authorities or law enforcement. We retain enforcement audit logs and certain account records as required by these obligations.",
  },
  {
    id: "information-sharing",
    title: "Information Sharing",
    content:
      "Phosra does not sell, rent, or trade your personal data or children's data to any third party for any purpose. We share information only in the limited circumstances described below, and we impose contractual and technical safeguards on all data recipients.\n\nPlatform Providers: When you connect a third-party platform (such as Netflix, YouTube, TikTok, or a device management service) and trigger policy enforcement, we transmit the minimum set of abstract policy rules required for that platform to apply the requested restrictions. We never share children's names, dates of birth, personal identifiers, or any information beyond the specific rule parameters needed for enforcement. Each platform adapter is designed to operate on a least-privilege basis.\n\nInfrastructure Providers: We use third-party service providers for hosting, database management, email delivery, and monitoring. These providers process data on our behalf under strict data processing agreements and are prohibited from using your data for their own purposes. We select providers that maintain SOC 2 compliance or equivalent security certifications.\n\nLaw Enforcement and Legal Requirements: We may disclose information if we believe in good faith that disclosure is required by applicable law, regulation, legal process, or governmental request. We will attempt to notify affected users of such requests unless we are legally prohibited from doing so or the request relates to an emergency involving potential harm to a child.\n\nBusiness Transfers: In the event of a merger, acquisition, reorganization, or sale of assets, your information may be transferred as part of the transaction. We will provide at least 30 days' notice before any such transfer and will ensure that the acquiring entity is bound by privacy protections at least as protective as those described in this Privacy Policy.\n\nWe want to be unequivocal on two points: We never sell personal data to any party, and we never share children's data with advertisers, data brokers, or any entity for marketing or commercial profiling purposes.",
  },
  {
    id: "data-retention",
    title: "Data Retention",
    content:
      "We retain your information only for as long as necessary to fulfill the purposes described in this Privacy Policy, comply with our legal obligations, and resolve disputes. The specific retention periods vary by data category.\n\nAccount Data: Your account information (name, email, authentication records) is retained for the duration of your active account plus 30 days following account deletion. This 30-day post-deletion period allows for account recovery in case of accidental deletion and ensures we can fulfill any outstanding legal or contractual obligations.\n\nChild Profile Data: When a child profile is deleted by a parent or guardian, all associated data, including the profile record, linked policy rules, enforcement preferences, and enforcement history for that profile, is permanently deleted from our systems within 7 days. This accelerated deletion timeline reflects our commitment to minimizing the retention of children's data.\n\nAPI and Usage Logs: API call logs, request metadata, and usage analytics are retained for 90 days from the date of the request. After this period, logs are permanently deleted. Aggregated, anonymized statistics derived from usage data may be retained indefinitely for capacity planning and service improvement.\n\nEnforcement Job Records: Records of enforcement actions (including job status, timestamps, platform responses, and error logs) are retained for 1 year to support compliance audits, dispute resolution, and regulatory reporting requirements under child safety laws.\n\nPlatform Credentials: Encrypted platform API keys and OAuth tokens are deleted immediately upon disconnection of the associated platform from your account. No cached or backup copies are retained after disconnection.",
  },
  {
    id: "your-rights",
    title: "Your Rights",
    content:
      "Depending on your jurisdiction, you may have certain rights regarding your personal data. We are committed to honoring these rights and have implemented mechanisms to facilitate their exercise.\n\nUnder the EU General Data Protection Regulation (GDPR), residents of the EEA and UK have the following rights: the right of access to obtain a copy of the personal data we hold about you; the right to rectification to correct inaccurate or incomplete data; the right to erasure (\"right to be forgotten\") to request deletion of your data; the right to restriction of processing in certain circumstances; the right to data portability to receive your data in a structured, machine-readable format; and the right to object to processing based on legitimate interests, including profiling.\n\nUnder the California Consumer Privacy Act (CCPA) and California Privacy Rights Act (CPRA), California residents have the following rights: the right to know what personal information we collect, use, disclose, and sell; the right to delete personal information we hold about you; the right to opt out of the sale of personal information (Phosra does not sell personal data, so this right is already satisfied); and the right to non-discrimination for exercising your privacy rights.\n\nYou may exercise any of these rights through the Settings page in your Phosra dashboard, which provides self-service tools for data access, export, and deletion. Alternatively, you may submit a request by contacting us at privacy@phosra.com. We will verify your identity before processing any request and will respond within 30 days of receipt. If we require additional time, we will notify you of the extension and the reasons for it. There is no fee for exercising your rights, except in cases of manifestly unfounded or excessive requests, where we may charge a reasonable administrative fee or decline the request.",
  },
  {
    id: "cookies",
    title: "Cookies & Tracking",
    content:
      "Phosra is committed to a privacy-first approach to cookies and tracking technologies. We use only the minimum cookies necessary to operate the Service and do not employ any advertising, retargeting, or behavioral tracking cookies.\n\nEssential Cookies: We use essential cookies to maintain your authenticated session, managed through our authentication provider Clerk. These cookies are strictly necessary for the Service to function and cannot be disabled without losing access to authenticated features such as the dashboard and API management pages. Essential cookies are first-party only and are not shared with any third party.\n\nAnalytics: Where we use analytics tools, we select privacy-respecting providers that do not use cross-site tracking, do not build user profiles, and do not share data with advertising networks. Analytics data is aggregated and anonymized before storage and is used solely to understand Service usage patterns and improve the user experience.\n\nNo Third-Party Tracking: We do not embed third-party tracking pixels, social media widgets that transmit data, or any advertising network scripts on phosra.com or within the Phosra dashboard. Your browsing activity on our platform is not shared with any external party for advertising, profiling, or remarketing purposes.\n\nManaging Cookies: You can control and delete cookies through your browser settings. Disabling essential cookies may prevent you from accessing authenticated areas of the Service. Because we do not use non-essential cookies, there is no cookie consent banner to manage beyond acknowledging this policy.",
  },
  {
    id: "security",
    title: "Security",
    content:
      "Phosra implements comprehensive technical and organizational security measures to protect your data and your children's data against unauthorized access, alteration, disclosure, or destruction.\n\nEncryption at Rest: All sensitive data, including child profile information, platform credentials, and provider API keys, is encrypted at rest using AES-256-GCM (Advanced Encryption Standard with 256-bit keys in Galois/Counter Mode). Encryption keys are managed through a dedicated key management system with regular key rotation.\n\nEncryption in Transit: All data transmitted between your browser or application and our servers is protected by TLS 1.3 (Transport Layer Security). We enforce HTTPS across all endpoints and apply HTTP Strict Transport Security (HSTS) headers to prevent protocol downgrade attacks.\n\nAuthentication Security: User passwords are managed by Clerk, our authentication provider, which employs bcrypt hashing with appropriate cost factors. API authentication uses JSON Web Tokens (JWT) with 15-minute expiry windows and cryptographic refresh token rotation. Refresh tokens are hashed using SHA-256 before storage, ensuring that even a database compromise would not expose valid session credentials.\n\nCredential Vault: Third-party platform credentials (API keys, OAuth tokens) are stored in an encrypted vault with application-level access controls. Credentials are decrypted only at the moment of use during enforcement operations and are never logged, cached in memory beyond the operation lifecycle, or included in error reports.\n\nOperational Security: We conduct regular security audits and penetration testing of our infrastructure and application layer. Our development process includes automated dependency vulnerability scanning, static code analysis, and mandatory code review for all changes to authentication, encryption, and data access components. We maintain an incident response plan and will notify affected users promptly in the event of a data breach.",
  },
  {
    id: "international-transfers",
    title: "International Transfers",
    content:
      "Phosra's primary data processing infrastructure is located in the United States. If you access the Service from outside the United States, your data will be transferred to and processed in the United States, which may have data protection laws that differ from those in your jurisdiction.\n\nFor users located in the European Economic Area (EEA), United Kingdom, or Switzerland, we ensure that international data transfers are conducted in compliance with Chapter V of the GDPR. Transfers to our infrastructure providers and sub-processors in the United States are protected by the European Commission's Standard Contractual Clauses (SCCs), supplemented by additional technical measures including encryption in transit and at rest.\n\nWe continuously monitor developments in international data transfer frameworks, including the EU-U.S. Data Privacy Framework and successor arrangements, and will adopt appropriate transfer mechanisms as they become available. Where a sub-processor is located in a jurisdiction that has received an adequacy decision from the European Commission, we rely on that adequacy decision as the basis for transfer.\n\nIf you have questions about international data transfers or wish to obtain a copy of the applicable Standard Contractual Clauses, please contact our Data Protection Officer at dpo@phosra.com.",
  },
  {
    id: "changes",
    title: "Changes to This Policy",
    content:
      "We may update this Privacy Policy from time to time to reflect changes in our data practices, the introduction of new features, or developments in applicable privacy laws and regulations.\n\nFor material changes that affect how we collect, use, or share your personal data or children's data, we will provide at least 30 days' advance notice before the changes take effect. Notice will be delivered via email to the address associated with your account and through a prominent notification in the Phosra dashboard. Material changes include, but are not limited to, new categories of data collection, new third-party data sharing arrangements, changes to data retention periods for children's data, and changes to your rights or how to exercise them.\n\nYour continued use of the Service after the effective date of an updated Privacy Policy constitutes your acceptance of the revised terms. If you do not agree with the changes, you should discontinue use of the Service and delete your account before the effective date. Previous versions of this Privacy Policy are available upon request by contacting privacy@phosra.com.",
  },
  {
    id: "contact",
    title: "Contact Us",
    content:
      "If you have questions, concerns, or requests regarding this Privacy Policy or our data practices, we encourage you to reach out through the following channels.\n\nPrivacy Inquiries: For general privacy questions, data access requests, or concerns about how your information is handled, please contact us at privacy@phosra.com. Our privacy team aims to acknowledge all inquiries within two business days and to provide a substantive response within 30 days.\n\nData Protection Officer: For matters relating to GDPR compliance, international data transfers, data protection impact assessments, or to exercise your rights under European data protection law, please contact our Data Protection Officer at dpo@phosra.com.\n\nMailing Address: Phosra, Inc., Wilmington, Delaware, United States.\n\nEU Representative: For users in the European Economic Area who wish to contact a representative within the EU regarding data protection matters, our EU representative details will be published on this page upon appointment.\n\nSupervisory Authority: If you are located in the EEA or UK and believe that our processing of your personal data violates applicable data protection law, you have the right to lodge a complaint with your local data protection supervisory authority. We would, however, appreciate the opportunity to address your concerns before you approach the supervisory authority, and we invite you to contact us first.",
  },
]

// ---------------------------------------------------------------------------
// Terms of Service
// ---------------------------------------------------------------------------

export const TERMS_SECTIONS: LegalSection[] = [
  {
    id: "acceptance",
    title: "Acceptance of Terms",
    content:
      "By accessing, browsing, or using any part of the Phosra platform, including phosra.com, the Phosra API, the Phosra dashboard, developer documentation, and any related services (collectively, the \"Service\"), you acknowledge that you have read, understood, and agree to be bound by these Terms of Service (\"Terms\"). These Terms constitute a legally binding agreement between you and Phosra, Inc., a Delaware corporation (\"Phosra,\" \"we,\" \"us,\" or \"our\").\n\nIf you are using the Service on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these Terms, and \"you\" shall refer to both you individually and the organization. If you do not agree to any part of these Terms, you must immediately discontinue all use of the Service.\n\nThese Terms are effective as of the date you first access or use the Service and remain in effect until terminated in accordance with the Termination section below. We reserve the right to update these Terms as described in the General Provisions section, and your continued use following any such update constitutes acceptance of the revised Terms.",
  },
  {
    id: "definitions",
    title: "Definitions",
    content:
      "The following definitions apply throughout these Terms and are provided to ensure clarity regarding the specific concepts and components of the Phosra platform.\n\n\"API\" means the Phosra REST API, including all endpoints, request and response formats, authentication mechanisms, and associated technical interfaces through which you interact with the Service programmatically. \"PCSS\" means the Phosra Child Safety Standard, our proprietary specification that defines the universal rule categories, age-to-rating mappings, and enforcement protocols used across the platform. \"Platform\" means any third-party digital service, application, or device where Phosra enforces policy rules on behalf of users, including but not limited to Netflix, YouTube, TikTok, Instagram, Roblox, and device management systems.\n\n\"Policy\" means a collection of rules and configurations that define how a child's online experience should be governed across one or more platforms, including content rating filters, screen time limits, notification curfews, web filtering preferences, and algorithmic feed controls. \"Child Profile\" means the data record created by a parent or guardian within the Service for a specific child, containing the child's first name, date of birth, age group, and associated policy assignments.\n\n\"User\" or \"Account\" means the parent, guardian, developer, or enterprise customer who registers for and maintains an account on the Phosra platform. \"Enforcement\" means the technical process of transmitting policy rules to connected platform adapters and verifying that those rules have been applied successfully. \"MCP\" means Model Context Protocol, an open standard for tool-use integrations that Phosra supports to enable AI-assisted parental controls management.",
  },
  {
    id: "accounts",
    title: "Account Registration & Security",
    content:
      "To access the full functionality of the Service, you must register for a Phosra account. By registering, you represent and warrant that you are at least 18 years of age and have the legal capacity to enter into a binding agreement. Each individual may maintain only one Phosra account, and sharing of account credentials is prohibited.\n\nYou must provide accurate, current, and complete information during the registration process and maintain the accuracy of such information throughout the duration of your account. Accounts are managed through Clerk, our authentication provider, which handles password hashing, session management, and multi-factor authentication capabilities.\n\nYou are solely responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify Phosra immediately at security@phosra.com if you become aware of or suspect any unauthorized access to your account, unauthorized use of your API keys, or any other breach of security.\n\nPhosra reserves the right to suspend or terminate accounts that violate these Terms, engage in fraudulent activity, exhibit patterns of abuse, or pose a risk to the security or integrity of the Service or other users' data. We will provide reasonable notice before suspension except where immediate action is required to prevent harm.",
  },
  {
    id: "api-license",
    title: "API License & Usage",
    content:
      "Subject to your compliance with these Terms and all applicable laws, Phosra grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the Phosra API for the purpose of managing child safety policies and enforcing parental controls through the Service.\n\nYou may integrate the Phosra API into your own applications, platforms, or services to manage child profiles, configure policies, connect platforms, trigger enforcement actions, and retrieve enforcement status information. All API usage must comply with these Terms, the Phosra API documentation, the Phosra Child Safety Standard (PCSS), and all applicable local, state, federal, and international laws, including child data protection regulations.\n\nThis license does not grant you any rights to Phosra's source code, proprietary algorithms, internal infrastructure, or any intellectual property beyond the API interface as documented. The license is automatically revoked upon termination of your account or violation of these Terms. You may not transfer, assign, or sublicense your API access to any third party without Phosra's prior written consent.",
  },
  {
    id: "rate-limits",
    title: "Rate Limits & Usage Quotas",
    content:
      "API access is subject to rate limits and usage quotas that vary by subscription tier. These limits are designed to ensure fair access, maintain Service performance, and protect infrastructure stability for all users.\n\nFamily Tier: Accounts on the Family tier are limited to 100 API calls per hour. This tier is designed for individual parents and guardians managing their own family's devices and platforms. Developer Tier: Accounts on the Developer tier are limited to 5,000 API calls per hour. This tier is designed for application developers integrating Phosra into their products. Enterprise Tier: Accounts on the Enterprise tier receive custom rate limits negotiated as part of their service agreement, along with dedicated support and enhanced SLA commitments.\n\nWhen you exceed your tier's rate limit, the API will return HTTP 429 (Too Many Requests) responses until the rate limit window resets. Persistent or intentional circumvention of rate limits, including through the use of multiple accounts, IP rotation, or distributed request patterns designed to evade detection, constitutes a violation of these Terms and may result in temporary or permanent account suspension.\n\nPhosra reserves the right to adjust rate limits with at least 30 days' advance notice. Changes to rate limits will be communicated via email and through the Phosra dashboard. If a rate limit change materially affects your use of the Service, you may terminate your account without penalty during the notice period.",
  },
  {
    id: "data-handling",
    title: "Data Handling & Processing",
    content:
      "You acknowledge and agree that when you submit data to the Service, including child profile information and policy configurations, Phosra acts as a data processor on your behalf. You are the data controller for all child data and personal data you submit through the Service, and you retain full responsibility for the lawfulness of its collection, accuracy, and the purposes for which it is processed.\n\nAs a data controller, you are responsible for ensuring that you have a lawful basis for submitting child data to the Service, including verifiable parental consent where required by applicable law. You represent and warrant that you have the legal authority, whether as a parent, legal guardian, or authorized agent, to submit child data and to authorize Phosra to process it on your behalf for the purposes described in these Terms and our Privacy Policy.\n\nPhosra processes child data solely for the purpose of providing the Service, including policy configuration, enforcement across connected platforms, compliance verification, and audit logging. We do not use child data for any purpose other than service delivery, and we do not sell, license, or otherwise commercialize child data under any circumstances.\n\nA Data Processing Agreement (DPA) that meets the requirements of Article 28 of the GDPR is available for enterprise customers upon request. The DPA sets forth the specific terms governing Phosra's processing of personal data on your behalf, including sub-processor disclosures, data security obligations, breach notification procedures, and data subject rights assistance.",
  },
  {
    id: "children-obligations",
    title: "Children's Data Obligations",
    content:
      "The submission and management of children's data through the Phosra platform carries significant legal and ethical responsibilities. By creating child profiles and submitting child data, you represent, warrant, and covenant the following.\n\nYou represent that you are the parent or legal guardian of each child whose data you submit to the Service, or that you have obtained explicit, verifiable authorization from the child's parent or legal guardian to submit such data. You are responsible for obtaining any and all consents required under applicable law, including verifiable parental consent as mandated by the Children's Online Privacy Protection Act (COPPA) and any applicable state, national, or international child data protection regulations.\n\nYou must comply with all applicable child data protection laws in your jurisdiction, including but not limited to COPPA, the Kids Online Safety Act (KOSA), the EU General Data Protection Regulation (GDPR) as it applies to children's data, the UK Age Appropriate Design Code, and any state-level child privacy legislation. You will not submit data for any child over whom you do not have legal authority, and you will not use the Service to monitor, track, or restrict the activities of individuals who are not your legal dependents.\n\nPhosra reserves the right to delete child data and suspend associated accounts if we have reasonable grounds to believe that child data was submitted without proper authorization, that the submitting user is not the child's parent or legal guardian, or that the data is being used for purposes other than lawful parental monitoring and child safety enforcement. We may report suspected violations to the relevant regulatory authorities, including the Federal Trade Commission.",
  },
  {
    id: "acceptable-use",
    title: "Acceptable Use Policy",
    content:
      "Your use of the Service must at all times comply with these Terms, applicable law, and the following acceptable use standards. You agree that you will not engage in any of the following prohibited activities.\n\nYou must not reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code, algorithms, or internal structure of the Phosra API, platform adapters, or any other component of the Service. You must not use the Service for surveillance, tracking, or monitoring beyond the scope of lawful parental controls for your own minor children or legal dependents. You must not attempt to circumvent, bypass, or disable any security measures, authentication mechanisms, rate limits, or access controls implemented by the Service.\n\nYou must not share, transfer, publish, or expose your API keys, authentication tokens, account credentials, or any other access credentials with or to any unauthorized third party. You must not use the Service in any manner that could harm, exploit, endanger, or violate the rights of children, including using the platform to facilitate unauthorized access to a child's accounts, harvest a child's personal data, or enable any form of child exploitation.\n\nYou must not scrape, harvest, crawl, or collect data from the Service beyond the scope of your authorized API access. You must not impersonate other users, misrepresent your identity or affiliation, or create accounts under false pretenses. You must not use the Service to transmit malware, viruses, or any code designed to disrupt, damage, or interfere with the operation of the Service or any connected platform. Violation of this Acceptable Use Policy may result in immediate suspension or termination of your account.",
  },
  {
    id: "ip",
    title: "Intellectual Property",
    content:
      "Phosra, Inc. owns and retains all right, title, and interest in and to the Service, including the Phosra API, the Phosra Child Safety Standard (PCSS) specification, all platform adapter implementations, the Phosra dashboard, developer documentation, the phosra.com website, all associated trademarks, service marks, logos, trade dress, and the underlying technology, architecture, and infrastructure. These rights are protected by United States and international intellectual property laws.\n\nYou retain all ownership rights to the data you submit to the Service, including account information, child profile data, policy configurations, and platform credentials. Nothing in these Terms transfers ownership of your data to Phosra. You grant Phosra a limited, non-exclusive, worldwide, royalty-free license to process, store, transmit, and use your data solely for the purpose of providing and improving the Service as described in these Terms and our Privacy Policy. This license terminates upon deletion of your data or termination of your account.\n\nIf you provide Phosra with feedback, suggestions, enhancement requests, recommendations, or other input regarding the Service (\"Feedback\"), you grant Phosra an unrestricted, irrevocable, perpetual, royalty-free license to use, modify, and incorporate such Feedback into the Service without any obligation to you. You acknowledge that Feedback is provided voluntarily and that Phosra is under no obligation to implement, acknowledge, or compensate you for any Feedback.",
  },
  {
    id: "third-party",
    title: "Third-Party Platforms",
    content:
      "A core function of the Phosra Service is the enforcement of parental control policies across third-party digital platforms. You acknowledge and agree that the availability and effectiveness of enforcement depends on factors outside of Phosra's control, including the APIs, policies, and technical capabilities of those third-party platforms.\n\nPhosra does not guarantee that all connected platforms will support all policy rule categories at all times. Platform providers may modify, restrict, or deprecate their APIs, which may affect Phosra's ability to enforce certain rules. When a platform change affects enforcement capability, we will make reasonable efforts to notify you through the dashboard and to update our platform adapter accordingly, but we cannot guarantee uninterrupted enforcement across all platforms.\n\nYou are responsible for maintaining valid credentials for each connected platform and for ensuring that your use of those platforms complies with their respective terms of service. Phosra is not responsible for actions taken by third-party platforms, including account suspension, content removal, or policy changes enacted by those platforms independently of Phosra enforcement actions.\n\nThe storage, encryption, and usage of platform credentials is governed by our Privacy Policy. Phosra accesses your platform accounts only to the extent necessary to apply and verify the enforcement of your configured policy rules. We do not access platform accounts for any purpose other than authorized enforcement operations.",
  },
  {
    id: "warranties",
    title: "Warranties & Disclaimers",
    content:
      "Phosra makes reasonable commercial efforts to ensure that the Service operates reliably, that enforcement actions are executed accurately, and that your data is handled securely. However, given the complexity of operating across 188+ third-party platforms and the inherent unpredictability of distributed systems, certain limitations apply.\n\nTHE SERVICE IS PROVIDED ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, PHOSRA, INC. DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, AND ANY WARRANTIES ARISING FROM COURSE OF DEALING OR USAGE OF TRADE.\n\nPhosra does not warrant that the Service will be uninterrupted, error-free, or free of harmful components. We do not warrant that all policy rules will be successfully enforced on all connected platforms at all times, as enforcement depends on third-party platform availability and API compatibility. We do not warrant that the Service will meet your specific requirements or expectations beyond the functionality described in our documentation.\n\nEnterprise customers may negotiate separate Service Level Agreements (SLAs) that provide specific uptime commitments, response time guarantees, and remedies for service interruptions. Such SLAs, where executed, shall supersede the disclaimers in this section to the extent of any conflict. The disclaimers in this section do not affect any rights that cannot be waived or limited under applicable consumer protection law.",
  },
  {
    id: "liability",
    title: "Limitation of Liability",
    content:
      "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL PHOSRA, INC., ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, LICENSORS, OR SERVICE PROVIDERS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES, REGARDLESS OF WHETHER SUCH DAMAGES WERE FORESEEABLE AND WHETHER OR NOT PHOSRA WAS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.\n\nTO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, PHOSRA'S TOTAL AGGREGATE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR USE OF THE SERVICE SHALL NOT EXCEED THE GREATER OF: (A) THE TOTAL AMOUNTS PAID BY YOU TO PHOSRA DURING THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM; OR (B) ONE HUNDRED UNITED STATES DOLLARS ($100.00).\n\nTHIS LIMITATION OF LIABILITY APPLIES TO ALL CLAIMS, WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, STATUTE, OR ANY OTHER LEGAL THEORY, AND REGARDLESS OF WHETHER THE REMEDY PROVIDED HEREIN FAILS OF ITS ESSENTIAL PURPOSE. Some jurisdictions do not allow the exclusion or limitation of certain damages, so the above limitations may not apply to you to the extent prohibited by applicable law. In such cases, Phosra's liability shall be limited to the fullest extent permitted by applicable law.",
  },
  {
    id: "indemnification",
    title: "Indemnification",
    content:
      "You agree to indemnify, defend, and hold harmless Phosra, Inc., its parent companies, subsidiaries, affiliates, officers, directors, employees, agents, licensors, and service providers from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable attorneys' fees and court costs) arising out of or relating to the following.\n\nYour use of the Service, including any enforcement actions triggered through your account. Any violation by you of these Terms, the Acceptable Use Policy, or the Privacy Policy. Any violation by you of any applicable law, regulation, or rule, including child data protection laws such as COPPA, KOSA, GDPR, or any equivalent legislation in your jurisdiction. Any data, content, or child profile information that you submit to the Service, including claims that such data was submitted without proper authorization or consent.\n\nAny infringement or misappropriation by you of any third-party intellectual property right, privacy right, or other proprietary right. Any dispute between you and a third-party platform arising from enforcement actions initiated through the Service. This indemnification obligation survives the termination of your account and these Terms.\n\nPhosra will provide you with prompt written notice of any claim subject to indemnification, cooperate with you in the defense of such claim, and permit you to control the defense and settlement of the claim, provided that no settlement may be made without Phosra's prior written consent if such settlement would impose any obligation or liability on Phosra or admit fault on Phosra's behalf.",
  },
  {
    id: "termination",
    title: "Termination",
    content:
      "Either party may terminate the relationship governed by these Terms at any time, subject to the following provisions.\n\nYou may close your Phosra account at any time through the Settings page in the Phosra dashboard. Account closure is self-service and does not require contacting Phosra support. Upon initiating account closure, your API access will be revoked immediately, connected platform credentials will be deleted immediately, and enforcement of all active policies will cease.\n\nPhosra may terminate or suspend your account if you materially breach these Terms and fail to cure the breach within 14 days of written notice, if your account is used for illegal activity, if your continued use of the Service poses a risk to the security or integrity of the platform or other users' data, or if required by law or regulation. In cases involving imminent harm to children, illegal activity, or security threats, Phosra may suspend access immediately without prior notice.\n\nUpon termination by either party: all API access is revoked immediately; your account data (profile, settings, policy configurations) remains available for export for 30 days after termination; all child profiles and associated data are permanently deleted within 30 days; all connected platform credentials are deleted immediately; and enforcement job history is retained for the legally required audit period and then deleted. The following sections survive termination: Intellectual Property, Warranties and Disclaimers, Limitation of Liability, Indemnification, Governing Law and Disputes, and General Provisions.",
  },
  {
    id: "governing-law",
    title: "Governing Law & Disputes",
    content:
      "These Terms, and any dispute or claim arising out of or relating to these Terms or the Service (including non-contractual disputes), shall be governed by and construed in accordance with the laws of the State of Delaware, United States of America, without giving effect to any principles of conflicts of law that would cause the application of the laws of any other jurisdiction.\n\nAny dispute, controversy, or claim arising out of or relating to these Terms, or the breach, termination, or validity thereof, shall be resolved through binding arbitration administered by the American Arbitration Association (AAA) under its Commercial Arbitration Rules. The arbitration shall be conducted in Wilmington, Delaware, before a single arbitrator selected in accordance with AAA procedures. The arbitrator's decision shall be final and binding, and judgment upon the award may be entered in any court of competent jurisdiction.\n\nCLASS ACTION WAIVER: YOU AND PHOSRA AGREE THAT EACH PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, CONSOLIDATED, OR REPRESENTATIVE PROCEEDING. The arbitrator may not consolidate more than one person's claims and may not preside over any form of class or representative proceeding. Each party shall bear its own costs and attorneys' fees incurred in connection with any arbitration proceeding.\n\nSmall Claims Court Exception: Notwithstanding the foregoing, either party may bring qualifying claims in small claims court in Wilmington, Delaware, or the county in which you reside, provided the claim falls within the court's jurisdictional limits and remains in small claims court. If the claim is removed or transferred to a court of general jurisdiction, the arbitration provisions of this section shall apply.",
  },
  {
    id: "general",
    title: "General Provisions",
    content:
      "Severability: If any provision of these Terms is held by a court or arbitrator of competent jurisdiction to be invalid, illegal, or unenforceable, such provision shall be modified to the minimum extent necessary to make it enforceable, or if modification is not possible, shall be severed from these Terms. The invalidity or unenforceability of any provision shall not affect the validity or enforceability of the remaining provisions, which shall continue in full force and effect.\n\nWaiver: The failure of Phosra to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision. A waiver of any right or provision shall be effective only if made in writing and signed by an authorized representative of Phosra, and shall apply only to the specific instance for which it is given.\n\nEntire Agreement: These Terms, together with the Privacy Policy and any applicable Data Processing Agreement or Enterprise Service Level Agreement, constitute the entire agreement between you and Phosra with respect to the Service and supersede all prior or contemporaneous understandings, agreements, representations, and warranties, whether written or oral, regarding the Service.\n\nAssignment: You may not assign, transfer, or delegate any of your rights or obligations under these Terms without Phosra's prior written consent. Phosra may assign these Terms, in whole or in part, without restriction, in connection with a merger, acquisition, corporate reorganization, or sale of all or substantially all of its assets, provided that the assignee agrees to be bound by these Terms.\n\nNotices: All notices required or permitted under these Terms shall be sent via email to the address associated with your Phosra account. Notices to Phosra should be directed to legal@phosra.com. Notices are deemed received when sent to the email address on file. Force Majeure: Neither party shall be liable for any delay or failure to perform obligations under these Terms due to events beyond its reasonable control, including natural disasters, acts of government, pandemics, internet or telecommunications failures, power outages, cyberattacks, or labor disputes. Contact: legal@phosra.com. Phosra, Inc., Wilmington, Delaware, United States.",
  },
]
