import type { MovementEntry } from "./types"

export const MOVEMENTS_REGISTRY: MovementEntry[] = [
  /* ──────────────────────────────────────────────────────────────────
   * ❶  FLAGSHIP MOVEMENTS (existing)
   * ────────────────────────────────────────────────────────────────── */
  {
    id: "four-norms",
    slug: "four-norms",
    name: "Four Norms",
    organization: "The Anxious Generation",
    organizationUrl: "https://www.anxiousgeneration.com",
    status: "active",
    description: "Jonathan Haidt's four foundational norms for a phone-free childhood.",
    longDescription:
      "Based on The Anxious Generation by Jonathan Haidt, the Four Norms represent a research-backed framework for protecting children from the harms of smartphone-based childhood. Families following this standard can use Phosra to translate these norms into enforceable rules across every connected platform — turning a social pledge into verified, cross-platform protection.",
    iconEmoji: "📱",
    iconUrl: "/movements/icons/four-norms.png",
    accentColor: "#E85D3A",
    rules: [
      { category: "social_media_min_age", label: "No social media", value: "Until age 16", maxAge: 16 },
      { category: "privacy_account_creation", label: "No smartphones", value: "Until age 14", maxAge: 14 },
      { category: "time_scheduled_hours", label: "Phone-free schools", value: "School hours blocked" },
      { category: "time_daily_limit", label: "More outdoor play", value: "120 min/day minimum" },
    ],
    tags: ["mental-health", "phone-free", "schools", "social-media"],
    minAge: 0,
    maxAge: 16,
    adoptionCount: 2847,
    schoolCount: 142,
  },
  {
    id: "wait-until-8th",
    slug: "wait-until-8th",
    name: "Wait Until 8th",
    organization: "Wait Until 8th",
    organizationUrl: "https://www.waituntil8th.org",
    status: "active",
    description: "A community pledge to delay smartphones until at least 8th grade.",
    longDescription:
      "Wait Until 8th is a grassroots movement of over 130,000 families who pledge to wait until at least 8th grade before giving their children a smartphone. Phosra can enforce this pledge at the device level for families who adopt it — restricting smartphone app access, social media, and mature content across all connected platforms until the child reaches 8th grade age.",
    iconEmoji: "✋",
    iconUrl: "/movements/icons/wait-until-8th.png",
    accentColor: "#4A90D9",
    rules: [
      { category: "privacy_account_creation", label: "No smartphone apps", value: "Until 8th grade (~14)", maxAge: 14 },
      { category: "social_media_min_age", label: "No social media", value: "Until 8th grade", maxAge: 14 },
      { category: "content_rating", label: "Age-appropriate content", value: "Strict filtering" },
      { category: "web_filter_level", label: "Web filtering", value: "Strict" },
      { category: "monitoring_activity", label: "Activity monitoring", value: "Enabled" },
    ],
    tags: ["smartphone-delay", "pledge", "community", "grassroots"],
    minAge: 0,
    maxAge: 14,
    adoptionCount: 4213,
    schoolCount: 287,
  },
  {
    id: "screen-smart-family",
    slug: "screen-smart-family",
    name: "Screen-Smart Family",
    organization: "Phosra",
    status: "active",
    description: "Phosra's recommended baseline for balanced screen time and online safety.",
    longDescription:
      "The Screen-Smart Family standard is Phosra's own curated best-practice ruleset, designed by child development experts and informed by current legislation (KOSA, COPPA 2.0). It provides a balanced, age-adaptive approach to screen time, content filtering, and privacy — automatically adjusting rules as your child grows.",
    iconEmoji: "🛡️",
    iconUrl: "/mark.svg",
    accentColor: "#00D47E",
    rules: [
      { category: "time_daily_limit", label: "Daily screen time", value: "Age-adaptive limits" },
      { category: "content_rating", label: "Content ratings", value: "Age-appropriate" },
      { category: "web_safesearch", label: "Safe search", value: "Enforced" },
      { category: "social_chat_control", label: "Chat controls", value: "Known contacts only" },
      { category: "purchase_approval", label: "Purchase approval", value: "Required" },
      { category: "privacy_data_sharing", label: "Data sharing", value: "Minimal" },
    ],
    tags: ["balanced", "recommended", "phosra", "best-practice"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 6502,
    schoolCount: 0,
  },
  {
    id: "screen-free-schools",
    slug: "screen-free-schools",
    name: "Screen-Free Schools",
    organization: "Screen Time Action Network",
    organizationUrl: "https://screentimenetwork.org",
    status: "coming_soon",
    description: "Comprehensive device restrictions during school hours for focused learning.",
    longDescription:
      "The Screen-Free Schools standard enforces phone-free policies during school hours, blocking social media, gaming, and non-educational content during the school day. Designed for school-wide adoption, it activates when 10 or more families in a grade level adopt it — creating community-wide accountability for distraction-free learning.",
    iconEmoji: "🏫",
    iconUrl: "/movements/icons/screen-free-schools.png",
    accentColor: "#7B5CB8",
    rules: [
      { category: "time_scheduled_hours", label: "School hours", value: "All non-educational blocked" },
      { category: "social_media_min_age", label: "Social media", value: "Blocked during school" },
      { category: "notification_curfew", label: "Notifications", value: "Silenced during school" },
      { category: "algo_feed_control", label: "Algorithmic feeds", value: "Disabled during school" },
    ],
    tags: ["schools", "education", "phone-free", "focus"],
    minAge: 5,
    maxAge: 18,
    adoptionCount: 0,
    schoolCount: 0,
  },

  /* ──────────────────────────────────────────────────────────────────
   * ❷  GRASSROOTS PLEDGE MOVEMENTS
   * ────────────────────────────────────────────────────────────────── */
  {
    id: "smartphone-free-childhood",
    slug: "smartphone-free-childhood",
    name: "Smartphone Free Childhood",
    organization: "Smartphone Free Childhood",
    organizationUrl: "https://smartphonefreechildhood.co.uk",
    status: "active",
    description: "UK-based parent movement to delay smartphone access and build phone-free communities.",
    longDescription:
      "Smartphone Free Childhood is one of the fastest-growing parental movements in the UK, with over 100,000 parents joining local WhatsApp groups to collectively delay smartphone access. Founded in 2024 by Daisy Greenwell and Clare Fernyhough, it provides community support for families choosing to resist peer pressure around early smartphone adoption. Families using Phosra can enforce the pledge at the device level — restricting app installs, social media, and web browsing across all connected devices until the child is ready.",
    iconEmoji: "🇬🇧",
    iconUrl: "/movements/icons/smartphone-free-childhood.png",
    accentColor: "#1D4ED8",
    rules: [
      { category: "privacy_account_creation", label: "No smartphone apps", value: "Until secondary school", maxAge: 11 },
      { category: "social_media_min_age", label: "No social media", value: "Until age 16", maxAge: 16 },
      { category: "content_rating", label: "Content filtering", value: "Strict age gates" },
      { category: "dm_restriction", label: "Direct messages", value: "Blocked", maxAge: 13 },
      { category: "web_filter_level", label: "Web filtering", value: "Strict" },
    ],
    tags: ["uk", "grassroots", "smartphone-delay", "community", "pledge"],
    minAge: 0,
    maxAge: 16,
    adoptionCount: 1893,
    schoolCount: 64,
  },
  {
    id: "the-balance-project",
    slug: "the-balance-project",
    name: "The Balance Project",
    organization: "The Balance Project",
    organizationUrl: "https://thebalanceproject.org",
    status: "active",
    description: "Family-centered framework balancing tech use with real-world connection and play.",
    longDescription:
      "The Balance Project helps families find a sustainable middle ground on technology — not banning screens entirely, but building intentional habits around when, where, and how devices are used. Their framework emphasizes tech-free meals, bedtime routines, and outdoor time. Families using Phosra can turn these habits into automated rules — scheduled downtime, per-app limits, and notification curfews enforced consistently across platforms.",
    iconEmoji: "⚖️",
    iconUrl: "/movements/icons/the-balance-project.png",
    accentColor: "#059669",
    rules: [
      { category: "time_daily_limit", label: "Balanced screen time", value: "Age-appropriate daily caps" },
      { category: "time_downtime", label: "Tech-free meals & bedtime", value: "Scheduled downtime blocks" },
      { category: "notification_curfew", label: "Evening quiet hours", value: "8 PM–7 AM curfew" },
      { category: "time_per_app_limit", label: "Per-app limits", value: "Entertainment capped" },
      { category: "algo_feed_control", label: "Feed controls", value: "Chronological only" },
    ],
    tags: ["balanced", "family", "screen-time", "habits", "wellness"],
    minAge: 3,
    maxAge: 17,
    adoptionCount: 1247,
    schoolCount: 0,
  },

  /* ──────────────────────────────────────────────────────────────────
   * ❸  MAJOR NONPROFITS & ADVOCACY ORGANIZATIONS
   * ────────────────────────────────────────────────────────────────── */
  {
    id: "fairplay-commercial-free",
    slug: "fairplay-commercial-free",
    name: "Fairplay Standard",
    organization: "Fairplay (formerly CCFC)",
    organizationUrl: "https://fairplayforkids.org",
    status: "active",
    description: "Protecting children from manipulative design, exploitative marketing, and commercial surveillance.",
    longDescription:
      "Fairplay (formerly the Campaign for a Commercial-Free Childhood) has been at the forefront of child protection advocacy for over 25 years, winning landmark victories against companies like Facebook and Google. Their standard focuses on shielding children from manipulative design patterns, targeted advertising, and commercial data exploitation. With Phosra, families can enforce these protections at the platform level — blocking targeted ads, disabling addictive design features, and restricting data collection across every connected service.",
    iconEmoji: "🎯",
    iconUrl: "/movements/icons/fairplay-commercial-free.png",
    accentColor: "#DC2626",
    rules: [
      { category: "targeted_ad_block", label: "Block targeted ads", value: "All platforms" },
      { category: "addictive_design_control", label: "Disable addictive design", value: "Autoplay, infinite scroll off" },
      { category: "commercial_data_ban", label: "No commercial data use", value: "Block data sharing" },
      { category: "privacy_data_sharing", label: "Data minimization", value: "Strict" },
      { category: "purchase_block_iap", label: "Block in-app purchases", value: "No loot boxes or IAP" },
      { category: "algo_feed_control", label: "No algorithmic feeds", value: "Chronological or disabled" },
    ],
    tags: ["advertising", "privacy", "commercial-free", "advocacy", "manipulative-design"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 3156,
    schoolCount: 0,
  },
  {
    id: "common-sense-media",
    slug: "common-sense-media",
    name: "Common Sense Standard",
    organization: "Common Sense Media",
    organizationUrl: "https://www.commonsensemedia.org",
    status: "active",
    description: "Age-based media ratings and digital citizenship framework for every platform.",
    longDescription:
      "Common Sense Media is the largest media rating organization for families, providing age-based ratings for movies, games, apps, and websites used by over 100 million families worldwide. Their standard enforces age-appropriate content ratings, digital citizenship principles, and privacy protections based on their expert reviews. Families using Phosra can automatically apply Common Sense ratings as content filtering rules across streaming, gaming, and social platforms.",
    iconEmoji: "⭐",
    iconUrl: "/movements/icons/common-sense-media.png",
    accentColor: "#F59E0B",
    rules: [
      { category: "content_rating", label: "Common Sense ratings", value: "Age-matched filtering" },
      { category: "content_descriptor_block", label: "Block mature descriptors", value: "Violence, sex, language" },
      { category: "web_safesearch", label: "Safe search", value: "Enforced across engines" },
      { category: "privacy_profile_visibility", label: "Profile privacy", value: "Private by default" },
      { category: "social_chat_control", label: "Chat safety", value: "Age-gated access" },
    ],
    tags: ["ratings", "media-literacy", "digital-citizenship", "content-filtering", "education"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 5421,
    schoolCount: 312,
  },
  {
    id: "parents-together",
    slug: "parents-together",
    name: "ParentsTogether Standard",
    organization: "ParentsTogether Foundation",
    organizationUrl: "https://parentstogether.org",
    status: "active",
    description: "Multi-million member parent network focused on Big Tech accountability and child safety.",
    longDescription:
      "ParentsTogether is a 3-million-member parent organization that campaigns for Big Tech accountability, child online safety legislation, and family-friendly platform design. Their standard combines strong privacy protections with algorithmic transparency requirements — pushing platforms to prioritize child wellbeing over engagement metrics. Phosra can translate their advocacy into enforceable platform rules for families who adopt this standard.",
    iconEmoji: "👨‍👩‍👧‍👦",
    accentColor: "#8B5CF6",
    rules: [
      { category: "algo_feed_control", label: "Algorithmic transparency", value: "No engagement-optimized feeds" },
      { category: "targeted_ad_block", label: "No targeted ads", value: "Block all behavioral ads" },
      { category: "privacy_data_sharing", label: "Data protection", value: "No third-party sharing" },
      { category: "addictive_design_control", label: "Anti-addiction controls", value: "Disable dark patterns" },
      { category: "parental_event_notification", label: "Parent notifications", value: "Flagged content alerts" },
      { category: "algorithmic_audit", label: "Algorithmic audit", value: "Transparency required" },
    ],
    tags: ["advocacy", "tech-accountability", "privacy", "algorithm", "parent-network"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 2834,
    schoolCount: 0,
  },
  {
    id: "protect-young-eyes",
    slug: "protect-young-eyes",
    name: "Protect Young Eyes",
    organization: "Protect Young Eyes",
    organizationUrl: "https://protectyoungeyes.com",
    status: "active",
    description: "Digital safety education with practical device-level protection recommendations.",
    longDescription:
      "Protect Young Eyes provides families and schools with actionable digital safety education, including app reviews, device setup guides, and age-based technology roadmaps. Founded by Chris McKenna, they have presented to over 500,000 parents and 300,000 students. Their standard translates their device safety recommendations into enforceable rules — from web filtering and safe search to app restrictions and monitoring.",
    iconEmoji: "👁️",
    iconUrl: "/movements/icons/protect-young-eyes.png",
    accentColor: "#0EA5E9",
    rules: [
      { category: "web_filter_level", label: "DNS-level filtering", value: "Strict" },
      { category: "web_safesearch", label: "Safe search", value: "Locked on all engines" },
      { category: "content_rating", label: "App age ratings", value: "Enforced" },
      { category: "monitoring_activity", label: "Activity monitoring", value: "Weekly reports" },
      { category: "monitoring_alerts", label: "Safety alerts", value: "Predatory contact, sexting" },
      { category: "web_category_block", label: "Category blocking", value: "Adult, gambling, drugs" },
    ],
    tags: ["education", "device-safety", "monitoring", "web-filtering", "schools"],
    minAge: 3,
    maxAge: 17,
    adoptionCount: 1876,
    schoolCount: 198,
  },

  /* ──────────────────────────────────────────────────────────────────
   * ❹  CLINICAL & RESEARCH-BASED GUIDELINES
   * ────────────────────────────────────────────────────────────────── */
  {
    id: "aap-family-media-plan",
    slug: "aap-family-media-plan",
    name: "AAP Family Media Plan",
    organization: "American Academy of Pediatrics",
    organizationUrl: "https://www.healthychildren.org/English/fmp",
    status: "active",
    description: "Pediatrician-backed screen time and media guidelines from the American Academy of Pediatrics.",
    longDescription:
      "The AAP Family Media Plan is the gold standard in pediatric screen time guidance, developed by the American Academy of Pediatrics based on decades of child development research. It recommends zero screen time under 18 months, co-viewing for ages 2–5, and consistent limits with media-free zones for older children. With Phosra, families can turn these clinical recommendations into real device-level rules — enforcing age-tiered time limits, content restrictions, and device-free periods.",
    iconEmoji: "🩺",
    accentColor: "#0891B2",
    rules: [
      { category: "time_daily_limit", label: "Screen time caps", value: "0 min (0–18mo), 60 min (2–5), custom (6+)" },
      { category: "content_rating", label: "Content quality", value: "Educational priority" },
      { category: "time_downtime", label: "Media-free zones", value: "Bedrooms, mealtimes" },
      { category: "time_scheduled_hours", label: "Bedtime device off", value: "1 hr before sleep" },
      { category: "notification_curfew", label: "Sleep protection", value: "No alerts during sleep" },
    ],
    tags: ["clinical", "pediatrics", "screen-time", "research-backed", "health"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 4187,
    schoolCount: 0,
  },
  {
    id: "who-screen-time-guidelines",
    slug: "who-screen-time-guidelines",
    name: "WHO Early Years Guidelines",
    organization: "World Health Organization",
    organizationUrl: "https://www.who.int/publications/i/item/9789241550536",
    status: "active",
    description: "World Health Organization guidelines on physical activity, sedentary behavior, and screen time for under-5s.",
    longDescription:
      "The WHO Guidelines on Physical Activity, Sedentary Behaviour and Sleep for Children Under 5 provide evidence-based limits on screen exposure for the youngest children. They recommend zero sedentary screen time for infants under 1, no more than 1 hour for ages 2–4, and emphasize active play and quality sleep. Families using Phosra can enforce these international health standards as hard device limits during a child's earliest years.",
    iconEmoji: "🌍",
    iconUrl: "/movements/icons/who-screen-time-guidelines.png",
    accentColor: "#2563EB",
    rules: [
      { category: "time_daily_limit", label: "Screen time limits", value: "0 min (<1yr), 60 min (2–4yr)" },
      { category: "content_rating", label: "Content quality", value: "Educational only" },
      { category: "content_allowlist_mode", label: "Allowlist mode", value: "Pre-approved apps only" },
      { category: "time_downtime", label: "Active play priority", value: "180 min physical activity" },
    ],
    tags: ["clinical", "who", "early-years", "health", "international", "research-backed"],
    minAge: 0,
    maxAge: 5,
    adoptionCount: 2341,
    schoolCount: 0,
  },
  {
    id: "children-and-screens",
    slug: "children-and-screens",
    name: "Children and Screens",
    organization: "Children and Screens: Institute of Digital Media and Child Development",
    organizationUrl: "https://www.childrenandscreens.org",
    status: "active",
    description: "Research institute providing evidence-based guidelines on children's digital media use.",
    longDescription:
      "Children and Screens is the leading interdisciplinary research institute studying the effects of digital media on child development, founded by Dr. Pamela Hurst-Della Pietra. Their recommendations synthesize findings from neuroscience, psychology, and pediatrics into actionable guidelines covering screen time, social media, gaming, and sleep. Phosra can translate these research-based recommendations into measurable platform rules for families who adopt them.",
    iconEmoji: "🔬",
    iconUrl: "/movements/icons/children-and-screens.png",
    accentColor: "#6366F1",
    rules: [
      { category: "time_daily_limit", label: "Evidence-based time caps", value: "Age-tiered limits" },
      { category: "social_media_min_age", label: "Social media delay", value: "Until age 13+", maxAge: 13 },
      { category: "addictive_design_control", label: "Anti-compulsive design", value: "Disable autoplay, streaks" },
      { category: "time_downtime", label: "Sleep hygiene", value: "No screens 1hr before bed" },
      { category: "screen_time_report", label: "Usage transparency", value: "Weekly family reports" },
    ],
    tags: ["research", "neuroscience", "child-development", "evidence-based", "academic"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 1453,
    schoolCount: 47,
  },

  /* ──────────────────────────────────────────────────────────────────
   * ❺  TECH ACCOUNTABILITY & HUMANE DESIGN
   * ────────────────────────────────────────────────────────────────── */
  {
    id: "center-for-humane-technology",
    slug: "center-for-humane-technology",
    name: "Humane Tech Standard",
    organization: "Center for Humane Technology",
    organizationUrl: "https://www.humanetech.com",
    status: "active",
    description: "Advocating for technology that protects attention, mental health, and democratic values.",
    longDescription:
      "The Center for Humane Technology, founded by former Google design ethicist Tristan Harris and featured in The Social Dilemma, works to realign technology with humanity. Their standard focuses on dismantling the attention economy for children — disabling algorithmic feeds, removing engagement-driven notifications, and blocking persuasive design patterns. With Phosra, families can turn the humane technology vision into real protection at the device level.",
    iconEmoji: "🧠",
    iconUrl: "/movements/icons/center-for-humane-technology.png",
    accentColor: "#7C3AED",
    rules: [
      { category: "algo_feed_control", label: "No algorithmic feeds", value: "Chronological or off" },
      { category: "addictive_design_control", label: "Disable dark patterns", value: "No autoplay, infinite scroll" },
      { category: "notification_curfew", label: "Notification limits", value: "Batch mode, no push" },
      { category: "usage_timer_notification", label: "Usage awareness", value: "Timer reminders every 30 min" },
      { category: "targeted_ad_block", label: "No behavioral targeting", value: "Block all tracked ads" },
      { category: "privacy_data_sharing", label: "Data minimization", value: "No engagement tracking" },
    ],
    tags: ["humane-design", "attention", "tech-accountability", "algorithm", "mental-health"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 2198,
    schoolCount: 0,
  },
  {
    id: "design-it-for-us",
    slug: "design-it-for-us",
    name: "Design It For Us",
    organization: "Design It For Us",
    organizationUrl: "https://www.designitforus.org",
    status: "active",
    description: "Youth-led coalition demanding platforms be designed with young people's safety in mind.",
    longDescription:
      "Design It For Us is a coalition of youth-led organizations including teens who have testified before Congress about the harms of social media. They demand that platforms be designed with young people's safety as a priority, not an afterthought. Their standard enforces the protections they have personally advocated for — strict privacy defaults, anti-exploitation safeguards, and meaningful age verification. Families using Phosra can enforce their generation's demands as platform-level rules.",
    iconEmoji: "🗣️",
    iconUrl: "/movements/icons/design-it-for-us.png",
    accentColor: "#EC4899",
    rules: [
      { category: "privacy_profile_visibility", label: "Private by default", value: "No public profiles" },
      { category: "dm_restriction", label: "DM safety", value: "Known contacts only", maxAge: 16 },
      { category: "age_gate", label: "Age verification", value: "Verified age gates" },
      { category: "algo_feed_control", label: "Safe-by-design feeds", value: "No engagement optimization" },
      { category: "addictive_design_control", label: "Anti-manipulation", value: "No FOMO mechanics" },
      { category: "image_rights_minor", label: "Image protections", value: "No minor image scraping" },
    ],
    tags: ["youth-led", "platform-design", "advocacy", "privacy", "social-media"],
    minAge: 10,
    maxAge: 17,
    adoptionCount: 987,
    schoolCount: 0,
  },
  {
    id: "log-off-movement",
    slug: "log-off-movement",
    name: "Log Off Movement",
    organization: "Log Off",
    organizationUrl: "https://www.logoffmovement.org",
    status: "beta",
    description: "Youth-founded organization promoting healthy social media habits and digital wellbeing.",
    longDescription:
      "Log Off is a youth-founded nonprofit that empowers young people to take control of their digital lives through education, peer support, and advocacy. Founded by Emma Lembke at age 16 after personally experiencing the negative effects of social media, the organization has grown into a national movement. Their standard focuses on breaking compulsive usage patterns and building intentional digital habits. With Phosra, families can put these principles into practice as scheduled breaks, usage caps, and feed controls.",
    iconEmoji: "📴",
    iconUrl: "/movements/icons/log-off-movement.png",
    accentColor: "#F97316",
    rules: [
      { category: "time_per_app_limit", label: "Social media caps", value: "30 min/day per app" },
      { category: "usage_timer_notification", label: "Break reminders", value: "Every 20 minutes" },
      { category: "addictive_design_control", label: "Disable compulsive features", value: "No streaks, no FOMO" },
      { category: "time_downtime", label: "Digital detox hours", value: "Weekend morning blocks" },
      { category: "algo_feed_control", label: "Feed detox", value: "Chronological mode" },
    ],
    tags: ["youth-led", "digital-wellbeing", "social-media", "habits", "mental-health"],
    minAge: 12,
    maxAge: 17,
    adoptionCount: 634,
    schoolCount: 0,
  },

  /* ──────────────────────────────────────────────────────────────────
   * ❻  UK & INTERNATIONAL CHILD SAFETY
   * ────────────────────────────────────────────────────────────────── */
  {
    id: "5rights-foundation",
    slug: "5rights-foundation",
    name: "5Rights Standard",
    organization: "5Rights Foundation",
    organizationUrl: "https://5rightsfoundation.com",
    status: "active",
    description: "International framework ensuring children's digital rights, architects of the UK Age Appropriate Design Code.",
    longDescription:
      "The 5Rights Foundation, led by Baroness Beeban Kidron, developed the framework behind the UK's Age Appropriate Design Code (Children's Code) — the most influential piece of child online safety regulation globally. Their five rights — to remove, to know, to safety, to digital literacy, and to agency — have shaped legislation in the UK, EU, and California. Families using Phosra can enforce these rights as platform rules — including data deletion requests, algorithmic transparency, and privacy-by-default settings.",
    iconEmoji: "🔑",
    iconUrl: "/movements/icons/5rights-foundation.png",
    accentColor: "#14B8A6",
    rules: [
      { category: "data_deletion_request", label: "Right to remove", value: "Data erasure on demand" },
      { category: "algorithmic_audit", label: "Right to know", value: "Algorithmic transparency" },
      { category: "privacy_data_sharing", label: "Privacy by default", value: "Highest privacy settings" },
      { category: "geolocation_opt_in", label: "Location privacy", value: "Off by default" },
      { category: "parental_consent_gate", label: "Parental consent", value: "Required for data collection" },
      { category: "commercial_data_ban", label: "No data profiling", value: "Block commercial profiling" },
    ],
    tags: ["uk", "international", "digital-rights", "legislation", "privacy", "age-appropriate-design"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 1567,
    schoolCount: 0,
  },
  {
    id: "molly-rose-foundation",
    slug: "molly-rose-foundation",
    name: "Molly Rose Standard",
    organization: "Molly Rose Foundation",
    organizationUrl: "https://mollyrosefoundation.org",
    status: "active",
    description: "Campaigning to end online harms to children, founded after the death of Molly Russell.",
    longDescription:
      "The Molly Rose Foundation was established by Ian Russell after his daughter Molly took her own life at age 14, influenced by harmful content on social media. The foundation campaigns to make the internet a safer place for children and was instrumental in shaping the UK Online Safety Act. Their standard focuses on blocking self-harm content, restricting algorithmic recommendation of harmful material, and ensuring platforms have robust CSAM reporting. Families using Phosra can enforce these protections across every connected platform.",
    iconEmoji: "🌹",
    iconUrl: "/movements/icons/molly-rose-foundation.png",
    accentColor: "#BE185D",
    rules: [
      { category: "web_category_block", label: "Block harmful content", value: "Self-harm, suicide, eating disorders" },
      { category: "algo_feed_control", label: "Safe recommendations", value: "No harmful content amplification" },
      { category: "csam_reporting", label: "CSAM reporting", value: "Platform compliance required" },
      { category: "monitoring_alerts", label: "Safety alerts", value: "Harmful content detection" },
      { category: "content_descriptor_block", label: "Content filtering", value: "Block dangerous descriptors" },
    ],
    tags: ["uk", "online-safety", "mental-health", "harmful-content", "advocacy", "legislation"],
    minAge: 10,
    maxAge: 17,
    adoptionCount: 1234,
    schoolCount: 0,
  },
  {
    id: "australian-esafety",
    slug: "australian-esafety",
    name: "eSafety Standard",
    organization: "Australian eSafety Commissioner",
    organizationUrl: "https://www.esafety.gov.au",
    status: "active",
    description: "Australia's official online safety framework with age verification and platform accountability requirements.",
    longDescription:
      "The Australian eSafety Commissioner is the world's first government agency dedicated to online safety, led by Commissioner Julie Inman Grant. Their framework includes mandatory age verification for social media (16+ under the Online Safety Amendment Act), industry codes of practice, and a complaints system for cyberbullying and harmful content. With Phosra, families can apply the eSafety framework's protections as platform-level rules — including strict age gating, content filtering, and cyberbullying safeguards.",
    iconEmoji: "🦘",
    iconUrl: "/movements/icons/australian-esafety.png",
    accentColor: "#D97706",
    rules: [
      { category: "social_media_min_age", label: "Social media age gate", value: "16+ (Australian law)", maxAge: 16 },
      { category: "age_gate", label: "Age verification", value: "Mandatory verification" },
      { category: "csam_reporting", label: "CSAM compliance", value: "Mandatory reporting" },
      { category: "social_chat_control", label: "Anti-cyberbullying", value: "Contact controls" },
      { category: "privacy_data_sharing", label: "Data sovereignty", value: "No offshore data sharing" },
    ],
    tags: ["australia", "government", "age-verification", "international", "regulation"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 1098,
    schoolCount: 0,
  },
  {
    id: "eu-better-internet-kids",
    slug: "eu-better-internet-kids",
    name: "EU BIK+ Standard",
    organization: "European Commission — BIK+ Strategy",
    organizationUrl: "https://digital-strategy.ec.europa.eu/en/policies/strategy-better-internet-kids",
    status: "beta",
    description: "European strategy for a Better Internet for Kids with age-appropriate digital services.",
    longDescription:
      "The EU Better Internet for Kids+ (BIK+) strategy is the European Commission's comprehensive framework for protecting children online while ensuring they can fully benefit from the digital world. Building on the EU's Digital Services Act and GDPR protections, BIK+ emphasizes age-appropriate design, digital literacy, and cross-border cooperation. Phosra can translate the BIK+ principles into GDPR-aligned privacy rules, age-appropriate content delivery, and transparent algorithmic controls for families who adopt this standard.",
    iconEmoji: "🇪🇺",
    iconUrl: "/movements/icons/eu-better-internet-kids.png",
    accentColor: "#1E40AF",
    rules: [
      { category: "parental_consent_gate", label: "GDPR parental consent", value: "Required under 16" },
      { category: "commercial_data_ban", label: "No child data profiling", value: "GDPR Article 8 compliance" },
      { category: "age_gate", label: "Age-appropriate design", value: "EU age verification" },
      { category: "content_rating", label: "EU content standards", value: "PEGI-aligned ratings" },
      { category: "data_deletion_request", label: "Right to erasure", value: "GDPR data deletion" },
      { category: "algorithmic_audit", label: "DSA transparency", value: "Algorithmic disclosures" },
    ],
    tags: ["eu", "international", "gdpr", "digital-services-act", "regulation", "age-appropriate-design"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 876,
    schoolCount: 0,
  },

  /* ──────────────────────────────────────────────────────────────────
   * ❼  SCHOOL-FOCUSED MOVEMENTS
   * ────────────────────────────────────────────────────────────────── */
  {
    id: "phone-free-schools",
    slug: "phone-free-schools",
    name: "Phone-Free Schools",
    organization: "Phone-Free Schools Movement",
    organizationUrl: "https://www.phonefreeschools.org",
    status: "active",
    description: "National push for phone-free school policies using Yondr pouches and platform-level enforcement.",
    longDescription:
      "The Phone-Free Schools movement has gained bipartisan political support across the US, UK, and Australia, with school districts implementing policies using Yondr magnetic pouches and platform-level restrictions. Governor Gavin Newsom signed the Phone-Free School Act in California (2024), and UNESCO recommended a global ban on smartphones in schools. With Phosra, families can extend phone-free school policies beyond the physical pouch — enforcing app and notification blocks during school hours across every connected platform.",
    iconEmoji: "🔒",
    iconUrl: "/movements/icons/phone-free-schools.png",
    accentColor: "#4338CA",
    rules: [
      { category: "time_scheduled_hours", label: "School-day lockdown", value: "8 AM–3 PM block" },
      { category: "notification_curfew", label: "Silent during school", value: "All notifications paused" },
      { category: "social_media_min_age", label: "Social media blocked", value: "During school hours" },
      { category: "content_allowlist_mode", label: "Educational only", value: "Approved apps whitelist" },
      { category: "algo_feed_control", label: "No feeds during school", value: "Disabled 8 AM–3 PM" },
    ],
    tags: ["schools", "phone-free", "education", "legislation", "focus"],
    minAge: 5,
    maxAge: 18,
    adoptionCount: 1654,
    schoolCount: 432,
  },
  {
    id: "away-for-the-day",
    slug: "away-for-the-day",
    name: "Away For The Day",
    organization: "Away For The Day",
    organizationUrl: "https://www.awayfortheday.org",
    status: "active",
    description: "Evidence-based campaign for school phone policies backed by research on academic achievement.",
    longDescription:
      "Away For The Day provides schools and parents with research-backed resources to implement phone-free school policies. Their studies show that schools banning phones see improvements in test scores, social interaction, and mental health. Unlike enforcement-only approaches, Away For The Day includes parent education and community buy-in strategies. Families using Phosra can enforce school-hour restrictions from the Away For The Day standard while getting data on how the policy impacts their child's device usage patterns.",
    iconEmoji: "📵",
    iconUrl: "/movements/icons/away-for-the-day.png",
    accentColor: "#EA580C",
    rules: [
      { category: "time_scheduled_hours", label: "School hours block", value: "Bell-to-bell restriction" },
      { category: "notification_curfew", label: "Notifications off", value: "During school hours" },
      { category: "screen_time_report", label: "Usage reporting", value: "School vs. home comparison" },
      { category: "monitoring_activity", label: "Academic monitoring", value: "During school hours" },
    ],
    tags: ["schools", "phone-free", "research-backed", "academic", "education"],
    minAge: 5,
    maxAge: 18,
    adoptionCount: 1123,
    schoolCount: 356,
  },

  /* ──────────────────────────────────────────────────────────────────
   * ❽  CHILD EXPLOITATION PREVENTION
   * ────────────────────────────────────────────────────────────────── */
  {
    id: "thorn-digital-defenders",
    slug: "thorn-digital-defenders",
    name: "Thorn Digital Defenders",
    organization: "Thorn",
    organizationUrl: "https://www.thorn.org",
    status: "active",
    description: "Technology-driven approach to defending children from online sexual exploitation.",
    longDescription:
      "Thorn, founded by Ashton Kutcher and Demi Moore, builds technology to defend children from sexual abuse and exploitation. Their tools help platforms detect CSAM (child sexual abuse material), identify victims, and disrupt trafficking networks. The Thorn Digital Defenders standard focuses on maximum protection against exploitation — strict contact controls, CSAM compliance, predator detection alerts, and image protection. With Phosra, families can enforce these critical safeguards across every connected platform.",
    iconEmoji: "🌳",
    iconUrl: "/movements/icons/thorn-digital-defenders.png",
    accentColor: "#16A34A",
    rules: [
      { category: "csam_reporting", label: "CSAM detection", value: "Platform compliance mandatory" },
      { category: "dm_restriction", label: "Contact restrictions", value: "Known contacts only", maxAge: 16 },
      { category: "monitoring_alerts", label: "Predator detection", value: "Grooming pattern alerts" },
      { category: "image_rights_minor", label: "Image protection", value: "No minor image sharing" },
      { category: "privacy_profile_visibility", label: "Hidden profiles", value: "Not discoverable by strangers" },
      { category: "social_contacts", label: "Contact approval", value: "Parent-approved contacts only" },
    ],
    tags: ["exploitation-prevention", "csam", "safety", "technology", "child-protection"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 2456,
    schoolCount: 0,
  },
  {
    id: "ncose-standard",
    slug: "ncose-standard",
    name: "NCOSE Digital Safety",
    organization: "National Center on Sexual Exploitation",
    organizationUrl: "https://endsexualexploitation.org",
    status: "beta",
    description: "Holding platforms accountable for facilitating sexual exploitation through their Dirty Dozen List.",
    longDescription:
      "The National Center on Sexual Exploitation (NCOSE) publishes the annual Dirty Dozen List naming the top 12 facilitators of sexual exploitation, pressuring companies like Twitter/X, Amazon, and Pornhub to implement stronger protections. Their standard applies the most stringent exploitation-prevention rules available — blocking access to platforms with poor safety records, enforcing strict content filtering, and requiring verified age gates. Families using Phosra can turn NCOSE's advocacy into real platform-level enforcement.",
    iconEmoji: "🚫",
    iconUrl: "/movements/icons/ncose-standard.png",
    accentColor: "#991B1B",
    rules: [
      { category: "web_category_block", label: "Block exploitation vectors", value: "Adult content, dating apps" },
      { category: "web_filter_level", label: "Maximum web filtering", value: "Strictest level" },
      { category: "age_gate", label: "Verified age gates", value: "Hard age verification" },
      { category: "csam_reporting", label: "CSAM compliance", value: "Full reporting chain" },
      { category: "content_descriptor_block", label: "Content descriptors", value: "Block sexual, violent content" },
    ],
    tags: ["exploitation-prevention", "accountability", "content-filtering", "advocacy"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 743,
    schoolCount: 0,
  },

  /* ──────────────────────────────────────────────────────────────────
   * ❾  OUTDOOR & NATURE-BASED MOVEMENTS
   * ────────────────────────────────────────────────────────────────── */
  {
    id: "1000-hours-outside",
    slug: "1000-hours-outside",
    name: "1000 Hours Outside",
    organization: "1000 Hours Outside",
    organizationUrl: "https://www.1000hoursoutside.com",
    status: "active",
    description: "Challenge families to match outdoor time with screen time — 1,000 hours per year outside.",
    longDescription:
      "1000 Hours Outside, founded by Ginny Yurich, challenges families to spend as much time outdoors as the average child spends on screens — roughly 1,000 hours per year. The movement has grown to millions of participating families worldwide. Their standard enforces screen time reciprocity: for every hour of screen time, an equal amount of outdoor or active play time is encouraged. With Phosra, families can put this into practice — daily screen limits calibrated to promote outdoor time, with scheduled device-free windows for outdoor play.",
    iconEmoji: "🌲",
    iconUrl: "/movements/icons/1000-hours-outside.png",
    accentColor: "#15803D",
    rules: [
      { category: "time_daily_limit", label: "Screen time budget", value: "Match outdoor hour-for-hour" },
      { category: "time_downtime", label: "Outdoor play windows", value: "3–6 PM device-free daily" },
      { category: "time_per_app_limit", label: "Entertainment caps", value: "Streaming/gaming limited" },
      { category: "usage_timer_notification", label: "Go outside reminders", value: "After 30 min indoors" },
      { category: "screen_time_report", label: "Indoor/outdoor balance", value: "Weekly reports" },
    ],
    tags: ["outdoor", "nature", "screen-time", "physical-activity", "wellness", "family"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 1876,
    schoolCount: 0,
  },
  {
    id: "children-nature-network",
    slug: "children-nature-network",
    name: "Children & Nature Network",
    organization: "Children & Nature Network",
    organizationUrl: "https://www.childrenandnature.org",
    status: "beta",
    description: "Richard Louv's movement connecting children with nature to combat 'Nature Deficit Disorder.'",
    longDescription:
      "The Children & Nature Network (C&NN), co-founded by Richard Louv, author of Last Child in the Woods, works to reverse 'Nature Deficit Disorder' by connecting children with the natural world. Their research shows that outdoor time reduces ADHD symptoms, improves academic performance, and builds resilience. Their standard promotes device-free outdoor time, limits indoor entertainment, and encourages family nature experiences. Families using Phosra can protect nature time with scheduled device-free blocks.",
    iconEmoji: "🍃",
    iconUrl: "/movements/icons/children-nature-network.png",
    accentColor: "#166534",
    rules: [
      { category: "time_daily_limit", label: "Indoor screen limits", value: "Reduced daily caps" },
      { category: "time_downtime", label: "Nature hours", value: "Weekend morning device-free" },
      { category: "time_scheduled_hours", label: "After-school outdoors", value: "3–5 PM device-free" },
      { category: "screen_time_report", label: "Balance tracking", value: "Screen vs nature reports" },
    ],
    tags: ["outdoor", "nature", "wellness", "research-backed", "child-development"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 567,
    schoolCount: 23,
  },

  /* ──────────────────────────────────────────────────────────────────
   * ❿  FREE-RANGE & INDEPENDENCE MOVEMENTS
   * ────────────────────────────────────────────────────────────────── */
  {
    id: "let-grow",
    slug: "let-grow",
    name: "Let Grow",
    organization: "Let Grow",
    organizationUrl: "https://letgrow.org",
    status: "active",
    description: "Promoting childhood independence and resilience by fighting overprotection — online and off.",
    longDescription:
      "Let Grow, co-founded by Lenore Skenazy (author of Free-Range Kids) and Jonathan Haidt, advocates for giving children age-appropriate independence rather than wrapping them in bubble wrap. Their philosophy applies to digital life too — not zero screens, but graduated autonomy. Their standard starts strict for younger children and progressively loosens restrictions as kids demonstrate responsibility. Phosra can support the Let Grow approach with age-adaptive rules that automatically relax as children mature.",
    iconEmoji: "🌱",
    iconUrl: "/movements/icons/let-grow.png",
    accentColor: "#65A30D",
    rules: [
      { category: "time_daily_limit", label: "Graduated time limits", value: "Relaxes with age" },
      { category: "content_rating", label: "Age-adaptive content", value: "Progressive access" },
      { category: "monitoring_activity", label: "Fading monitoring", value: "Less oversight as they age" },
      { category: "social_media_min_age", label: "Earned social access", value: "Age 13 with supervision", maxAge: 13 },
      { category: "parental_consent_gate", label: "Milestone unlocks", value: "New access at milestones" },
    ],
    tags: ["independence", "resilience", "free-range", "age-adaptive", "balanced"],
    minAge: 5,
    maxAge: 17,
    adoptionCount: 1345,
    schoolCount: 89,
  },

  /* ──────────────────────────────────────────────────────────────────
   * ⓫  DIGITAL LITERACY & EDUCATION
   * ────────────────────────────────────────────────────────────────── */
  {
    id: "mediasmarts",
    slug: "mediasmarts",
    name: "MediaSmarts",
    organization: "MediaSmarts",
    organizationUrl: "https://mediasmarts.ca",
    status: "active",
    description: "Canada's centre for digital and media literacy, promoting critical thinking about online content.",
    longDescription:
      "MediaSmarts is Canada's premier centre for digital and media literacy, providing educators and families with research-based resources to develop children's critical thinking skills around media, technology, and the internet. Their standard combines content literacy with practical protections — age-appropriate filtering paired with graduated exposure to help children develop their own judgment. Families using Phosra can adopt MediaSmarts' approach as smart filtering that teaches while it protects.",
    iconEmoji: "🍁",
    accentColor: "#DC2626",
    rules: [
      { category: "content_rating", label: "Graduated content access", value: "Age-progressive unlocking" },
      { category: "web_safesearch", label: "Guided search", value: "Safe search with learning mode" },
      { category: "web_filter_level", label: "Smart filtering", value: "Educational-priority filtering" },
      { category: "screen_time_report", label: "Usage insights", value: "Media literacy reports" },
      { category: "ai_minor_interaction", label: "AI interaction safety", value: "Age-appropriate AI access" },
    ],
    tags: ["canada", "media-literacy", "education", "digital-citizenship", "critical-thinking"],
    minAge: 3,
    maxAge: 17,
    adoptionCount: 892,
    schoolCount: 156,
  },

  /* ──────────────────────────────────────────────────────────────────
   * ⓬  LEGAL ADVOCACY
   * ────────────────────────────────────────────────────────────────── */
  {
    id: "social-media-victims-law-center",
    slug: "social-media-victims-law-center",
    name: "SMVLC Safe Platform Standard",
    organization: "Social Media Victims Law Center",
    organizationUrl: "https://socialmediavictims.org",
    status: "beta",
    description: "Legal advocacy representing families harmed by social media, setting the strictest platform safety requirements.",
    longDescription:
      "The Social Media Victims Law Center (SMVLC) represents families of children who have been harmed or died as a result of social media use, filing landmark lawsuits against Meta, TikTok, Snap, and other platforms. Their standard reflects the maximum protections that their legal cases have argued platforms should provide — the strictest possible safety configuration. Families using Phosra can apply the SMVLC standard as maximum-strength protections across all platforms.",
    iconEmoji: "⚖️",
    iconUrl: "/movements/icons/social-media-victims-law-center.png",
    accentColor: "#78350F",
    rules: [
      { category: "social_media_min_age", label: "Social media delay", value: "Until age 16", maxAge: 16 },
      { category: "algo_feed_control", label: "No algorithmic feeds", value: "Completely disabled" },
      { category: "addictive_design_control", label: "No addictive design", value: "All dark patterns blocked" },
      { category: "dm_restriction", label: "No stranger DMs", value: "Blocked entirely", maxAge: 16 },
      { category: "targeted_ad_block", label: "No targeted ads", value: "Complete ad block" },
      { category: "csam_reporting", label: "Exploitation reporting", value: "Maximum compliance" },
      { category: "notification_curfew", label: "No late-night alerts", value: "9 PM–7 AM curfew" },
    ],
    tags: ["legal", "advocacy", "maximum-protection", "social-media", "platform-accountability"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 456,
    schoolCount: 0,
  },

  /* ──────────────────────────────────────────────────────────────────
   * ⓭  SURGEON GENERAL & GOVERNMENT ADVISORIES
   * ────────────────────────────────────────────────────────────────── */
  {
    id: "us-surgeon-general-advisory",
    slug: "us-surgeon-general-advisory",
    name: "Surgeon General Advisory",
    organization: "US Surgeon General",
    organizationUrl: "https://www.hhs.gov/surgeongeneral/priorities/youth-mental-health",
    status: "active",
    description: "US Surgeon General's advisory on social media and youth mental health — translated into enforceable rules.",
    longDescription:
      "In May 2023, US Surgeon General Dr. Vivek Murthy issued an unprecedented advisory declaring social media a 'profound risk of harm' to children's mental health, followed by a 2024 call for tobacco-style warning labels on social media platforms. The advisory recommends delaying social media, limiting usage, and requiring industry accountability. With Phosra, families can turn the Surgeon General's recommendations into enforceable platform rules — not just suggestions, but real protections.",
    iconEmoji: "🏛️",
    accentColor: "#1E3A5F",
    rules: [
      { category: "social_media_min_age", label: "Delay social media", value: "Until at least 13", maxAge: 13 },
      { category: "time_daily_limit", label: "Time limits", value: "Reasonable daily caps" },
      { category: "notification_curfew", label: "Sleep protection", value: "No nighttime alerts" },
      { category: "algo_feed_control", label: "Safe feeds", value: "No harmful amplification" },
      { category: "privacy_data_sharing", label: "Data protection", value: "Minimize collection" },
      { category: "screen_time_report", label: "Transparency tools", value: "Usage reporting for families" },
    ],
    tags: ["government", "mental-health", "social-media", "advisory", "us", "official"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 3678,
    schoolCount: 0,
  },

  /* ──────────────────────────────────────────────────────────────────
   * ⓮  EVENTS & AWARENESS CAMPAIGNS
   * ────────────────────────────────────────────────────────────────── */
  {
    id: "screen-free-week",
    slug: "screen-free-week",
    name: "Screen-Free Week",
    organization: "Fairplay",
    organizationUrl: "https://fairplayforkids.org/screen-free-week",
    status: "coming_soon",
    description: "Annual celebration where families, schools, and communities swap screen time for creative play.",
    longDescription:
      "Screen-Free Week (formerly TV Turnoff Week) is an annual international event organized by Fairplay where families, schools, and communities unplug from entertainment screens for seven days and rediscover play, nature, and face-to-face connection. Families using Phosra can adopt Screen-Free Week as a time-limited standard that automatically activates during the event week — enforcing strict entertainment blocks while still allowing educational and communication tools.",
    iconEmoji: "🎉",
    iconUrl: "/movements/icons/screen-free-week.png",
    accentColor: "#A855F7",
    rules: [
      { category: "time_daily_limit", label: "Entertainment blackout", value: "0 min entertainment screens" },
      { category: "content_allowlist_mode", label: "Essential apps only", value: "Communication & education only" },
      { category: "time_per_app_limit", label: "Gaming blocked", value: "All games disabled" },
      { category: "algo_feed_control", label: "Social feeds off", value: "All feeds disabled" },
    ],
    tags: ["event", "awareness", "screen-free", "annual", "community", "unplugging"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 0,
    schoolCount: 0,
  },
]
