import type { StandardEntry } from "./types"

export const STANDARDS_REGISTRY: StandardEntry[] = [
  {
    id: "four-norms",
    slug: "four-norms",
    name: "Four Norms",
    organization: "The Anxious Generation",
    organizationUrl: "https://www.anxiousgeneration.com",
    status: "active",
    description: "Jonathan Haidt's four foundational norms for a phone-free childhood.",
    longDescription:
      "Based on The Anxious Generation by Jonathan Haidt, the Four Norms represent a research-backed framework for protecting children from the harms of smartphone-based childhood. When adopted through Phosra, these norms are automatically translated into enforceable rules across every connected platform — turning a social pledge into verified, cross-platform protection.",
    iconEmoji: "📱",
    accentColor: "#E85D3A",
    rules: [
      { category: "social_media_min_age", label: "No social media", value: "Until age 16", maxAge: 16 },
      { category: "privacy_account_creation", label: "No smartphones", value: "Until age 14", maxAge: 14 },
      { category: "time_scheduled_hours", label: "Phone-free schools", value: "School hours blocked" },
      { category: "time_daily_limit", label: "More outdoor play", value: "120 min/day minimum" },
    ],
    tags: ["mental-health", "phone-free", "schools", "social-media"],
    minAge: 0,
    maxAge: 16,
    adoptionCount: 2847,
    schoolCount: 142,
  },
  {
    id: "wait-until-8th",
    slug: "wait-until-8th",
    name: "Wait Until 8th",
    organization: "Wait Until 8th",
    organizationUrl: "https://www.waituntil8th.org",
    status: "active",
    description: "A community pledge to delay smartphones until at least 8th grade.",
    longDescription:
      "Wait Until 8th is a grassroots movement of over 130,000 families who pledge to wait until at least 8th grade before giving their children a smartphone. When enforced through Phosra, this pledge becomes real at the device level — restricting smartphone app access, social media, and mature content across all connected platforms until the child reaches 8th grade age.",
    iconEmoji: "✋",
    accentColor: "#4A90D9",
    rules: [
      { category: "privacy_account_creation", label: "No smartphone apps", value: "Until 8th grade (~14)", maxAge: 14 },
      { category: "social_media_min_age", label: "No social media", value: "Until 8th grade", maxAge: 14 },
      { category: "content_rating", label: "Age-appropriate content", value: "Strict filtering" },
      { category: "web_filter_level", label: "Web filtering", value: "Strict" },
      { category: "monitoring_activity", label: "Activity monitoring", value: "Enabled" },
    ],
    tags: ["smartphone-delay", "pledge", "community", "grassroots"],
    minAge: 0,
    maxAge: 14,
    adoptionCount: 4213,
    schoolCount: 287,
  },
  {
    id: "screen-smart-family",
    slug: "screen-smart-family",
    name: "Screen-Smart Family",
    organization: "Phosra",
    status: "active",
    description: "Phosra's recommended baseline for balanced screen time and online safety.",
    longDescription:
      "The Screen-Smart Family standard is Phosra's own curated best-practice ruleset, designed by child development experts and informed by current legislation (KOSA, COPPA 2.0). It provides a balanced, age-adaptive approach to screen time, content filtering, and privacy — automatically adjusting rules as your child grows.",
    iconEmoji: "🛡️",
    accentColor: "#00D47E",
    rules: [
      { category: "time_daily_limit", label: "Daily screen time", value: "Age-adaptive limits" },
      { category: "content_rating", label: "Content ratings", value: "Age-appropriate" },
      { category: "web_safesearch", label: "Safe search", value: "Enforced" },
      { category: "social_chat_control", label: "Chat controls", value: "Known contacts only" },
      { category: "purchase_approval", label: "Purchase approval", value: "Required" },
      { category: "privacy_data_sharing", label: "Data sharing", value: "Minimal" },
    ],
    tags: ["balanced", "recommended", "phosra", "best-practice"],
    minAge: 0,
    maxAge: 17,
    adoptionCount: 6502,
    schoolCount: 0,
  },
  {
    id: "screen-free-schools",
    slug: "screen-free-schools",
    name: "Screen-Free Schools",
    organization: "Screen Time Action Network",
    organizationUrl: "https://screentimenetwork.org",
    status: "coming_soon",
    description: "Comprehensive device restrictions during school hours for focused learning.",
    longDescription:
      "The Screen-Free Schools standard enforces phone-free policies during school hours, blocking social media, gaming, and non-educational content during the school day. Designed for school-wide adoption, it activates when 10 or more families in a grade level adopt it — creating community-wide accountability for distraction-free learning.",
    iconEmoji: "🏫",
    accentColor: "#7B5CB8",
    rules: [
      { category: "time_scheduled_hours", label: "School hours", value: "All non-educational blocked" },
      { category: "social_media_min_age", label: "Social media", value: "Blocked during school" },
      { category: "notification_curfew", label: "Notifications", value: "Silenced during school" },
      { category: "algo_feed_control", label: "Algorithmic feeds", value: "Disabled during school" },
    ],
    tags: ["schools", "education", "phone-free", "focus"],
    minAge: 5,
    maxAge: 18,
    adoptionCount: 0,
    schoolCount: 0,
  },
]
