#!/usr/bin/env npx tsx
/**
 * Generates static-research-context.ts from the live filesystem research data.
 * Run this before deploying so the chat widget works on Vercel where the
 * research data directory is not available at runtime.
 *
 * Usage: cd web && npx tsx scripts/generate-chat-context.mts
 */
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import { register } from "module"

const __dirname = path.dirname(fileURLToPath(import.meta.url))

async function main() {
  // Use dynamic import with tsx's path resolution — call via the
  // Next.js-style alias by setting up the tsconfig paths
  const mod = await import("../src/lib/platform-research/chat-context.ts")
  const ctx: string = await mod.buildResearchContext()
  const output =
    "// Auto-generated by scripts/generate-chat-context.mts — do not edit\nexport const STATIC_RESEARCH_CONTEXT = " +
    JSON.stringify(ctx) +
    ";\n"
  const outPath = path.resolve(
    __dirname,
    "../src/lib/platform-research/static-research-context.ts"
  )
  fs.writeFileSync(outPath, output, "utf-8")
  console.log(
    `Wrote ${(output.length / 1024).toFixed(1)} KB to ${path.relative(process.cwd(), outPath)}`
  )
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
