"use client"

import { AGE_RATING_TABLE, AGE_DEFAULTS_TABLE } from "@/lib/docs/ratings"

function Keyword({ children }: { children: string }) {
  return <strong className="text-brand-green font-bold">{children}</strong>
}

export function RatingsBrowser() {
  return (
    <div className="space-y-12">
      {/* Age-to-Rating Standard */}
      <section>
        <h2 className="text-xl font-bold text-foreground mb-4">Age-to-Rating Standard</h2>
        <p className="text-sm text-muted-foreground mb-4">Platforms <Keyword>MUST</Keyword> use the following age-to-rating mappings when computing content restrictions. Used by <code className="bg-muted px-1 rounded text-xs text-foreground">GET /ratings/by-age</code> and <code className="bg-muted px-1 rounded text-xs text-foreground">POST /policies/:id/generate-from-age</code>.</p>
        <div className="bg-card rounded border border-border overflow-x-auto -mx-4 sm:mx-0">
          <table className="w-full text-sm min-w-[500px]">
            <thead><tr className="bg-muted/50"><th className="px-3 sm:px-4 py-3 text-left text-xs text-muted-foreground">Age</th><th className="px-3 sm:px-4 py-3 text-center text-xs text-muted-foreground">MPAA</th><th className="px-3 sm:px-4 py-3 text-center text-xs text-muted-foreground">TV</th><th className="px-3 sm:px-4 py-3 text-center text-xs text-muted-foreground">ESRB</th><th className="px-3 sm:px-4 py-3 text-center text-xs text-muted-foreground">PEGI</th><th className="px-3 sm:px-4 py-3 text-center text-xs text-muted-foreground">CSM</th></tr></thead>
            <tbody className="divide-y divide-border">
              {AGE_RATING_TABLE.map((row) => (
                <tr key={row.range} className="hover:bg-muted/30 transition-colors">
                  <td className="px-4 py-3 font-medium text-foreground">{row.range}</td>
                  <td className="px-4 py-3 text-center"><span className="bg-blue-100 text-blue-700 dark:bg-blue-500/20 dark:text-blue-400 px-2 py-0.5 rounded text-xs font-medium">{row.mpaa}</span></td>
                  <td className="px-4 py-3 text-center"><span className="bg-purple-100 text-purple-700 dark:bg-purple-500/20 dark:text-purple-400 px-2 py-0.5 rounded text-xs font-medium">{row.tv}</span></td>
                  <td className="px-4 py-3 text-center"><span className="bg-emerald-100 text-emerald-700 dark:bg-emerald-500/20 dark:text-emerald-400 px-2 py-0.5 rounded text-xs font-medium">{row.esrb}</span></td>
                  <td className="px-4 py-3 text-center"><span className="bg-orange-100 text-orange-700 dark:bg-orange-500/20 dark:text-orange-400 px-2 py-0.5 rounded text-xs font-medium">{row.pegi}</span></td>
                  <td className="px-4 py-3 text-center"><span className="bg-pink-100 text-pink-700 dark:bg-pink-500/20 dark:text-pink-400 px-2 py-0.5 rounded text-xs font-medium">{row.csm}</span></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* Age-Based Default Policies */}
      <section>
        <h2 className="text-xl font-bold text-foreground mb-4">Age-Based Default Policies</h2>
        <p className="text-sm text-muted-foreground mb-4">
          Default policy values generated by <code className="bg-muted px-1 rounded text-xs text-foreground">POST /policies/:id/generate-from-age</code> and the Quick Setup API.
          These defaults represent the &quot;recommended&quot; strictness level. Values are computed from the child&apos;s age at policy creation time.
        </p>
        <div className="bg-card rounded border border-border overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-muted/50">
                <th className="px-4 py-3 text-left text-xs text-muted-foreground whitespace-nowrap">Setting</th>
                <th className="px-4 py-3 text-center text-xs text-muted-foreground">0-6</th>
                <th className="px-4 py-3 text-center text-xs text-muted-foreground">7-9</th>
                <th className="px-4 py-3 text-center text-xs text-muted-foreground">10-12</th>
                <th className="px-4 py-3 text-center text-xs text-muted-foreground">13-16</th>
                <th className="px-4 py-3 text-center text-xs text-muted-foreground">17+</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {AGE_DEFAULTS_TABLE.map(row => (
                <tr key={row.key} className="hover:bg-muted/30 transition-colors">
                  <td className="px-4 py-3 font-medium text-foreground whitespace-nowrap">
                    {row.setting}
                  </td>
                  {row.values.map((val, i) => (
                    <td key={i} className="px-4 py-3 text-center text-xs text-muted-foreground whitespace-nowrap">{val}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  )
}
