import type { ParentalControlEntry } from "./types"

export const PARENTAL_CONTROLS_REGISTRY: ParentalControlEntry[] = [
  // ─────────────────────────────────────────────────────────────────
  // PARENTAL APPS
  // ─────────────────────────────────────────────────────────────────

  {
    id: "bark",
    slug: "bark",
    name: "Bark",
    description:
      "AI-powered monitoring that scans texts, emails, and 30+ social media platforms for signs of cyberbullying, depression, suicidal ideation, and online predators.",
    longDescription:
      "Bark uses advanced machine learning to analyze children's online activity across texts, emails, YouTube, and more than 30 social media platforms. Rather than logging every message, Bark surfaces only the interactions that indicate potential dangers — cyberbullying, explicit content, signs of depression, suicidal ideation, and online predators. Parents receive real-time alerts with recommended actions, keeping kids safe without invading every private conversation. Bark also offers web filtering, screen time scheduling, and location tracking.",
    website: "https://www.bark.us",
    iconEmoji: "\uD83D\uDC15",
    accentColor: "#5C6BC0",
    sourceCategory: "parental_apps",
    pricingTier: "freemium",
    pricingDetails:
      "Bark Jr (free) covers basic monitoring. Bark Premium starts at $14/mo or $99/yr and includes full monitoring, screen time management, and location tracking.",
    apiAvailability: "partner_api",
    apiDetails:
      "Bark offers a documented API for managed device platforms and school districts. Access may require an integration agreement.",
    devices: {
      iOS: true,
      android: true,
      windows: false,
      macOS: false,
      chromeos: true,
      fireos: false,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "monitoring_activity", label: "Activity Monitoring", support: "full" },
      { category: "monitoring_alerts", label: "Smart Alerts", support: "full" },
      { category: "monitoring_location", label: "Location Tracking", support: "full" },
      { category: "web_filter_level", label: "Web Filtering", support: "full" },
      { category: "web_category_block", label: "Category Blocking", support: "full" },
      { category: "web_safesearch", label: "Safe Search Enforcement", support: "full" },
      { category: "time_scheduled_hours", label: "Screen Time Scheduling", support: "full" },
      { category: "time_daily_limit", label: "Daily Time Limits", support: "full" },
      { category: "social_chat_control", label: "Chat Monitoring", support: "full" },
      { category: "social_media_min_age", label: "Social Media Age Gating", support: "full" },
      { category: "dm_restriction", label: "DM Restriction", support: "full" },
      { category: "content_rating", label: "Content Rating Enforcement", support: "full" },
      { category: "notification_curfew", label: "Notification Curfew", support: "full" },
    ],
    minAge: 4,
    maxAge: 17,
    tags: ["ai-monitoring", "social-media", "cyberbullying", "alerts", "school-integration"],
    featured: true,
  },

  {
    id: "qustodio",
    slug: "qustodio",
    name: "Qustodio",
    description:
      "Comprehensive cross-platform parental control with real-time web filtering, screen time management, app controls, and detailed activity reports across every major device.",
    longDescription:
      "Qustodio is one of the most widely used parental control platforms, offering a unified dashboard to manage children's digital lives across Windows, macOS, iOS, Android, ChromeOS, and Kindle. It provides real-time web filtering with 30+ content categories, per-app time limits, YouTube monitoring, social media tracking, location tracking, and SOS panic button functionality. Detailed daily and weekly reports give parents clear visibility into browsing habits and app usage without overwhelming them with raw data.",
    website: "https://www.qustodio.com",
    iconEmoji: "\uD83D\uDEE1\uFE0F",
    accentColor: "#00A8E8",
    sourceCategory: "parental_apps",
    pricingTier: "freemium",
    pricingDetails:
      "Free plan covers 1 device with basic features. Premium Small ($54.95/yr) covers 5 devices; Premium Medium ($96.95/yr) covers 10; Premium Large ($137.95/yr) covers 15.",
    apiAvailability: "public_api",
    apiDetails:
      "Qustodio provides a documented REST API for integrators and enterprise customers. Endpoints cover device management, rule configuration, and activity reports.",
    devices: {
      iOS: true,
      android: true,
      windows: true,
      macOS: true,
      chromeos: true,
      fireos: true,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "time_daily_limit", label: "Daily Time Limits", support: "full" },
      { category: "time_scheduled_hours", label: "Scheduled Hours", support: "full" },
      { category: "time_per_app_limit", label: "Per-App Time Limits", support: "full" },
      { category: "time_downtime", label: "Device Downtime", support: "full" },
      { category: "web_filter_level", label: "Web Filtering", support: "full" },
      { category: "web_category_block", label: "Category Blocking", support: "full" },
      { category: "web_safesearch", label: "Safe Search Enforcement", support: "full" },
      { category: "monitoring_activity", label: "Activity Reports", support: "full" },
      { category: "monitoring_alerts", label: "Real-Time Alerts", support: "full" },
      { category: "monitoring_location", label: "Location Tracking", support: "full" },
      { category: "social_media_min_age", label: "Social Media Monitoring", support: "full" },
      { category: "content_rating", label: "Content Rating Enforcement", support: "full" },
      { category: "purchase_approval", label: "Purchase Approval", support: "full" },
    ],
    minAge: 3,
    maxAge: 17,
    tags: ["cross-platform", "web-filtering", "screen-time", "reports", "location"],
    featured: true,
  },

  {
    id: "net-nanny",
    slug: "net-nanny",
    name: "Net Nanny",
    description:
      "The original web filtering solution with over 25 years of experience, offering AI-powered real-time content analysis, screen time management, and app blocking.",
    longDescription:
      "Net Nanny has been a pioneer in web filtering since 1995 and continues to evolve with AI-powered content classification that analyzes web pages in real-time rather than relying solely on static blocklists. It offers customizable filtering profiles per child, screen time management, app blocking, profanity masking, and pornography blocking. The family feed provides a consolidated view of all children's online activity. While it lacks a public API, its mature filtering engine is widely regarded as one of the most accurate in the industry.",
    website: "https://www.netnanny.com",
    iconEmoji: "\uD83D\uDC69\u200D\uD83D\uDCBB",
    accentColor: "#2E7D32",
    sourceCategory: "parental_apps",
    pricingTier: "paid",
    pricingDetails:
      "Single device plan at $39.99/yr. Family plan (5 devices) at $54.99/yr. Family plan (20 devices) at $89.99/yr.",
    apiAvailability: "no_api",
    devices: {
      iOS: true,
      android: true,
      windows: true,
      macOS: true,
      chromeos: false,
      fireos: false,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "web_filter_level", label: "Web Filtering", support: "full" },
      { category: "web_category_block", label: "Category Blocking", support: "full" },
      { category: "web_safesearch", label: "Safe Search Enforcement", support: "full" },
      { category: "content_rating", label: "Content Rating Enforcement", support: "full" },
      { category: "time_daily_limit", label: "Daily Time Limits", support: "full" },
      { category: "time_scheduled_hours", label: "Scheduled Hours", support: "full" },
      { category: "time_per_app_limit", label: "Per-App Time Limits", support: "full" },
      { category: "monitoring_activity", label: "Activity Reports", support: "full" },
      { category: "monitoring_alerts", label: "Alert Notifications", support: "full" },
      { category: "monitoring_location", label: "Location Tracking", support: "full" },
      { category: "social_media_min_age", label: "Social Media Monitoring", support: "full" },
      { category: "notification_curfew", label: "Notification Curfew", support: "full" },
    ],
    minAge: 3,
    maxAge: 17,
    tags: ["web-filtering", "ai-content-analysis", "screen-time", "profanity-masking"],
    featured: true,
  },

  {
    id: "norton-family",
    slug: "norton-family",
    name: "Norton Family",
    description:
      "Norton's parental control solution with web supervision, time management, search monitoring, and location tracking backed by NortonLifeLock's threat intelligence.",
    longDescription:
      "Norton Family leverages NortonLifeLock's decades of cybersecurity expertise to provide parents with web supervision, time management, instant lock, search monitoring, video supervision, mobile app supervision, and location tracking. It integrates seamlessly with Norton 360 subscriptions, making it an attractive choice for families already in the Norton ecosystem. The school time feature lets parents restrict device usage to educational sites during school hours. Norton Family excels at web filtering accuracy thanks to Norton's massive URL classification database.",
    website: "https://family.norton.com",
    iconEmoji: "\uD83D\uDD12",
    accentColor: "#FFC107",
    sourceCategory: "parental_apps",
    pricingTier: "freemium",
    pricingDetails:
      "Included with Norton 360 Deluxe ($49.99/yr) and Premium ($109.99/yr) subscriptions. Standalone Norton Family Premier at $49.99/yr.",
    apiAvailability: "no_api",
    devices: {
      iOS: true,
      android: true,
      windows: true,
      macOS: false,
      chromeos: false,
      fireos: false,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "web_filter_level", label: "Web Supervision", support: "full" },
      { category: "web_category_block", label: "Category Blocking", support: "full" },
      { category: "web_safesearch", label: "Search Monitoring", support: "full" },
      { category: "time_daily_limit", label: "Daily Time Limits", support: "full" },
      { category: "time_scheduled_hours", label: "School Time Scheduling", support: "full" },
      { category: "time_downtime", label: "Instant Lock", support: "full" },
      { category: "monitoring_activity", label: "Activity Reports", support: "full" },
      { category: "monitoring_alerts", label: "Rule Violation Alerts", support: "full" },
      { category: "monitoring_location", label: "Location Tracking", support: "full" },
      { category: "content_rating", label: "Video Supervision", support: "full" },
      { category: "social_media_min_age", label: "Social Media Monitoring", support: "full" },
      { category: "privacy_data_sharing", label: "Data Sharing Controls", support: "full" },
    ],
    minAge: 4,
    maxAge: 17,
    tags: ["norton", "web-supervision", "school-time", "video-monitoring", "location"],
    featured: false,
  },

  {
    id: "bark-phone",
    slug: "bark-phone",
    name: "Bark Phone",
    description:
      "A dedicated kid-safe smartphone from the makers of Bark, with parental controls baked into the device firmware for monitoring, filtering, and contact management.",
    longDescription:
      "Bark Phone is a Samsung smartphone preconfigured with Bark's full suite of parental controls built directly into the device at the operating system level. Unlike app-based solutions that can be circumvented, Bark Phone's controls are embedded in the firmware, covering contact approval, app management, screen time, location tracking, and content monitoring. Parents manage everything from the Bark dashboard. The phone comes in three preset configurations — starter (no social media, no browser), intermediate, and advanced — making it easy to gradually grant more access as kids demonstrate responsibility.",
    website: "https://www.bark.us/bark-phone",
    iconEmoji: "\uD83D\uDCF1",
    accentColor: "#7E57C2",
    sourceCategory: "parental_apps",
    pricingTier: "paid",
    pricingDetails:
      "Monthly plans starting at $49/mo (includes device, cellular plan, and Bark Premium). No upfront device cost.",
    apiAvailability: "partner_api",
    apiDetails:
      "Inherits Bark's managed API capabilities. Device-level controls are managed through the Bark platform.",
    devices: {
      iOS: false,
      android: true,
      windows: false,
      macOS: false,
      chromeos: false,
      fireos: false,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "monitoring_activity", label: "Activity Monitoring", support: "full" },
      { category: "monitoring_alerts", label: "AI-Powered Alerts", support: "full" },
      { category: "monitoring_location", label: "Location Tracking", support: "full" },
      { category: "web_filter_level", label: "Web Filtering", support: "full" },
      { category: "web_category_block", label: "Category Blocking", support: "full" },
      { category: "web_safesearch", label: "Safe Search Enforcement", support: "full" },
      { category: "time_daily_limit", label: "Daily Time Limits", support: "full" },
      { category: "time_scheduled_hours", label: "Screen Time Scheduling", support: "full" },
      { category: "time_per_app_limit", label: "Per-App Time Limits", support: "full" },
      { category: "social_chat_control", label: "Contact Approval", support: "full" },
      { category: "dm_restriction", label: "DM Restrictions", support: "full" },
      { category: "content_rating", label: "App Approval", support: "full" },
      { category: "privacy_account_creation", label: "Account Creation Control", support: "full" },
    ],
    minAge: 6,
    maxAge: 16,
    tags: ["dedicated-phone", "firmware-controls", "bark-ecosystem", "contact-management"],
    featured: true,
  },

  {
    id: "canopy",
    slug: "canopy",
    name: "Canopy",
    description:
      "AI-based content filtering that blocks explicit images and videos in real-time on the device without taking screenshots or logging private messages.",
    longDescription:
      "Canopy takes a privacy-first approach to parental controls by using on-device AI to detect and block explicit images and videos in real-time — across any app, browser, or messaging platform — without ever taking screenshots, reading message content, or sending private data to the cloud. This makes it one of the few solutions that can filter content inside encrypted messaging apps like iMessage and WhatsApp while respecting the child's textual privacy. Canopy also provides web filtering, sexting prevention, and screen time management.",
    website: "https://canopy.us",
    iconEmoji: "\uD83C\uDF3F",
    accentColor: "#43A047",
    sourceCategory: "parental_apps",
    pricingTier: "paid",
    pricingDetails:
      "Plans start at $7.99/mo or $71.99/yr per family (up to 10 devices).",
    apiAvailability: "no_api",
    devices: {
      iOS: true,
      android: true,
      windows: false,
      macOS: false,
      chromeos: false,
      fireos: false,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "content_rating", label: "Visual Content Filtering", support: "full" },
      { category: "web_filter_level", label: "Web Filtering", support: "full" },
      { category: "web_category_block", label: "Category Blocking", support: "full" },
      { category: "web_safesearch", label: "Safe Search Enforcement", support: "full" },
      { category: "time_daily_limit", label: "Daily Time Limits", support: "full" },
      { category: "time_scheduled_hours", label: "Screen Time Scheduling", support: "full" },
      { category: "dm_restriction", label: "Sexting Prevention", support: "full" },
      { category: "monitoring_alerts", label: "Alert Notifications", support: "full" },
      { category: "monitoring_activity", label: "Activity Reports", support: "full" },
      { category: "social_chat_control", label: "Chat Content Filtering", support: "full" },
      { category: "privacy_data_sharing", label: "Privacy-First Design", support: "full" },
    ],
    minAge: 5,
    maxAge: 17,
    tags: ["ai-filtering", "privacy-first", "no-screenshots", "sexting-prevention", "encrypted-apps"],
    featured: false,
  },

  {
    id: "securly",
    slug: "securly",
    name: "Securly",
    description:
      "Cloud-based student safety platform trusted by over 20,000 schools, extending AI-powered web filtering and wellness monitoring from the classroom to home.",
    longDescription:
      "Securly is the most widely deployed student safety solution in K-12 education, protecting over 20 million students across more than 20,000 schools. Its cloud-based platform provides AI-powered web filtering, real-time threat detection, student wellness monitoring (detecting self-harm and bullying signals), and device management. Securly Home extends school-level protections to home networks, giving parents the same visibility and control outside school hours. The platform integrates with Google Workspace and Microsoft 365 for Education, and its tip line feature lets students anonymously report safety concerns.",
    website: "https://www.securly.com",
    iconEmoji: "\uD83C\uDFEB",
    accentColor: "#1565C0",
    sourceCategory: "parental_apps",
    pricingTier: "paid",
    pricingDetails:
      "Enterprise pricing for schools (per-student licensing). Securly Home is included for parents of enrolled students at no additional cost.",
    apiAvailability: "partner_api",
    apiDetails:
      "Securly provides documented APIs for SIS integration, Google Workspace, and Microsoft 365 for Education environments.",
    devices: {
      iOS: true,
      android: true,
      windows: true,
      macOS: false,
      chromeos: true,
      fireos: false,
      router: false,
      browser_extension: true,
    },
    capabilities: [
      { category: "web_filter_level", label: "AI Web Filtering", support: "full" },
      { category: "web_category_block", label: "Category Blocking", support: "full" },
      { category: "web_safesearch", label: "Safe Search Enforcement", support: "full" },
      { category: "monitoring_activity", label: "Activity Reports", support: "full" },
      { category: "monitoring_alerts", label: "Wellness Alerts", support: "full" },
      { category: "time_daily_limit", label: "Daily Time Limits", support: "full" },
      { category: "time_scheduled_hours", label: "School Time Scheduling", support: "full" },
      { category: "content_rating", label: "Content Classification", support: "full" },
      { category: "social_chat_control", label: "Messaging Monitoring", support: "full" },
      { category: "monitoring_location", label: "Device Location", support: "full" },
      { category: "privacy_data_sharing", label: "COPPA/FERPA Compliance", support: "full" },
    ],
    minAge: 5,
    maxAge: 18,
    tags: ["school", "k-12", "student-safety", "wellness", "chromebook", "google-workspace"],
    featured: false,
  },

  {
    id: "mobicip",
    slug: "mobicip",
    name: "Mobicip",
    description:
      "Cloud-based parental control with smart internet filtering, screen time management, app blocking, and cross-platform family monitoring dashboards.",
    longDescription:
      "Mobicip provides a comprehensive, cloud-managed parental control experience across iOS, Android, Windows, macOS, ChromeOS, and Kindle Fire. Its smart internet filter uses AI to categorize websites in real-time, going beyond static blocklists to handle new and unclassified sites. Parents get granular screen time controls with daily schedules, per-app limits, and homework time modes. The unified dashboard makes it easy to manage multiple children across different devices, with detailed usage reports and instant alerts for policy violations.",
    website: "https://www.mobicip.com",
    iconEmoji: "\u2601\uFE0F",
    accentColor: "#0288D1",
    sourceCategory: "parental_apps",
    pricingTier: "freemium",
    pricingDetails:
      "Free plan covers 1 device with basic filtering. Standard plan ($39.99/yr) covers 5 devices. Premium plan ($59.99/yr) covers 20 devices with full features.",
    apiAvailability: "no_api",
    devices: {
      iOS: true,
      android: true,
      windows: true,
      macOS: true,
      chromeos: true,
      fireos: false,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "web_filter_level", label: "Smart Web Filtering", support: "full" },
      { category: "web_category_block", label: "Category Blocking", support: "full" },
      { category: "web_safesearch", label: "Safe Search Enforcement", support: "full" },
      { category: "time_daily_limit", label: "Daily Time Limits", support: "full" },
      { category: "time_scheduled_hours", label: "Scheduled Hours", support: "full" },
      { category: "time_per_app_limit", label: "Per-App Time Limits", support: "full" },
      { category: "time_downtime", label: "Homework Mode", support: "full" },
      { category: "monitoring_activity", label: "Activity Reports", support: "full" },
      { category: "monitoring_alerts", label: "Instant Alerts", support: "full" },
      { category: "monitoring_location", label: "Location Tracking", support: "full" },
      { category: "content_rating", label: "Content Rating Enforcement", support: "full" },
      { category: "social_media_min_age", label: "Social Media Monitoring", support: "full" },
    ],
    minAge: 3,
    maxAge: 17,
    tags: ["cloud-based", "cross-platform", "smart-filtering", "homework-mode", "family-dashboard"],
    featured: false,
  },

  {
    id: "ourpact",
    slug: "ourpact",
    name: "OurPact",
    description:
      "Screen time scheduler and app blocker that lets parents grant, block, and schedule access to apps and the internet with a single tap.",
    longDescription:
      "OurPact focuses on simplicity, giving parents an intuitive one-tap interface to instantly block or grant access to all apps and the internet on their child's device. Its scheduling engine allows parents to create recurring daily routines — school time, homework time, bedtime — that automatically restrict or allow device access. The app also offers geofencing with location-based alerts, website blocking, daily screen time allowances, and a gallery viewer for monitoring photos. OurPact is particularly popular among parents of younger children who want straightforward controls without complex configuration.",
    website: "https://ourpact.com",
    iconEmoji: "\uD83E\uDD1D",
    accentColor: "#E91E63",
    sourceCategory: "parental_apps",
    pricingTier: "freemium",
    pricingDetails:
      "Free plan covers 1 device with basic blocking. OurPact Plus ($6.99/mo) adds scheduling and web filtering. OurPact Premium ($9.99/mo) adds location tracking and gallery viewer.",
    apiAvailability: "no_api",
    devices: {
      iOS: true,
      android: true,
      windows: false,
      macOS: false,
      chromeos: false,
      fireos: false,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "time_scheduled_hours", label: "Screen Time Scheduling", support: "full" },
      { category: "time_daily_limit", label: "Daily Allowances", support: "full" },
      { category: "time_downtime", label: "Instant Block/Grant", support: "full" },
      { category: "web_filter_level", label: "Website Blocking", support: "full" },
      { category: "web_category_block", label: "Category Blocking", support: "full" },
      { category: "monitoring_location", label: "Geofencing & Location", support: "full" },
      { category: "monitoring_activity", label: "App Usage Reports", support: "full" },
      { category: "monitoring_alerts", label: "Geofence Alerts", support: "full" },
      { category: "content_rating", label: "App Blocking", support: "full" },
      { category: "time_per_app_limit", label: "Per-App Blocking", support: "full" },
      { category: "notification_curfew", label: "Notification Curfew", support: "full" },
    ],
    minAge: 3,
    maxAge: 16,
    tags: ["simple", "one-tap", "scheduling", "geofencing", "app-blocking"],
    featured: false,
  },

  {
    id: "kidslox",
    slug: "kidslox",
    name: "Kidslox",
    description:
      "Simple, family-friendly screen time controls with daily limits, scheduled access, app blocking, and a shared family PIN system.",
    longDescription:
      "Kidslox is designed for parents who want effective screen time controls without a steep learning curve. It offers three simple modes — Lock (blocks everything), Schedule (follows a timed routine), and Free (full access) — that parents can toggle with a tap. Daily screen time limits count down in real-time, and kids can see their remaining time. Kidslox also provides web filtering, app blocking, YouTube monitoring, and a family PIN system so both parents can manage controls from their own devices. The clean interface and straightforward setup make it an excellent choice for non-technical families.",
    website: "https://kidslox.com",
    iconEmoji: "\uD83E\uDDD2",
    accentColor: "#FF7043",
    sourceCategory: "parental_apps",
    pricingTier: "freemium",
    pricingDetails:
      "Free trial for 14 days. Annual plan at $59.99/yr or lifetime purchase at $99.99, covering unlimited devices per family.",
    apiAvailability: "no_api",
    devices: {
      iOS: true,
      android: true,
      windows: false,
      macOS: false,
      chromeos: false,
      fireos: false,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "time_daily_limit", label: "Daily Time Limits", support: "full" },
      { category: "time_scheduled_hours", label: "Screen Time Scheduling", support: "full" },
      { category: "time_downtime", label: "Instant Lock Mode", support: "full" },
      { category: "web_filter_level", label: "Web Filtering", support: "full" },
      { category: "web_category_block", label: "Category Blocking", support: "full" },
      { category: "content_rating", label: "App Blocking", support: "full" },
      { category: "monitoring_activity", label: "Usage Reports", support: "full" },
      { category: "web_safesearch", label: "Safe Search Enforcement", support: "full" },
      { category: "time_per_app_limit", label: "Per-App Blocking", support: "full" },
      { category: "monitoring_alerts", label: "Limit Reached Alerts", support: "full" },
    ],
    minAge: 3,
    maxAge: 16,
    tags: ["simple", "screen-time", "family-friendly", "three-modes", "unlimited-devices"],
    featured: false,
  },

  {
    id: "mmguardian",
    slug: "mmguardian",
    name: "MMGuardian",
    description:
      "Monitoring and protection app with call and SMS control, app supervision, web filtering, and real-time location tracking for Android and iOS.",
    longDescription:
      "MMGuardian provides a comprehensive suite of monitoring tools focused on communication safety. It can filter and monitor phone calls and text messages (including detecting images), block unknown contacts, and provide detailed logs of all communication activity. Beyond messaging controls, MMGuardian offers web filtering, app management (block, allow, or set time limits per app), screen time scheduling, and real-time GPS location tracking with geofencing. Its strength lies in deep Android integration that provides visibility into SMS and call activity that most competing apps cannot match.",
    website: "https://www.mmguardian.com",
    iconEmoji: "\uD83D\uDC41\uFE0F",
    accentColor: "#546E7A",
    sourceCategory: "parental_apps",
    pricingTier: "paid",
    pricingDetails:
      "Annual plans: Basic ($34.99/yr for 1 device), Standard ($49.99/yr for 3 devices), Premium ($69.99/yr for 5 devices).",
    apiAvailability: "no_api",
    devices: {
      iOS: true,
      android: true,
      windows: false,
      macOS: false,
      chromeos: false,
      fireos: false,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "social_chat_control", label: "SMS/Call Monitoring", support: "full" },
      { category: "dm_restriction", label: "Contact Blocking", support: "full" },
      { category: "monitoring_activity", label: "Activity Monitoring", support: "full" },
      { category: "monitoring_alerts", label: "Real-Time Alerts", support: "full" },
      { category: "monitoring_location", label: "GPS Location Tracking", support: "full" },
      { category: "web_filter_level", label: "Web Filtering", support: "full" },
      { category: "web_category_block", label: "Category Blocking", support: "full" },
      { category: "time_daily_limit", label: "Daily Time Limits", support: "full" },
      { category: "time_scheduled_hours", label: "Screen Time Scheduling", support: "full" },
      { category: "time_per_app_limit", label: "Per-App Time Limits", support: "full" },
      { category: "content_rating", label: "App Management", support: "full" },
      { category: "web_safesearch", label: "Safe Search Enforcement", support: "full" },
    ],
    minAge: 4,
    maxAge: 17,
    tags: ["call-monitoring", "sms-control", "communication-safety", "deep-android", "geofencing"],
    featured: false,
  },

  {
    id: "kaspersky-safe-kids",
    slug: "kaspersky-safe-kids",
    name: "Kaspersky Safe Kids",
    description:
      "Kaspersky's parental control suite with GPS tracking, screen time management, web and YouTube filtering, and real-time alerts across all major platforms.",
    longDescription:
      "Kaspersky Safe Kids draws on Kaspersky's deep expertise in internet security to deliver a full-featured parental control solution. It provides real-time GPS tracking with geofencing alerts, screen time management with per-device schedules, web filtering with 14 content categories, YouTube search monitoring, battery level monitoring, and social media monitoring on VK. The free tier is surprisingly generous, offering web filtering and screen time management at no cost. Premium adds GPS tracking, real-time alerts, YouTube monitoring, and battery tracking. Available on Windows, macOS, iOS, and Android.",
    website: "https://www.kaspersky.com/safe-kids",
    iconEmoji: "\uD83D\uDD10",
    accentColor: "#00796B",
    sourceCategory: "parental_apps",
    pricingTier: "freemium",
    pricingDetails:
      "Free plan includes web filtering and screen time. Premium plan at $14.99/yr per family (often bundled with Kaspersky security suites).",
    apiAvailability: "no_api",
    devices: {
      iOS: true,
      android: true,
      windows: true,
      macOS: true,
      chromeos: false,
      fireos: false,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "web_filter_level", label: "Web Filtering", support: "full" },
      { category: "web_category_block", label: "Category Blocking (14 categories)", support: "full" },
      { category: "web_safesearch", label: "Safe Search Enforcement", support: "full" },
      { category: "time_daily_limit", label: "Daily Time Limits", support: "full" },
      { category: "time_scheduled_hours", label: "Scheduled Hours", support: "full" },
      { category: "time_per_app_limit", label: "Per-App Time Limits", support: "full" },
      { category: "monitoring_location", label: "GPS Tracking & Geofencing", support: "full" },
      { category: "monitoring_alerts", label: "Real-Time Alerts", support: "full" },
      { category: "monitoring_activity", label: "Activity Reports", support: "full" },
      { category: "content_rating", label: "YouTube Monitoring", support: "full" },
      { category: "social_media_min_age", label: "Social Media Monitoring", support: "full" },
      { category: "time_downtime", label: "Device Downtime", support: "full" },
    ],
    minAge: 3,
    maxAge: 17,
    tags: ["kaspersky", "gps-tracking", "youtube-monitoring", "generous-free-tier", "security-suite"],
    featured: false,
  },

  {
    id: "circle",
    slug: "circle",
    name: "Circle",
    description:
      "Router-level home network parental controls by Aura that filter and manage every connected device without installing software on individual devices.",
    longDescription:
      "Circle by Aura takes a unique network-level approach to parental controls. Instead of installing software on each device, Circle works at the router level to filter and manage internet access for every connected device in the home — including smart TVs, gaming consoles, and IoT devices that can't run apps. Parents create profiles for each family member with custom filter levels, time limits, bedtime schedules, and pause controls. The companion iOS and Android apps extend Circle's protections to mobile devices outside the home via a VPN. Circle integrates with Disney's content ratings and offers per-platform time limits (e.g., 1 hour of YouTube, 30 minutes of TikTok).",
    website: "https://meetcircle.com",
    iconEmoji: "\u2B55",
    accentColor: "#FF5722",
    sourceCategory: "parental_apps",
    pricingTier: "paid",
    pricingDetails:
      "Circle device at $69.99 (one-time). Circle subscription at $9.99/mo covers unlimited home devices plus mobile.",
    apiAvailability: "no_api",
    devices: {
      iOS: true,
      android: true,
      windows: false,
      macOS: false,
      chromeos: false,
      fireos: false,
      router: true,
      browser_extension: false,
    },
    capabilities: [
      { category: "web_filter_level", label: "Network-Level Filtering", support: "full" },
      { category: "web_category_block", label: "Category Blocking", support: "full" },
      { category: "web_safesearch", label: "Safe Search Enforcement", support: "full" },
      { category: "time_daily_limit", label: "Daily Time Limits", support: "full" },
      { category: "time_scheduled_hours", label: "Bedtime Scheduling", support: "full" },
      { category: "time_per_app_limit", label: "Per-Platform Time Limits", support: "full" },
      { category: "time_downtime", label: "Pause Internet", support: "full" },
      { category: "content_rating", label: "Content Rating Enforcement", support: "full" },
      { category: "monitoring_activity", label: "Usage History", support: "full" },
      { category: "monitoring_alerts", label: "Usage Alerts", support: "full" },
      { category: "monitoring_location", label: "Location Tracking", support: "full" },
      { category: "social_chat_control", label: "Chat Monitoring", support: "full" },
    ],
    minAge: 3,
    maxAge: 17,
    tags: ["router-level", "network-wide", "no-install", "smart-tv", "gaming-console", "aura"],
    featured: true,
  },

  {
    id: "gabb",
    slug: "gabb",
    name: "Gabb",
    description:
      "A kid-safe phone ecosystem with no internet browser, no social media, and no app store, providing essential phone features in a safe, curated environment.",
    longDescription:
      "Gabb offers a fundamentally different approach to children's mobile safety: instead of filtering a full-featured smartphone, Gabb provides purpose-built devices (Gabb Phone, Gabb Watch) that simply don't include a web browser, social media, app store, or games. Kids get essential communication features — calls, texts, GPS location, a camera, and music — without any exposure to the open internet. The Gabb ecosystem includes carrier service, parental controls via the MyGabb app, and a growing suite of kid-safe apps. For families who want to delay smartphone exposure while giving kids connectivity, Gabb offers a compelling middle ground.",
    website: "https://gabb.com",
    iconEmoji: "\uD83D\uDCDE",
    accentColor: "#26A69A",
    sourceCategory: "parental_apps",
    pricingTier: "bundled",
    pricingDetails:
      "Gabb Phone Plus at $99.99 (device) + monthly plans starting at $24.99/mo (includes cellular service and parental controls).",
    apiAvailability: "partner_api",
    apiDetails:
      "Gabb offers a documented API for integration with school and family management platforms. Access may require an API access agreement.",
    devices: {
      iOS: false,
      android: true,
      windows: false,
      macOS: false,
      chromeos: false,
      fireos: false,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "social_chat_control", label: "Contact Management", support: "full" },
      { category: "dm_restriction", label: "Messaging Controls", support: "full" },
      { category: "web_filter_level", label: "No Browser (Full Block)", support: "full" },
      { category: "content_rating", label: "Curated App Library", support: "full" },
      { category: "social_media_min_age", label: "No Social Media", support: "full" },
      { category: "monitoring_location", label: "GPS Location Tracking", support: "full" },
      { category: "monitoring_alerts", label: "Location Alerts", support: "full" },
      { category: "privacy_account_creation", label: "No Account Creation", support: "full" },
      { category: "purchase_block_iap", label: "No In-App Purchases", support: "full" },
      { category: "purchase_approval", label: "No App Store", support: "full" },
      { category: "time_daily_limit", label: "Screen Time Limits", support: "full" },
    ],
    minAge: 6,
    maxAge: 14,
    tags: ["dedicated-phone", "no-internet", "no-social-media", "kid-safe", "curated-apps"],
    featured: false,
  },

  {
    id: "pinwheel",
    slug: "pinwheel",
    name: "Pinwheel",
    description:
      "A smart phone for kids with a curated app library, gradual unlock system, and expert-backed approach to introducing technology responsibly.",
    longDescription:
      "Pinwheel provides smartphones designed specifically for kids, featuring a curated library of over 1,000 apps that have been reviewed by child development experts, educators, and parents. The unique Caregiver Portal lets parents control exactly which apps are available and gradually unlock more features as kids grow and demonstrate responsibility. Pinwheel's approach is rooted in the philosophy that kids need a guided on-ramp to technology rather than either full access or total restriction. The platform includes contact management, location tracking, customizable routines, and a growing ecosystem of educational and creative apps.",
    website: "https://www.pinwheel.com",
    iconEmoji: "\uD83C\uDFA1",
    accentColor: "#AB47BC",
    sourceCategory: "parental_apps",
    pricingTier: "bundled",
    pricingDetails:
      "Pinwheel phones from $99 (device). Caregiver subscription at $9.98/mo (includes app curation, controls, and cellular plan add-on).",
    apiAvailability: "partner_api",
    apiDetails:
      "Pinwheel offers managed API access for curated app providers and child safety platforms seeking integration.",
    devices: {
      iOS: false,
      android: true,
      windows: false,
      macOS: false,
      chromeos: false,
      fireos: false,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "content_rating", label: "Expert-Curated App Library", support: "full" },
      { category: "social_chat_control", label: "Contact Management", support: "full" },
      { category: "dm_restriction", label: "Messaging Controls", support: "full" },
      { category: "time_daily_limit", label: "Screen Time Limits", support: "full" },
      { category: "time_scheduled_hours", label: "Customizable Routines", support: "full" },
      { category: "monitoring_location", label: "Location Tracking", support: "full" },
      { category: "web_filter_level", label: "Web Filtering", support: "full" },
      { category: "web_category_block", label: "Category Blocking", support: "full" },
      { category: "privacy_account_creation", label: "Account Creation Control", support: "full" },
      { category: "purchase_approval", label: "App Approval System", support: "full" },
      { category: "purchase_block_iap", label: "In-App Purchase Control", support: "full" },
      { category: "monitoring_alerts", label: "Caregiver Alerts", support: "full" },
      { category: "monitoring_activity", label: "Usage Reports", support: "full" },
    ],
    minAge: 6,
    maxAge: 15,
    tags: ["dedicated-phone", "curated-apps", "gradual-unlock", "expert-reviewed", "caregiver-portal"],
    featured: true,
  },

  {
    id: "troomi",
    slug: "troomi",
    name: "Troomi",
    description:
      "Kid-safe smartphone with parent-approved apps, GPS tracking, and a safe messaging system — no social media, no open internet.",
    longDescription:
      "Troomi provides smartphones designed for kids that prioritize safety without sacrificing the connectivity families need. Running a custom version of Android, Troomi devices ship with no social media, no open internet browsing, and no app store. Parents use the Troomi Parent Portal to approve specific apps from a curated, safety-reviewed library and manage their child's contacts, messaging permissions, and GPS location. The KidSmart Apps program ensures every available app meets Troomi's child safety standards. Troomi's tiered plans let families start with basic talk-and-text and gradually add features as kids mature.",
    website: "https://www.troomi.com",
    iconEmoji: "\uD83C\uDF33",
    accentColor: "#66BB6A",
    sourceCategory: "parental_apps",
    pricingTier: "bundled",
    pricingDetails:
      "Troomi phones from $99 (device). Monthly plans from $19.95/mo (talk + text) to $29.95/mo (talk + text + curated apps + GPS).",
    apiAvailability: "no_api",
    devices: {
      iOS: false,
      android: true,
      windows: false,
      macOS: false,
      chromeos: false,
      fireos: false,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "content_rating", label: "Parent-Approved App Library", support: "full" },
      { category: "social_chat_control", label: "Safe Messaging System", support: "full" },
      { category: "dm_restriction", label: "Contact Approval", support: "full" },
      { category: "web_filter_level", label: "No Browser (Full Block)", support: "full" },
      { category: "social_media_min_age", label: "No Social Media", support: "full" },
      { category: "monitoring_location", label: "GPS Location Tracking", support: "full" },
      { category: "purchase_approval", label: "No App Store", support: "full" },
      { category: "purchase_block_iap", label: "No In-App Purchases", support: "full" },
      { category: "privacy_account_creation", label: "No Account Creation", support: "full" },
      { category: "time_daily_limit", label: "Screen Time Limits", support: "full" },
      { category: "monitoring_alerts", label: "Parent Alerts", support: "full" },
    ],
    minAge: 6,
    maxAge: 14,
    tags: ["dedicated-phone", "no-internet", "kid-safe-apps", "safe-messaging", "parent-portal"],
    featured: false,
  },

  // ─────────────────────────────────────────────────────────────────
  // BUILT-IN PLATFORM CONTROLS
  // ─────────────────────────────────────────────────────────────────

  {
    id: "apple-screen-time",
    slug: "apple-screen-time",
    name: "Apple Screen Time",
    description:
      "Apple's built-in parental controls for iPhone, iPad, and Mac with app limits, downtime scheduling, content restrictions, communication limits, and Family Sharing integration.",
    longDescription:
      "Apple Screen Time is the native parental control system built into iOS, iPadOS, and macOS. Through Family Sharing, parents can remotely manage their children's devices with granular controls: daily app category limits, scheduled downtime, explicit content restrictions based on age ratings, communication limits (restricting who kids can call, text, and FaceTime), and Ask to Buy for App Store and iTunes purchases. Screen Time provides detailed weekly usage reports broken down by app and category. For enterprise and education environments, these controls are fully configurable via Mobile Device Management (MDM) profiles, making Apple Screen Time one of the few built-in solutions with a robust programmatic API.",
    website: "https://support.apple.com/en-us/108806",
    iconEmoji: "\uD83C\uDF4E",
    accentColor: "#000000",
    sourceCategory: "builtin_controls",
    pricingTier: "free",
    pricingDetails:
      "Included free with all Apple devices running iOS 12+, iPadOS 13+, and macOS Catalina+.",
    apiAvailability: "public_api",
    apiDetails:
      "Fully configurable via Apple MDM (Mobile Device Management) profiles. Restrictions payloads, app lock, web content filter, and Screen Time configuration profiles are documented in Apple's Device Management framework.",
    devices: {
      iOS: true,
      android: false,
      windows: false,
      macOS: true,
      chromeos: false,
      fireos: false,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "time_daily_limit", label: "App Category Limits", support: "full" },
      { category: "time_per_app_limit", label: "Per-App Time Limits", support: "full" },
      { category: "time_scheduled_hours", label: "Scheduled Downtime", support: "full" },
      { category: "time_downtime", label: "Downtime Mode", support: "full" },
      { category: "content_rating", label: "Age-Based Content Restrictions", support: "full" },
      { category: "web_filter_level", label: "Web Content Filtering", support: "full" },
      { category: "web_safesearch", label: "Explicit Content Block", support: "full" },
      { category: "purchase_approval", label: "Ask to Buy", support: "full" },
      { category: "purchase_block_iap", label: "In-App Purchase Restriction", support: "full" },
      { category: "social_chat_control", label: "Communication Limits", support: "full" },
      { category: "monitoring_activity", label: "Weekly Usage Reports", support: "full" },
      { category: "monitoring_location", label: "Find My / Location Sharing", support: "full" },
      { category: "privacy_account_creation", label: "Child Apple ID Management", support: "full" },
      { category: "notification_curfew", label: "Downtime Notification Silence", support: "full" },
      { category: "privacy_data_sharing", label: "Privacy Controls", support: "full" },
    ],
    minAge: 0,
    maxAge: 17,
    tags: ["apple", "native", "mdm", "family-sharing", "ask-to-buy", "communication-limits"],
    featured: true,
    platformRegistryId: "apple_mdm",
  },

  {
    id: "google-family-link",
    slug: "google-family-link",
    name: "Google Family Link",
    description:
      "Google's built-in parental controls for Android and ChromeOS with app approval, screen time limits, device location, content filtering, and Google account supervision.",
    longDescription:
      "Google Family Link provides comprehensive parental controls built into Android and ChromeOS devices. Parents create supervised Google Accounts for children under 13, giving them visibility and control over their child's digital experience. Key features include app approval from the Play Store, daily screen time limits, device bedtime scheduling, Google Chrome web filtering, Google Search SafeSearch enforcement, YouTube Restricted Mode, and real-time device location tracking. Family Link also controls what data the child's Google account can access and share. The Family Link app on the parent's phone serves as a remote control panel. For Chromebook users, Family Link extends to manage ChromeOS device policies, website permissions, and educational app access.",
    website: "https://families.google.com/familylink",
    iconEmoji: "\uD83D\uDC68\u200D\uD83D\uDC69\u200D\uD83D\uDC67",
    accentColor: "#4285F4",
    sourceCategory: "builtin_controls",
    pricingTier: "free",
    pricingDetails:
      "Included free with all Android 7.0+ devices and ChromeOS. Requires a supervised Google Account.",
    apiAvailability: "public_api",
    apiDetails:
      "Android Management API and Chrome Policy API provide programmatic device management. Google Workspace for Education APIs extend Family Link policies for school environments.",
    devices: {
      iOS: false,
      android: true,
      windows: false,
      macOS: false,
      chromeos: true,
      fireos: false,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "time_daily_limit", label: "Daily Screen Time Limits", support: "full" },
      { category: "time_scheduled_hours", label: "Bedtime Scheduling", support: "full" },
      { category: "time_downtime", label: "Device Lock", support: "full" },
      { category: "content_rating", label: "Play Store Content Ratings", support: "full" },
      { category: "web_filter_level", label: "Chrome Web Filtering", support: "full" },
      { category: "web_safesearch", label: "SafeSearch Enforcement", support: "full" },
      { category: "web_category_block", label: "Site Blocking", support: "full" },
      { category: "purchase_approval", label: "Play Store Approval", support: "full" },
      { category: "purchase_block_iap", label: "Purchase Authentication", support: "full" },
      { category: "monitoring_activity", label: "Activity Reports", support: "full" },
      { category: "monitoring_location", label: "Device Location", support: "full" },
      { category: "monitoring_alerts", label: "App Install Alerts", support: "full" },
      { category: "privacy_account_creation", label: "Supervised Account", support: "full" },
      { category: "privacy_data_sharing", label: "Google Account Data Controls", support: "full" },
    ],
    minAge: 0,
    maxAge: 17,
    tags: ["google", "android", "chromeos", "supervised-account", "play-store", "safesearch"],
    featured: true,
    platformRegistryId: "android",
  },

  {
    id: "microsoft-family-safety",
    slug: "microsoft-family-safety",
    name: "Microsoft Family Safety",
    description:
      "Microsoft's built-in family controls for Windows, Xbox, and mobile with screen time limits, content filters, spending controls, and activity reporting.",
    longDescription:
      "Microsoft Family Safety provides parental controls across the Microsoft ecosystem — Windows PCs, Xbox consoles, and companion mobile apps. Parents create a Microsoft family group and add child accounts to manage screen time across all linked devices with shared or per-device limits. Content restrictions leverage age-based ratings for apps, games, and media in the Microsoft Store and Xbox. Web and search filtering in Microsoft Edge blocks inappropriate content, while activity reports provide weekly email summaries of browsing, app usage, and search activity. Spending controls manage Microsoft Store purchases with allowance and approval features. The companion mobile apps for iOS and Android add location tracking and driving safety reports.",
    website: "https://family.microsoft.com",
    iconEmoji: "\uD83E\uDE9F",
    accentColor: "#0078D4",
    sourceCategory: "builtin_controls",
    pricingTier: "free",
    pricingDetails:
      "Included free with Microsoft accounts. Premium features (location alerts, driving safety) available with Microsoft 365 Family ($99.99/yr).",
    apiAvailability: "no_api",
    apiDetails:
      "Microsoft Graph API provides limited family group management. Full parental control configuration is not currently exposed through public APIs.",
    devices: {
      iOS: false,
      android: false,
      windows: true,
      macOS: false,
      chromeos: false,
      fireos: false,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "time_daily_limit", label: "Screen Time Limits", support: "full" },
      { category: "time_scheduled_hours", label: "Scheduled Hours", support: "full" },
      { category: "time_per_app_limit", label: "Per-App Time Limits", support: "full" },
      { category: "content_rating", label: "Age-Based Content Restrictions", support: "full" },
      { category: "web_filter_level", label: "Edge Web Filtering", support: "full" },
      { category: "web_safesearch", label: "Bing SafeSearch", support: "full" },
      { category: "web_category_block", label: "Website Blocklist", support: "full" },
      { category: "purchase_approval", label: "Spending Approval", support: "full" },
      { category: "purchase_block_iap", label: "Store Purchase Controls", support: "full" },
      { category: "monitoring_activity", label: "Weekly Activity Reports", support: "full" },
      { category: "monitoring_location", label: "Location Tracking (Mobile)", support: "full" },
      { category: "monitoring_alerts", label: "Activity Email Summaries", support: "full" },
      { category: "time_downtime", label: "Device Lock", support: "full" },
    ],
    minAge: 0,
    maxAge: 17,
    tags: ["microsoft", "windows", "xbox", "edge", "spending-controls", "family-group"],
    featured: true,
    platformRegistryId: "microsoft",
  },

  {
    id: "amazon-kids-plus",
    slug: "amazon-kids-plus",
    name: "Amazon Kids+",
    description:
      "Amazon's curated subscription for Fire tablets and Kindle with thousands of age-appropriate books, apps, games, and videos in a walled-garden environment.",
    longDescription:
      "Amazon Kids+ (formerly FreeTime Unlimited) transforms Fire tablets and Kindle devices into kid-safe environments with a curated library of thousands of age-appropriate books, apps, games, videos, and Audible audiobooks. The Parent Dashboard lets parents set daily screen time limits, educational goals (e.g., require 30 minutes of reading before games unlock), bedtime curfews, and content filters by age range. Amazon's age-appropriate content filters automatically adjust available content based on the child's age. The interface is designed specifically for kids with colorful profiles and easy navigation. Smart content filters ensure kids only see content appropriate for their age group, and all web browsing is restricted to a curated set of age-appropriate websites.",
    website: "https://www.amazon.com/ftu/home",
    iconEmoji: "\uD83D\uDCDA",
    accentColor: "#FF9900",
    sourceCategory: "builtin_controls",
    pricingTier: "bundled",
    pricingDetails:
      "Amazon Kids (basic controls) is free on Fire devices. Amazon Kids+ subscription: $4.99/mo for Prime members, $7.99/mo without Prime, or $2.99/mo per child.",
    apiAvailability: "no_api",
    devices: {
      iOS: false,
      android: false,
      windows: false,
      macOS: false,
      chromeos: false,
      fireos: true,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "content_rating", label: "Age-Appropriate Content Curation", support: "full" },
      { category: "time_daily_limit", label: "Daily Time Limits", support: "full" },
      { category: "time_scheduled_hours", label: "Bedtime Curfew", support: "full" },
      { category: "time_downtime", label: "Educational Goals Gate", support: "full" },
      { category: "web_filter_level", label: "Curated Web Browsing", support: "full" },
      { category: "web_category_block", label: "Website Allowlist", support: "full" },
      { category: "purchase_approval", label: "Purchase Prevention", support: "full" },
      { category: "purchase_block_iap", label: "In-App Purchase Block", support: "full" },
      { category: "monitoring_activity", label: "Usage Dashboard", support: "full" },
      { category: "privacy_account_creation", label: "Child Profile Management", support: "full" },
      { category: "social_media_min_age", label: "No Social Media Access", support: "full" },
    ],
    minAge: 3,
    maxAge: 12,
    tags: ["amazon", "fire-tablet", "kindle", "curated-content", "educational-goals", "walled-garden"],
    featured: false,
  },

  {
    id: "samsung-kids",
    slug: "samsung-kids",
    name: "Samsung Kids",
    description:
      "Samsung's built-in kids mode for Galaxy devices with a colorful kid-friendly interface, curated apps, screen time controls, and content restrictions.",
    longDescription:
      "Samsung Kids is a dedicated kids mode built into Samsung Galaxy smartphones and tablets. When activated, it replaces the standard home screen with a bright, playful interface containing only parent-approved apps and content. Samsung Kids includes a curated collection of educational apps, creative tools (drawing, music, camera with fun filters), and age-appropriate games. Parents control which apps are accessible, set daily usage limits, and restrict access to phone features like the camera, contacts, and Samsung Internet. The mode is protected by PIN so children cannot exit without parental permission. Samsung Kids also includes My Art, My Camera, My Browser (with curated sites only), and integration with Samsung's broader family management features.",
    website: "https://www.samsung.com/us/apps/samsung-kids",
    iconEmoji: "\u2B50",
    accentColor: "#1428A0",
    sourceCategory: "builtin_controls",
    pricingTier: "free",
    pricingDetails:
      "Included free on Samsung Galaxy devices running One UI 2.0+. No subscription required.",
    apiAvailability: "no_api",
    devices: {
      iOS: false,
      android: true,
      windows: false,
      macOS: false,
      chromeos: false,
      fireos: false,
      router: false,
      browser_extension: false,
    },
    capabilities: [
      { category: "content_rating", label: "Curated App Selection", support: "full" },
      { category: "time_daily_limit", label: "Daily Usage Limits", support: "full" },
      { category: "time_downtime", label: "Kids Mode Lock", support: "full" },
      { category: "web_filter_level", label: "Curated Web Browsing", support: "full" },
      { category: "web_category_block", label: "Website Allowlist", support: "full" },
      { category: "purchase_approval", label: "No Store Access", support: "full" },
      { category: "purchase_block_iap", label: "No In-App Purchases", support: "full" },
      { category: "privacy_account_creation", label: "PIN-Protected Profile", support: "full" },
      { category: "monitoring_activity", label: "Usage Reports", support: "full" },
      { category: "social_media_min_age", label: "No Social Media Access", support: "full" },
      { category: "monitoring_location", label: "Location Tracking", support: "full" },
    ],
    minAge: 3,
    maxAge: 10,
    tags: ["samsung", "galaxy", "kids-mode", "curated-apps", "creative-tools", "pin-protected"],
    featured: false,
  },
]
